### ISSUE TITLE
Fix 'age_group_hebrew' field for years 2008, 2009

### ISSUE THREAD

**Issue by yoni2k** [hasadna/anyway#1031]
`age_group_hebrew` is not accurate in years 2008 and 2009.
`age_group` is accurate, but `age_group_hebrew` is not.
`age_group == 2` (ages `05-09`) is split in `age_group_hebrew` into values `05-09` and `05-ספטמבר`
`age_group == 3` (ages `10-14`) is split in `age_group_hebrew` into values `10-14` and `אוקטובר-14`

Need to fix it in our DB

Numbers add up to the same number when combining occurrences: 
![image](https://user-images.githubusercontent.com/47971445/68389027-a4b97480-016a-11ea-864f-594ed11cd5c3.png)

Appears only in 2008 and 2009:
![image](https://user-images.githubusercontent.com/47971445/68389042-aedb7300-016a-11ea-9338-6a11615b171d.png)

**Comment by atalyaalon** [comment]
Thank you @MichalOren ! Great Work!

Relevant queries:
`update age_group
set age_group_hebrew = '05-09'
where year in (2008,2009) AND age_group.provider_code = 1 AND id=2;`

`update age_group
set age_group_hebrew = '10-14'
where year in (2008,2009) AND age_group.provider_code = 1 AND id=3;`

And Thank you @yoni2k for opening this issue.
