### ISSUE TITLE
change max date 

### ISSUE THREAD

**Issue by atalyaalon** [hasadna/anyway#1042]
change max date to be the maximal date in the data and not current date (we are usually in ~2 months delay - depending on when the CBS are sending the data)
<img width="292" alt="Screen Shot 2019-12-10 at 11 42 55" src="https://user-images.githubusercontent.com/20992625/70518068-5ec54700-1b42-11ea-82f5-532049485ab4.png">

**Comment by atalyaalon** [comment]
@sa1omon any news on this one?

**Comment by sa1omon** [comment]
> @sa1omon any news on this one?

Done :)

**Comment by atalyaalon** [comment]
@sa1omon great work
