### ISSUE TITLE
Additional News Flash API

### ISSUE THREAD

**Issue by atalyaalon** [hasadna/anyway#1073]
Current API: https://anyway.co.il/api/news-flash
Please create another API that: https://anyway.co.il/api/news-flash-filters
1. Enables to pull from a specific source
for example: https://anyway.co.il/api/news-flash-filters?source=ynet pulls all news flashes from ynet

2. If news_flash_count specified - Pulls X last news-flashes from each source

for example: https://anyway.co.il/api/news-flash-filters?source=ynet&news_flash_count=100
pulls 100 last news flashes from ynet (when choosing, please order by date field)

for example: https://anyway.co.il/api/news-flash-filters?news_flash_count=100
pulls 100 last news flashes from all sources (when choosing, please order by date field)

3. If start_date and end_date specified, pulls all news flashes in those dates

for example: https://anyway.co.il/api/news-flash-filters?start_date=01-01-2019&end_date=03-01-2019 pulls all news flashes from January 1st to January 3nd (including January 3rd)

for example: https://anyway.co.il/api/news-flash-filters?start_date=01-01-2019&end_date=03-01-2019&source=ynet 
pulls all ynet news flashes from January 1st to January 3nd (including January 3rd)

Also, please add documentation in our internal document.

**Comment by advak** [comment]
https://github.com/hasadna/anyway/pull/1088
