### ISSUE TITLE
Move Production to KamaTera

### ISSUE THREAD

**Issue by atalyaalon** [hasadna/anyway#1110]
including:

1. Two containers - app and db
2. App container: Python 3 running
3. CI - build containers and update DB schema when pushing to master.
4. Staging Server
~~5. DB daily backup~~ Duplication of this issue #951
6. Newflash crontab running
7. Keeping secrets that will be environment variables in k8
8. Having access for specific authorized people to our production app so we can run commands there if necessary (for example, a command for loading data)

**Comment by cubann** [comment]
@atalyaalon Any chance that  
> 5\. DB daily backup

is this issue #951 ?

**Comment by atalyaalon** [comment]
@cubann yes, please assign yourself
