### ISSUE TITLE
Cache infographics_data

### ISSUE THREAD

**Issue by atalyaalon** [hasadna/anyway#1200]
At the moment, the /api/infographics_data (see flask_app.py) is calculated for every API call.
We want to 
1. Create a table in our DB that will contain the API jsons for every news flash (key: tuple of news_flash_id and years_ago (arguments sent in the request), data - the output object in infographics_data.
2. Update the API to pull from this table
3. Create a function that updates this table for all of the current news flashes in our db.
4. Make sure that the table is updated using the function written in 3. First stage will be once a day in a crontab (for that talk to our @hasadna/anyway-devops team when you'll get to it. 
Make sure we're consistent (meaning that the whole table is updated at the same moment).

**Comment by ziv17** [comment]
Hi @atalyaalon , why do we need the years_ago as part of the key?

**Comment by atalyaalon** [comment]
@ziv17 since data we send will be different if we look at 1 or 3 or 5 or 8 years back.

**Comment by ziv17** [comment]
Hi @atalyaalon , in (2), if item is not found in the cache, I assume we want to do the regular calculation.

**Comment by atalyaalon** [comment]
@ziv17 sounds good to me
