### ISSUE TITLE
Add front collision count relative to other accidents count to infographics api

### ISSUE THREAD

**Issue by BarVolunteering** [hasadna/anyway#1201]
Add front collision count relative to other accidents count to infographics api

**Comment by atalyaalon** [comment]
@BarVolunteering please add the image as well

**Comment by BarVolunteering** [comment]
This issue is about implementing the 5th widget(marked in red)
![image](https://user-images.githubusercontent.com/58947331/80024521-e0ad7f80-84e7-11ea-8571-d20eb66556d3.png)
