### ISSUE TITLE
Add table of all years in which there are accidents

### ISSUE THREAD

**Issue by danielhers** [hasadna/anyway#122]
After loading the data in process.py, update the table to include all distinct years in which there are accidents.
This will be used for #121 so that we don't have to dynamically perform this distinct calculation.

**Comment by omerxx** [comment]
@danielhers is this still required?

**Comment by danielhers** [comment]
Yes, the years are still hard coded...

**Comment by omerxx** [comment]
If I exported the years into a python list based on the structure of the JS hard coded array:
`dict = { 'year 2000' : ['01/01/2000', '31/12/2000'] }` then used `json.dumps` so it would be readable.
How can I read the data in `app.js`? I don't know how to refer to the dictionary from process.py and if that's even possible?

**Comment by danielhers** [comment]
It's not related to process.py.
If we want it to come from the server, we just need to add a route in
main.py that will read this table and send a json of the years.
However, it's better if this is cached statically and sent from a CDN.
There's an issue about that (making index.html static), but we haven't done
that yet because I don't really know how. The plan is to use Amazon Web
Services S3.

**Comment by omerxx** [comment]
I've written the json for years on the server to a file.
The client pulls it in app.js
Is this an acceptable solution?

@OmerSchechter  I just put the structure in a `var YEARS={...}` and let `ranges: YEARS'
That was finally accepted by `dateRangePicker`

**Comment by OmerSchechter** [comment]
@omerxx Wait, so it's working right now? because i'm currently tinkering around with it..

**Comment by omerxx** [comment]
Yup. looks fine. thanks

**Comment by omerxx** [comment]
@danielhers / @njenia 
My fix is creating the years string once `process.py` completes its data population.
(this is the one case I can think of that year choices will need an update) 
The string is saved in a new file `years.js` and is loaded in the assets.

The one problem is that we expect over 10 years of possible choices (and this is just a current stat, in the future it should be many more). Should I set the string to show them all or just some of the last ones?

Another matter - should the date be until 31/12/year or 01/01/nextYear (as it is now)?

Is this solution accepted?
