### ISSUE TITLE
Import all road images from wikipedia

### ISSUE THREAD

**Issue by atalyaalon** [hasadna/anyway#1221]
Create a script that imports all road images svgs from https://he.wikipedia.org/wiki/%D7%9B%D7%91%D7%99%D7%A9%D7%99_%D7%99%D7%A9%D7%A8%D7%90%D7%9C

For example: road2 image: https://he.wikipedia.org/wiki/%D7%9B%D7%91%D7%99%D7%A9%D7%99_%D7%99%D7%A9%D7%A8%D7%90%D7%9C#/media/%D7%A7%D7%95%D7%91%D7%A5:ISR-HW-2.svg

**Comment by reuvenz1993** [comment]
1. Is there a preferred approach- web scraping or query string manipulation?
2. Where should this code be integrated?

Thank you :)

**Comment by atalyaalon** [comment]
@reuvenz1993 
1. no - we use python - so I prefer you'll use python for that
2. we'll integrate it in the backend
3. next phase will be to save the data in a repo in aws with these images

**Comment by yossich6** [comment]
@reuvenz1993 are you working on it? If so please assign this issue under your user name

**Comment by VickySidorkin** [comment]
https://github.com/hasadna/anyway/pull/1292
