### ISSUE TITLE
Apostrophe in API is translated to &apos

### ISSUE THREAD

**Issue by atalyaalon** [hasadna/anyway#1232]
See the title section in the API of the following news flash:
https://anyway.co.il/api/news-flash/25768 (the Hebrew word ג׳יפ)
However, in redash we see the Hebrew part perfectly good (see images)

How should we handle such characters? perhaps we can change the way we dump the data before sending the response?

<img width="683" alt="Screen Shot 2020-05-06 at 19 29 40" src="https://user-images.githubusercontent.com/20992625/81203057-22522600-8fd0-11ea-9452-34dd5b0dbe4a.png">
<img width="1082" alt="Screen Shot 2020-05-06 at 19 29 30" src="https://user-images.githubusercontent.com/20992625/81203064-25e5ad00-8fd0-11ea-9656-02b082579aa2.png">

**Comment by idosavion** [comment]
looking into it

**Comment by idosavion** [comment]
It seems like the data is stored in the wrong format, but I couldn't find where it is parsed/ crawled. would be happy to get some help/ get access to redash/db to dig a little deeper.

**Comment by atalyaalon** [comment]
@Mano3 can explain how data is processed and stored.
Regarding redash - sending you a pm

**Comment by Mano3** [comment]
@idosavion 
The code itself is stored in anyway/parsers/news_flash.
What do you mean by wrong format?
I think there might be just differences in formats, which could be solved without changing how the data is stored

**Comment by idosavion** [comment]
![image](https://user-images.githubusercontent.com/18330067/82581310-130ad500-9b99-11ea-8e92-d4a59f8df0ae.png)
I meant the data was scraped wrongly from ynet and the data within the DB is malformed (The problem is not with the deserialization of the object from the DB).

**Comment by Mano3** [comment]
@idosavion I think the data was scraped correctly. The parsing in the other hand is not perfect as seen, 
I'd suggest looking 
https://github.com/hasadna/anyway/blob/dev/anyway/parsers/news_flash/parsing_utils.py
(Get author, get description, etc..)
And here
https://github.com/hasadna/anyway/blob/dev/anyway/parsers/news_flash/beautiful_soup_news_flash_parse.py
(For use of these functions)
For ynet and Walla.
A simple replace for the strings will do in my opinion. 

If this problem also appears at MDA look here:
https://github.com/hasadna/anyway/blob/dev/anyway/parsers/mda_twitter/get_mda_tweets.py 
(Get MDA tweets)

**Comment by idosavion** [comment]
@Mano3
Thanks! Is there an easy/known way to reproduce the scraping and parsing process locally in order to debug it? found nothing in the tests

**Comment by atalyaalon** [comment]
Unfortunately not - however you are welcome to open an issue and add such tests

**Comment by nadavsh22** [comment]
Hi, iv'e checked the response from the rss request (ynet in this case) @Mano3  is correct, the data is scraped correctly. The &apos or any other special characters originate from parsing the HTML.
I tried replacing the parser for BeautifulSoup "html.parser" with "lxml" which seems to produce the desired behaviour.
