### ISSUE TITLE
Change the rank field in API to be in the meta part

### ISSUE THREAD

**Issue by atalyaalon** [hasadna/anyway#1242]
See [discussion here](https://github.com/hasadna/anyway-newsflash-infographics/issues/180)

Hence, instead of 

`'''
    Widget structure:
    {
        'name': str,
        'rank': int (Integer),
        'data': {
                 'items': list (Array) | dictionary (Object),
                 'text': dictionary (Object) - can be empty
                 }
        'meta': dictionary (Object) - can be empty
    }`

We'll have:

`'''
    Widget structure:
    {
        'name': str,
        'data': {
                 'items': list (Array) | dictionary (Object),
                 'text': dictionary (Object) - can be empty
                 }
        'meta': dictionary (Object) - Note: rank will be a key here, and the value will be the rank itself
    }`

Relevant file: infographics_utils.py

**Comment by yossich6** [comment]
''' Widget structure: {
     'name': str, 
    'data': { 
          'items': list (Array) | dictionary (Object), 
          'text': dictionary (Object) - can be empty }
   'meta': {
           <how to call this category?> dictionary (Object) - can be empty,
           'rank': int (Integer)
 }

Q: meta should hold a scope to categories? If so, what should be the name of - dictionary (Object) - can be empty?

**Comment by atalyaalon** [comment]
Widget structure: 
`{ 'name': str, 
   'data': { 'items': list (Array) | dictionary (Object),
                'text': dictionary (Object) - can be empty } 
 'meta': {'rank': int }}` 
In tne future we'll add 'meta' additional fields, perhaps also categories.
