### ISSUE TITLE
Add Casualties_Costs table to Anyway DB

### ISSUE THREAD

**Issue by MichalOren** [hasadna/anyway#1245]
Costs of casualties in LAMAS accidents base on נוהל פר"ת.
Assuming that journalists are interested in such an information aspect.
Add Casualties_Costs table to Anyway DB
[Casualties_Costs.xlsx](https://github.com/hasadna/anyway/files/4640607/Casualties_Costs.xlsx)
Find me for any clarification

Also - when creating the table, please make sure that column names are [snake_case](https://en.wikipedia.org/wiki/Snake_case)

**Comment by ziv17** [comment]
Hi @atalyaalon , is this a constant table? so the need is to create it and add the data items in the Excel file?

**Comment by atalyaalon** [comment]
@ziv17 yes, just like I did in embedded reports pr: https://github.com/hasadna/anyway/commit/c5e2c8821a320c65e05f0668aa5bbc2e20af39a1
I think it's better to have a csv and not an excel.

**Comment by atalyaalon** [comment]
@ziv17 note that unlike embedded reports, there is no need to add an API to this table.

**Comment by ziv17** [comment]
@atalyaalon , I understand the primary key is the type_ID. Should Injured_Type also be a primary key?

**Comment by atalyaalon** [comment]
@ziv17 I don't think it's very significant, whatever you think is ok.
