### ISSUE TITLE
Refactor scraping news flash

### ISSUE THREAD

**Issue by elazarg** [hasadna/anyway#1260]
The modules handling the scraping of news flash scraping require extensive refactoring.
Here's a non-exhaustive list of quality issues I see:

- [x]  Multiple occurrences of swallowed exceptions - I mean `Exception`s (catching `Exception`, even when logged, seems to be overkill).

- [x] Module-level side effects: `init_flask()`
- [x] Naming: Unclear separation of `news_flash_*` files and a `news_flash` folder. Noninformative long names; "scrap" instead of "scrape" (the correct verb);  `beautiful_soup` as part of a file name. The database adapter is named `news_flash_parser`. Regular links are named `rss_link`.
- [x] `get_*` functions receive site as argument to dispatch completely different handling for each site; I believe this should be "transposed" to separate modules/classes/config for each site (group by site, not by task, since they are not similar). Moreover, it seems easy to create a single function that would return a dict[str, str] which will hide the difference in source from other parts of the parsing.
- [x] `u''` strings
- [x] Different classifier functions for ynet and twitter, using separate lists, hard coded inside the conditionals. The classifier for both walla and ynet is called `classify_ynet`.
- [x] Commented-out imports and other minor style issues such as non-PEP8 compliant spaces
- [x] Using deprecated `pd.np` instead of numpy directly.
- [x] Unnecessarily repeated fetching and parsing of news flashes, just to check if there are new ones.
- [ ] Duplicated logic for location extraction on `update_news_flash`
- [x] Use SQLAlchemy objects (`NewsFlash`) instead of hand crafted SQL.
Of course, to in order to make large changes, we need tests. I guess another issue is in order for that.

**Comment by elazarg** [comment]
More:
- [ ] Duplicated logic for location extraction on `update_news_flash`
- [ ] Use SQLAlchemy objects (`NewsFlash`) instead of hand crafted SQL.

**Comment by atalyaalon** [comment]
@elazarg I see we're left with one sub-issue here of Duplicated logic for location extraction on `update_news_flash`.
Can you take this one and finalize this issue?
