### ISSUE TITLE
auto format python code

### ISSUE THREAD

**Issue by idosavion** [hasadna/anyway#1286]
Since the number of contributors in the project is getting bigger,
some standardisation is required in the codebase to ease readability,
it will also us to focus on more important stuff when reviewing PRs.

black was adopted by the python community and could be easily integrated into the project

**Comment by elazarg** [comment]
The transition will introduce huge code churn, and should not be performed lightly.

Also, black is still in a beta phase:
https://github.com/psf/black#note-this-is-a-beta-product

**Comment by elazarg** [comment]
Also, I'm in favor of the move - in principle. It should be quite slow however. Or happen when we know nobody is working on the codebase.

**Comment by idosavion** [comment]
1. This is a huge code churn, but I don't understand how it is considered a problem.
Anyone who is working on a PR can just format the code with black and ignore the changes in the file he is working on.
2. I haven't notice a change in black's style in the last couple of months, but removing it from the project if required is fairly simple (we only need to remove the test, right?)
