### ISSUE TITLE
Handle 05', 06', 07' accidents files of format 1

### ISSUE THREAD

**Issue by danielhers** [hasadna/anyway#136]
Some data directories (for example from 2007) contain the data in a `.txt` file with tab-separated values, rather than `csv`. They should be handled as well and loaded in `process.py`.

**Comment by danielhers** [comment]
No one is currently working on this. When running `process.py` after getting the complete data file (see Readme), some files fail to load.

**Comment by omerxx** [comment]
I manually imported the txt files to csv so they can be read.
I noticed that the missing accidents (2005, 2006, 2007 of Type1) don't have latitude and longitude values.
Is there any reason to import them if we can't present them on a map?

**Comment by danielhers** [comment]
No, I don't think there's a reason to load accidents with no location.

**Comment by omerxx** [comment]
@galraij Can you check why 2005, 2006, 2007 of Type1 accidents don'y have location values?
If it's a mistake let's get the original files. If it's not we can delete them from our data store

**Comment by omerxx** [comment]
According to the LMS documentation, in years 05 06 07, lat&long coordinates were not documented
