### ISSUE TITLE
News Flash duplicates

### ISSUE THREAD

**Issue by atalyaalon** [hasadna/anyway#1362]
As of now, process runs once in 30 minutes - and duplicates of news flash are inserted into the db. We want to get to the bottom of this.

**Comment by elazarg** [comment]
I think the culprit is here https://github.com/hasadna/anyway/blob/1620631c7af61e5a1b26c7cc1a9b4caa94eef3ed/anyway/parsers/news_flash_db_adapter.py#L166

The date is loaded as UTC, but `replace` does not move it to a new TZ; it merely rewrites the timezone. It should probably be `astimezone`.
