### ISSUE TITLE
Review bumping of werkzeug

### ISSUE THREAD

**Issue by atalyaalon** [hasadna/anyway#1363]
In previous time we tried to bump this version - it caused issues with alembic upgrade head command.
Do these issues still exist?
Maybe we can bump it to a later version, even of not last.

Relevant PR: https://github.com/hasadna/anyway/pull/1338

**Comment by yossich6** [comment]
can you describe what kind of problems you've noticed?

**Comment by yossich6** [comment]
and what you mean by alembic upgrade?

**Comment by atalyaalon** [comment]
@yossich6 we use alembic to manage db versions.
The command alembic upgrade head is use to upgrade the db after creating a new version (for example when creating a new table). PM for more information
