### ISSUE TITLE
Remove legacy code from news flash parser folder

### ISSUE THREAD

**Issue by Mano3** [hasadna/anyway#1390]
Since @elazarg incredible refactor, a lot of files became deprecated, there are also some functions that are deprecated in files that are being used.
I would appreciate if only code that is usable in production (via the current scraping flow) would remain in the codebase, any legacy code has got to go.
For example, as far as I understand news_flash folder is deprecated and everything is handled via location_extraction.py and news_flash_*.py files in the parsers folder. This is just an example, there are more legacy files in this folder regarding news flash parsing.
Maybe they all should be moved to a newly created news_flash for organization of files.

**Comment by elazarg** [comment]
Oh. I thought I have removed them already.
