### ISSUE TITLE
Collect DB logs

### ISSUE THREAD

**Issue by atalyaalon** [hasadna/anyway#1409]
As of now - logging_collector of the DB in production is off.
Please change this configuration in the docker-compose or db Dockerfile so logging_collector will be on - to find errors.

**Comment by atalyaalon** [comment]
@OriHoch any thoughts or suggestions on this one?

**Comment by OriHoch** [comment]
don't you get these DB errors in the application log?

**Comment by OriHoch** [comment]
you can try to see what it does but I don't think it's worth to keep this option on long-term because it adds overhead without any benefit as you should get all error logs from the app logs
