### ISSUE TITLE
Perform db session rollback in the case of exception during commit

### ISSUE THREAD

**Issue by atalyaalon** [hasadna/anyway#1410]
We get the following error: `ERROR: current transaction is aborted, commands ignored until end of transaction block`

Seems like a db command is failing somewhere in the code, but transaction isn't closed and we cannot perform other queries to the db. 

A few suggestions for solution and/or debugging:

1. Adding `db.session.rollback()` after every db.session action, for example: `db.session.commit()` or `db.session.query` or `db.session.add`, etc - see [session_transaction](https://docs.sqlalchemy.org/en/13/orm/session_transaction.html)
2. Examining DB logs - finding the query that failed ([relevant issue for adding logs](https://github.com/hasadna/anyway/issues/1409))

**Comment by atalyaalon** [comment]
@OriHoch any suggestions on this one?

**Comment by OriHoch** [comment]
this should be checked in app logs, not in DB logs, the app should be able to identify where DB updates are being done and where there are failures

**Comment by OriHoch** [comment]
the logs in Google Stackdriver show a lot of details, including full SQL statement which failed

**Comment by atalyaalon** [comment]
Thanks @OriHoch , we'll check it out. 
However, I believe that rolling back in exception is still a good code practice we should use, what do you think? (e.g see [here](https://stackoverflow.com/questions/2979369/databaseerror-current-transaction-is-aborted-commands-ignored-until-end-of-tra))

**Comment by OriHoch** [comment]
handling exceptions properly is always a good practice

**Comment by ziv17** [comment]
@atalyaalon 
How can I look at logs from the issue? I understand that the connection that we use has a very long transaction, that nothing is happening with it. In this case, a timeout on the connection should resolve the issue.
We can set timeout on the connection when initializing the enginge. The default is forever. I think that regardless of the current issue we should have a timeout.

**Comment by ziv17** [comment]
@atalyaalon 
In addition it makes sense to catch exception and perform rollback in all locations we perform database actions. We should decide what to do after the rollback. I mean, whether to return empty result, error, or throw an application-level exception.

**Comment by OriHoch** [comment]
@ziv17 logs are in google console, but there is nothing useful there, if you want contact me in slack and I can give you access (if @atalyaalon approves)

regarding timeouts, I think the default driver options are very good, and we would like to keep long running sessions for performance and to keep resources low. Also, timeouts won't definitively solve the problem, only perhaps make it less frequent.

I looked at the code for possible problems, and I think I found a good candidate: https://github.com/hasadna/anyway/blob/dev/anyway/infographics_utils.py#L745

@atalyaalon we should not use threads / multiprocessing in the web server as it requires some special handling regarding the DB connections. Even if it has max_workers=1 I think it still runs that single worker in a new thread.

Also, I think the infographics cache is quite heavy on the DB, it's worth to consider a dedicated cache like Redis, would perform much better and keep the DB free to do what it does best. It's easy to deploy a Redis server and use it in the infographics cache code.

**Comment by OriHoch** [comment]
https://www.psycopg.org/docs/faq.html#problems-with-transactions-handling

**Comment by ziv17** [comment]
I am confused.
Isn't the documentation says specifically that regular threads are supported? (Are we using a different kind of thread in the location you pointed out?)
I am concerned that limiting ourselves to work without concurrency might be a limitation.

Regarding the cache. Currently it has less than 2k entries, that are written once a day. There is a single read operations from the cache per infografics end-user request. Is this too problematic for our database?

Regarding the transaction timeout. The documentation specifically recommends to close transactions: 
`If you are writing a long-living program, you should probably make sure to call one of the transaction closing methods before leaving the connection unused for a long time (which may also be a few seconds`
I understand we intend to specifically close all transactions after we got the data we need. This means that if we do have a long standing transaction, it is a mistake. And if it is a transaction with an error, we will probably be better off if it will be closed by a timeout rather than hang the next request.

**Comment by OriHoch** [comment]
yes, regular threads are supported but also require some specific setting up of the connection which we are not doing at the moment, and may be hard to do as we have multiple layers of abstraction on top of the psycopg2 driver

The web app is already running in a concurrent way with multiple levels of concurrency via multiple abstraction layers - Kubernetes, sqlalchemy, flask-sqlalchemy, flask, gunicorn

I'm not familiar with the specific requirement regarding cache, just a matter of using the right tool for the job

regarding closing transactions - this is managed in the other layers, specifically in sqlalchemy and flask-sqlalchemy, it is handled as specified in the docs

**Comment by OriHoch** [comment]
currently I'm seeing spikes in DB RAM/CPU usage which correspond to the fill infographics cache task, I believe this can be prevented by using a dedicated in memory cache like redis

keeping consistent resource usage allows to optimize the overall cluster resources, as everything runs on a single shared cluster for all hasadna projects (not on dedicated servers)

![image](https://user-images.githubusercontent.com/1198854/90647485-07cf5000-e241-11ea-9ae8-e22b73bc66c0.png)

**Comment by ziv17** [comment]
OK.
@atalyaalon , how do you want to continue with this?

**Comment by OriHoch** [comment]
I opened a PR which removes the thread implementation, I didn't test it, please test and merge to see if it eliminates the errors - https://github.com/hasadna/anyway/pull/1424

**Comment by atalyaalon** [comment]
@OriHoch I approve access to logs for @ziv17 
Also - thank you for your pr - @ziv17  -  can you go over @OriHoch 's pr and approve / require fixes if needed?

@assafdayan FYI - please go over this correspondence
@ziv17 and @assafdayan  -  following this correspondence and when planning the architecture - we might have to consider using Redis (I believe @assafdayan suggested it in the past)
I'll talk to you both at the beginning of next week.

Thank you all! Great work!

**Comment by atalyaalon** [comment]
Also - @ziv17 and @OriHoch - regarding this issue - I still believe we'll have to handle this issue in some way.
I think I know how to reconstruct such exception - will try to do it this Saturday and will let you know how to reproduce.

**Comment by OriHoch** [comment]
looks like the errors stopped, this may be due to several other changes - 
1. scheduled jobs are only run on the main pod, and web requests are only handled on secondary pods
2. DB resources were optimized

however, I still suggest to merge #1424 as it should definitively eliminate this problems in the future
