### ISSUE TITLE
Profiling backend for bottleneck detection

### ISSUE THREAD

**Issue by BarVolunteering** [hasadna/anyway#1456]
Starting with the /markers route:
https://github.com/hasadna/anyway/blob/cfdf305a681931f4ba7909f36c0c1e61b680ddc6/anyway/flask_app.py#L329

**Comment by BarVolunteering** [comment]
raw data:
`--------------------------------------------------------------------------------
PATH: '/markers'
         243672 function calls (213556 primitive calls) in 0.562 seconds

   Ordered by: internal time, call count
   List reduced from 1268 to 30 due to restriction <30>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
       10    0.101    0.010    0.101    0.010 {method 'execute' of 'psycopg2.extensions.cursor' objects}
        9    0.087    0.010    0.087    0.010 {method 'fetchmany' of 'psycopg2.extensions.cursor' objects}
56731/28371    0.072    0.000    0.141    0.000 /home/a/anyway/venv/lib/python3.8/site-packages/simplejson/encoder.py:571(_iterencode_dict)
    28347    0.061    0.000    0.089    0.000 /home/a/anyway/venv/lib/python3.8/site-packages/simplejson/encoder.py:471(_iterencode_list)
    28371    0.052    0.000    0.193    0.000 /home/a/anyway/venv/lib/python3.8/site-packages/simplejson/encoder.py:661(_iterencode)
        1    0.047    0.047    0.240    0.240 /home/a/anyway/venv/lib/python3.8/site-packages/simplejson/encoder.py:275(encode)
        1    0.010    0.010    0.011    0.011 {built-in method _imp.create_dynamic}
      193    0.010    0.000    0.034    0.000 /home/a/anyway/anyway/models.py:309(serialize)
     1671    0.008    0.000    0.012    0.000 /home/a/anyway/anyway/models.py:168(format_description)
        1    0.005    0.005    0.005    0.005 {built-in method psycopg2._psycopg._connect}
       10    0.004    0.000    0.004    0.000 {method 'read' of '_io.BufferedReader' objects}
    73/13    0.004    0.000    0.008    0.001 /usr/lib/python3.8/sre_parse.py:493(_parse)
     7928    0.004    0.000    0.004    0.000 /home/a/anyway/venv/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py:279(__get__)
      193    0.003    0.000    0.004    0.000 /home/a/anyway/venv/lib/python3.8/site-packages/sqlalchemy/orm/loading.py:710(_populate_full)
    34606    0.003    0.000    0.003    0.000 {built-in method builtins.isinstance}
      193    0.003    0.000    0.014    0.000 /home/a/anyway/anyway/models.py:303(<listcomp>)
        1    0.003    0.003    0.003    0.003 {method 'compress' of 'zlib.Compress' objects}
      193    0.002    0.000    0.008    0.000 /home/a/anyway/venv/lib/python3.8/site-packages/sqlalchemy/orm/loading.py:509(_instance)
   109/11    0.002    0.000    0.003    0.000 /usr/lib/python3.8/sre_compile.py:71(_compile)
     3067    0.002    0.000    0.002    0.000 /home/a/anyway/venv/lib/python3.8/site-packages/simplejson/encoder.py:453(_encode_int)
     1516    0.002    0.000    0.002    0.000 /usr/lib/python3.8/sre_parse.py:254(get)
     8262    0.002    0.000    0.002    0.000 {built-in method simplejson._speedups.encode_basestring_ascii}
      162    0.002    0.000    0.006    0.000 /home/a/anyway/venv/lib/python3.8/site-packages/sqlalchemy/sql/compiler.py:810(visit_label)
      162    0.001    0.000    0.013    0.000 /home/a/anyway/venv/lib/python3.8/site-packages/sqlalchemy/sql/compiler.py:1799(_label_select_column)
  631/463    0.001    0.000    0.004    0.000 /home/a/anyway/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py:880(__get__)
        3    0.001    0.000    0.001    0.000 {method 'rollback' of 'psycopg2.extensions.connection' objects}
      177    0.001    0.000    0.002    0.000 /home/a/anyway/venv/lib/python3.8/site-packages/sqlalchemy/sql/compiler.py:864(visit_column)
   400/89    0.001    0.000    0.001    0.000 /home/a/anyway/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py:301(get_cls_kwargs)
      168    0.001    0.000    0.003    0.000 /home/a/anyway/venv/lib/python3.8/site-packages/sqlalchemy/orm/interfaces.py:518(_get_context_loader)
     3016    0.001    0.000    0.002    0.000 /home/a/anyway/anyway/localization.py:200(get_field)


--------------------------------------------------------------------------------`

**Comment by atalyaalon** [comment]
@ziv17 FYI

**Comment by BarVolunteering** [comment]
@atalyaalon How about this idea: 
break the markers function to 2 functions - one will return a list of markers with little info about every marker and a second that will return extended info on a specific marker? Will it be good for our users use-cases?

 except for that I am out of ideas on how to further improve this function.

**Comment by atalyaalon** [comment]
@BarVolunteering great work!
I think we should leave this for now, since I don't think it's a priority.
What do you think?

**Comment by BarVolunteering** [comment]
Agreed
