### ISSUE TITLE
Create a guided tour for ANYWAY

### ISSUE THREAD

**Issue by galraij** [hasadna/anyway#146]
Mockups and explanation can be found here:
https://docs.google.com/document/d/1qmrA_8cS16Wpy8Hfp0iDXkYYjm2geAnXehWPwWLMq04/edit?usp=sharing

Create a guided tour for anyway, a good example can be found in: http://www.obudget.org/#main//2014/main

More Sources for Inspiration:
http://www.webresourcesdepot.com/11-awesome-jquery-site-tour-plugins-for-guiding-users-with-style/

![step 1](https://cloud.githubusercontent.com/assets/3368312/6314259/7e558a08-b9e0-11e4-8a10-0d6490c128bc.jpg)

**Comment by danielhers** [comment]
Need to complete the tutorial based on the mockups.
Also, better translate the buttons.

**Comment by agamaloni** [comment]
Working on it :)

**Comment by danielhers** [comment]
@galraij is the tour ready, or are there more steps that should be in it?

**Comment by galraij** [comment]
Ideally we need more steps, let's wait until the new filters are ready and decide then. However, the first step location should be adjusted as the button for "Start Guidance" moved.

@agamaloni
