### ISSUE TITLE
Add injured_accidents_with_pedestrians to infographics API

### ISSUE THREAD

**Issue by atalyaalon** [hasadna/anyway#1466]
סוג גרף: stacked bar chart

מתי להציג:
כאשר התרחשה תאונה עם הולך רגל ברחוב שנמצא במפתח הרחובות של הלמ״ס.

מתודולוגיה:
כמות נפגעים בתאונות עם הולכי רגל לפי X שנים ברחוב X מוצג בגרף עמודות כאשר כל עמודה מחולקת למספר הנפגעים לפי חומרת הנפגע.

This will be done in 2 stages:
1. Add a widget with mock data ([see this pr as an example](https://github.com/hasadna/anyway/pull/1419/files))
       {
           "name": "injured_accidents_with_pedestrians",
           "data": {
               "items": [
                   {
                       "year": 2009,
                       "light_injury_severity_text": "פצוע קל",
                       "light_injury_severity_count": 10,
                       "severe_injury_severity_text": "פצוע קשה",
                       "severe_injury_severity_count": 3,
                   },
                   {
                       "year": 2009,
                       "light_injury_severity_text": "פצוע קל",
                       "light_injury_severity_count": 20,
                       "severe_injury_severity_text": "פצוע קשה",
                       "severe_injury_severity_count": 10,
                       "killed_injury_severity_text": "הרוג",
                       "killed_injury_severity_count": 2,
                   },
                          ],
               "text": {
                   "title": "נפגעים בתאונות עם הולכי רגל ברחוב ז׳בוטינסקי, פתח תקווה (2009-2015)"
               }
           },
           "meta": {
               "rank": 18
           }
       }

2. Create the real data of the newsflash's street.

The query used to create the above data:
select 
    accident_year, 
    injury_severity,
    injury_severity_hebrew, 
    accident_yishuv_name, 
    count(concat(provider_and_id, '_', involve_id))
from involved_markers_hebrew
where 
    provider_and_id in 
    (select distinct(provider_and_id )
    from involved_markers_hebrew 
    where accident_yishuv_name like '%פתח תקווה%' and (street1_hebrew like  '%בוטינסקי%' or street2_hebrew like  '%בוטינסקי%') and injured_type = 1 )
    and 
    (injury_severity <= 3 and injury_severity >= 1)
    and accident_year >= 2009 and accident_year <= 2015
group by accident_year, injury_severity, injury_severity_hebrew, accident_yishuv_name
order by injury_severity, accident_year

The graph that will be presented in FE:
![Screen Shot 2020-09-26 at 14 13 28](https://user-images.githubusercontent.com/20992625/94339413-84084080-0002-11eb-8e8f-262cdb6859a3.png)

**Comment by atalyaalon** [comment]
@BarVolunteering can you take this one?

**Comment by BarVolunteering** [comment]
@atalyaalon 
Maybe in 2-3 more weeks, currently i need to finish my existing issues.

**Comment by atalyaalon** [comment]
Closing this one since #1680 created. @DorAdam great work!
