### ISSUE TITLE
Add users table and API functions with restrictions (Read + Write)

### ISSUE THREAD

**Issue by atalyaalon** [hasadna/anyway#1469]
1. Table Fields:
oauth_id
organization
first_name
last_name
email

2. Check GDPR restrictions regarding keeping the data above

@yuvalbl any comments?

**Comment by BarVolunteering** [comment]
@atalyaalon About the API, how about:

1. Oauth2 API (login & callback)
2. Logout
3. Registration? - for the extra fields (organization, first_name, last_name and email)
4. Anything else?

**Comment by BarVolunteering** [comment]
As I talked with FE the interaction with the sensitive API will be done with JWT and will be restricted by IP

**Comment by BarVolunteering** [comment]
The API needed is:
Logout
Registration - for the extra fields (organization, first_name, last_name and email) - this will be the add user
Delete user
Update - for fields organization, first_name, last_name and email

**Comment by BarVolunteering** [comment]
The current status is that there is limited login support that was merged in pull request #1598 ,
the login system is still WIP.

**Comment by atalyaalon** [comment]
@BarVolunteering can we close this issue?

**Comment by BarVolunteering** [comment]
Yes.
Not all of the code is implemented but there are other issues that better describes what need to be done.
