### ISSUE TITLE
EURO DEMO: Query for motorcycle accidents in road 20 vs all roads

### ISSUE THREAD

**Issue by baruchpicard** [hasadna/anyway#1494]
JSON:
{
"name": "motorcycle accidents from all hard accidents. road 20",
"data": {
"items":
[
  {
    "location": "כביש 20",
    "vehicle": "אופנוע",
    "percentage": 0.5
  },
  {
    "location": "כביש 20",
    "vehicle": "אחר",
    "percentage": 0.5
  },
  {
    "location": "כל הארץ",
    "vehicle": "אחר",
    "percentage": 0.802680566
  },
  {
    "location": "כל הארץ",
    "vehicle": "אופנוע",
    "percentage": 0.197319434
  }
],
"text": {
"title": "אחוז תאונות האופנוע מכלל התאונות הקשות  - כביש 20 בהשוואה לכל הארץ"
}
},
"meta": {
"rank": 18
}
}

SQL CODE:
`
SELECT LOCATION,
       vehicle,
       num_of_accidents/sum(num_of_accidents) over(PARTITION BY LOCATION):: decimal AS percentage
FROM
  (SELECT CASE
              WHEN road_segment_name LIKE '%חיל השריון%'THEN 'כביש 20'
              ELSE 'כל הארץ'
          END AS LOCATION,
          CASE -- grouping of vehicles
              WHEN involve_vehicle_type IN (8,
                                            10,
                                            19,
                                            9) THEN 'אופנוע'
              ELSE 'אחר'
          END AS vehicle,
          COUNT(DISTINCT provider_and_id) num_of_accidents
   FROM involved_markers_hebrew
   WHERE road_type >2 -- only inter-city
AND accident_severity < 3
   GROUP BY 1,
            2
   ORDER BY 3 DESC) a`

VISUALISATION:
![image](https://user-images.githubusercontent.com/60894106/95188053-9c334900-07d4-11eb-8222-fdde32420d28.png)

**Comment by atalyaalon** [comment]
@baruchpicard amazing work! Adding the json in this pr: https://github.com/hasadna/anyway/pull/1495

**Comment by atalyaalon** [comment]
@BarVolunteering I added a PR for mock data, now we're left with implementing it so we'll get real data in the API.

**Comment by BarVolunteering** [comment]
@atalyaalon I won't be able to finish this issue by the end of this month

**Comment by BarVolunteering** [comment]
@ziv17

**Comment by atalyaalon** [comment]
@baruchpicard is there a new query for this one?

**Comment by MichalOren** [comment]
מציעה אופציה לכותרת אחרת ותצוגה דומה
![Moto3](https://user-images.githubusercontent.com/61007501/96727023-44dbce00-13bb-11eb-8ee0-d2bb15971908.PNG)

**Comment by atalyaalon** [comment]
@MichalOren Thanks! looks good!
I suggest writing in the header: "תאונות אופנועים קשות וקטלניות בכביש 20 בהשוואה לכל הארץ"
או שאולי עדיף ״לעומת כל הארץ״?
What do you think?

**Comment by MichalOren** [comment]
@atalyaalon 
1. I totaly agree it best to drop any reference to "%" or "Distribution" in the title.
2. בעברית: 'בהשוואה' מתכוון שחלק במשפט מתאר דמיון במשמעות לחלק האחר 
 .כאשר 'לעומת' מתכוון שחלק במשפט מתאר ניגוד במשמעות לחלק ההאחר
לכן נראה לי לעומת יותר מתאים
3. מדובר בתאונות ולא ברוכבי אופנוע אז בטוח לשנות

**Comment by atalyaalon** [comment]
@MichalOren Thank you!

2. Not sure about it - but maybe @elazarg will have an opinion on this.

If so agreed title is either 
תאונות אופנועים קשות וקטלניות בכביש 20 בהשוואה לכל הארץ 
OR 
תאונות אופנועים קשות וקטלניות בכביש 20 לעומת לכל הארץ
?

**Comment by elazarg** [comment]
לדעתי כאן עדיף "בהשוואה", שאיננו רומז על דמיון ואיננו רומז על שוני. 

But something about it is still clunky.

**Comment by atalyaalon** [comment]
Thanks Elazar! @MichalOren we can start with this 
and change if we'll have a better title.

@baruchpicard and @MichalOren wonderful work!
I created [this issue ](https://github.com/hasadna/anyway/issues/1579) in our new format - so I suggest closing this one.
@MichalOren can you add an image to the new issue above?
