### ISSUE TITLE
Localize infographics API

### ISSUE THREAD

**Issue by atalyaalon** [hasadna/anyway#1519]
API call: /api/infographics-data
This requires:
1. Localizing each widget
2. Add language parameter in API
3. I think there is no need we'll save per newsflash data for all languages in cache. That means that after extracting data from cache, we'll use a relevant dictionary to send the data in the wanted language. @ziv17 FYI

**Comment by elazarg** [comment]
Seems like the last time anyone touched `babel` in this repo was 3 years ago. 
For those who are not familiar (such as myself), I think this blog post is exceptionally useful:
https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-xiii-i18n-and-l10n

**Comment by atalyaalon** [comment]
@ziv17 performed an amazing work here. Closing this one.
