### ISSUE TITLE
anyway.co.il is not working without WWW

### ISSUE THREAD

**Issue by galraij** [hasadna/anyway#153]

**Comment by samuelregev** [comment]
did you see that:
https://devcenter.heroku.com/articles/custom-domains#root-domain

**Comment by danielhers** [comment]
anyway.co.il is in our domain name list.

**Comment by samuelregev** [comment]
What about your dns server? Does it support CNAME functionality at the apex?
Is it configured?

**Comment by danielhers** [comment]
I suppose it isn't.
Also found this: http://stackoverflow.com/a/16041655/223267

**Comment by samuelregev** [comment]
> nslookup anyway.co.il
Server:  UnKnown
Address:  10.0.0.138

*** No internal type for both IPv4 and IPv6 Addresses (A+AAAA) records available
 for anyway.co.il

Are you using amazon dns server(route53)?

https://devcenter.heroku.com/articles/route-53

**Comment by danielhers** [comment]
I don't know. @galraij who do we ask about DNS?

**Comment by galraij** [comment]
מאיר קריחלי
mkriheli@gmail.com

**Comment by galraij** [comment]
@MeirKriheli

**Comment by samuelregev** [comment]
http://whois.co.il/index.php?domain=anyway.co.il

name servers is AWS

**Comment by uda** [comment]
You can point it to some server just to return a 301 to www.anyway.co.il

**Comment by danielhers** [comment]
@daonb added oway.org.il

**Comment by danielhers** [comment]
@galraij what's the decision? Do we stay with `www.anyway.co.il` and `oway.org.il`, or do we want to support `anyway.co.il` too?

**Comment by galraij** [comment]
Ideally all of those should work:

www.anyway.co.il
anyway.co.il
www.oway.org.il
oway.org.il

**Comment by danielhers** [comment]
So we still need someone who knows how to deal with domains to get anyway.co.il to redirect to www.anyway.co.il.

**Comment by galraij** [comment]
I think it will be good to consider www.anyway.co.il as our main address and make sure it works without the 'www' and redirect oway.org.il and www.oway.org.il to www.anyway.co.il

**Comment by danielhers** [comment]
Fair enough, now we just need anyway.co.il and www.oway.org.il, and to do
the redirect :)

**Comment by OmerSchechter** [comment]
Have we tried modifying the .htaccess file?
