### ISSUE TITLE
EURO DEMO highway motorcycle accidents per km, severe+fatal

### ISSUE THREAD

**Issue by yuvalbar23** [hasadna/anyway#1556]
JSON:
{
"name": "motorcycle_accidents_distribution_severe_fatal",
"data": {
"items":
[
    {
        "road1": 20,
        "road_segment_name": "מחלף חולון - מחלף חיל השריון",
        "count": 24,
        "count_per_km": 20.0
    },
    {
        "road1": 20,
        "road_segment_name": "מחלף רוקח - מחלף קק\"ל",
        "count": 23,
        "count_per_km": 10.9523809524
    },
    {
        "road1": 20,
        "road_segment_name": "מחלף וולפסון - מחלף חולון",
        "count": 19,
        "count_per_km": 9.5
    },
    {
        "road1": 20,
        "road_segment_name": "מחלף קיבוץ גלויות - מחלף לה-גרדיה",
        "count": 19,
        "count_per_km": 15.8333333333
    },
    {
        "road1": 20,
        "road_segment_name": "מחלף לה-גרדיה - מחלף השלום",
        "count": 19,
        "count_per_km": 11.1764705882
    },
    {
        "road1": 20,
        "road_segment_name": "מחלף גלילות - כניסה לגעש",
        "count": 18,
        "count_per_km": 1.7821782178
    },
    {
        "road1": 20,
        "road_segment_name": "מחלף הרכבת - מחלף ההלכה",
        "count": 18,
        "count_per_km": 15.0
    },
    {
        "road1": 20,
        "road_segment_name": "מחלף קוממיות - מחלף יוספטל",
        "count": 18,
        "count_per_km": 12.0
    },
    {
        "road1": 20,
        "road_segment_name": "מחלף יוספטל - מחלף דב הוז",
        "count": 14,
        "count_per_km": 14.0
    },
    {
        "road1": 20,
        "road_segment_name": "מחלף קק\"ל - מחלף גלילות",
        "count": 14,
        "count_per_km": 5.8333333333
    },
    {
        "road1": 20,
        "road_segment_name": "מחלף ההלכה - מחלף רוקח",
        "count": 13,
        "count_per_km": 10.0
    },
    {
        "road1": 20,
        "road_segment_name": "מחלף דב הוז - מחלף וולפסון",
        "count": 9,
        "count_per_km": 6.4285714286
    },
    {
        "road1": 20,
        "road_segment_name": "מחלף חולות - מחלף משה דיין",
        "count": 7,
        "count_per_km": 1.5909090909
    },
    {
        "road1": 20,
        "road_segment_name": "מחלף משה דיין - מחלף קוממיות",
        "count": 5,
        "count_per_km": 3.125
    },
    {
        "road1": 20,
        "road_segment_name": "מחלף השלום - מחלף הרכבת",
        "count": 5,
        "count_per_km": 5.5555555556
    }
]
}
}
![image](https://user-images.githubusercontent.com/63560246/96688847-4b058680-138a-11eb-89b0-8e11eae302d9.png)

**Comment by atalyaalon** [comment]
@yuvalbar23 Wonderful, thanks!
I created the [following issue](https://github.com/hasadna/anyway/issues/1581) - We'll start with general count of accidents - won't focus on motorcycles in this Widget yet.
