### ISSUE TITLE
EURO DEMO highway motorcycle accidents per km, all accidents

### ISSUE THREAD

**Issue by yuvalbar23** [hasadna/anyway#1557]
JSON:
{
"name": "motorcycle_accidents_distribution_all_accidents",
"data": {
"items":
[
    {
        "road1": 20,
        "road_segment_name": "מחלף לה-גרדיה - מחלף השלום",
        "count": 341,
        "count_per_km": 200.5882352941
    },
    {
        "road1": 20,
        "road_segment_name": "מחלף חולון - מחלף חיל השריון",
        "count": 204,
        "count_per_km": 170.0
    },
    {
        "road1": 20,
        "road_segment_name": "מחלף הרכבת - מחלף ההלכה",
        "count": 170,
        "count_per_km": 141.6666666667
    },
    {
        "road1": 20,
        "road_segment_name": "מחלף רוקח - מחלף קק\"ל",
        "count": 169,
        "count_per_km": 80.4761904762
    },
    {
        "road1": 20,
        "road_segment_name": "מחלף וולפסון - מחלף חולון",
        "count": 157,
        "count_per_km": 78.5
    },
    {
        "road1": 20,
        "road_segment_name": "מחלף קיבוץ גלויות - מחלף לה-גרדיה",
        "count": 155,
        "count_per_km": 129.1666666667
    },
    {
        "road1": 20,
        "road_segment_name": "מחלף קוממיות - מחלף יוספטל",
        "count": 144,
        "count_per_km": 96.0
    },
    {
        "road1": 20,
        "road_segment_name": "מחלף גלילות - כניסה לגעש",
        "count": 133,
        "count_per_km": 13.1683168317
    },
    {
        "road1": 20,
        "road_segment_name": "מחלף דב הוז - מחלף וולפסון",
        "count": 127,
        "count_per_km": 90.7142857143
    },
    {
        "road1": 20,
        "road_segment_name": "מחלף ההלכה - מחלף רוקח",
        "count": 124,
        "count_per_km": 95.3846153846
    },
    {
        "road1": 20,
        "road_segment_name": "מחלף חולות - מחלף משה דיין",
        "count": 121,
        "count_per_km": 27.5
    },
    {
        "road1": 20,
        "road_segment_name": "מחלף יוספטל - מחלף דב הוז",
        "count": 95,
        "count_per_km": 95.0
    },
    {
        "road1": 20,
        "road_segment_name": "מחלף קק\"ל - מחלף גלילות",
        "count": 64,
        "count_per_km": 26.6666666667
    },
    {
        "road1": 20,
        "road_segment_name": "מחלף השלום - מחלף הרכבת",
        "count": 54,
        "count_per_km": 60.0
    },
    {
        "road1": 20,
        "road_segment_name": "מחלף משה דיין - מחלף קוממיות",
        "count": 32,
        "count_per_km": 20.0
    }
]
}
}
![image](https://user-images.githubusercontent.com/63560246/96689012-830cc980-138a-11eb-9ed4-5280e203c522.png)

**Comment by atalyaalon** [comment]
Thank you @yuvalbar23 !
Widget exists, closing this one
