### ISSUE TITLE
Widget: motorcycle_accidents_vs_all_accidents

### ISSUE THREAD

**Issue by atalyaalon** [hasadna/anyway#1579]
**Name**
Query for severe and fatal motorcycle accidents VS other accidents in a specific road vs all of the interurban roads 

**Title**
תאונות אופנועים קשות וקטלניות בכביש __ בהשוואה לכל הארץ
(שם הכותרת משתנה כתלות במספר כביש)

**Visualization**
@MichalOren please attach :) 

**Visualization explanation**
Visualization contains 2 bar graphs (for the specific road and for all of Israel interurban roads)
Each bar is a stacked bar completing to 100% containing the the percentage of severe and fatal accidents with motorcycles and the rest - all other severe and fatal accidents.

**Use case**
When the percentage of motorcycle accidents in the specific road is greater than 1.5 times the percentage of the motorcycle accidents in all of the roads (for example, if all interurban roads have a 20% of motorcycle severe and fatal accidents, infographics will be presented if the specific road has at least 30% of motorcycle accidents)

**SQL query**
See [query here](https://app.redash.io/hasadna/queries/511391/source)
Road number changes - according to the newsflash road1 field. Also title changes accordingly.

**Additional context**
- Definition will be used by BE team to generate a Json response to FE
- Mock Json already exists in code (look for motorcycle_accidents_vs_all_accidents in [infographics_utils.py](https://github.com/hasadna/anyway/blob/dev/anyway/infographics_utils.py))
- Definition will be provided by Data team, after internal review
- Definition will be written in English and should use language agnostic definitions and data structures 
(e.g. SQL columns) as much as possible.

**Comment by MichalOren** [comment]
![Moto4](https://user-images.githubusercontent.com/61007501/99146929-39f81e80-2685-11eb-9839-e85aed4cdd24.PNG)

**Comment by MichalOren** [comment]
@atalyaalon 
Usually the analysis have specific time frame. I wonder if we should include constatnt 'time reference' in infographic slides and jsons ? 
as part of standartization...
i cant find reference to the time frame of the analysis it in the website slides

**Comment by atalyaalon** [comment]
@MichalOren you are absolutely right - we'll already asked from the FE to add the dates in the bottom of each infographics.

**Comment by atalyaalon** [comment]
@MichalOren the infographics looks really good! I'll add it to the issue

**Comment by atalyaalon** [comment]
@MichalOren infographics looks really good. Thank you!

**Comment by atalyaalon** [comment]
Thank you @rsperer and @MichalOren !
Issue was opened to [FE team](https://github.com/hasadna/anyway-newsflash-infographics/issues/541)
