### ISSUE TITLE
Localize Widget - head_on_collisions_comparison

### ISSUE THREAD

**Issue by atalyaalon** [hasadna/anyway#1592]
**Widget ID**
head_on_collisions_comparison

**Widget Fields**
desc
**Dictionaries Missing**
specific dictionary to the description of this widget
Note: Create a dictionary containing using the DB code as a key and not the Hebrew translation (for example `{1: 'fatal'}` rather than `{'קטלנית': 'fatal'}`)

**Widget Title**
Yes, current title in hebrew: תאונות קטלניות ע״פ סוג

**Additional context**
- Existing translation to CBS fields - [see here](https://docs.google.com/spreadsheets/d/1gjeMsPEWayMZ4Z0tGDKkL0mDsXgIRQ4-aAadRpEP9Oc/edit?usp=sharing)
- Existing CBS Fields - [see here](https://docs.google.com/spreadsheets/d/1qaVV7NKXVYNmnxKZ4he2MKZDAjWPHiHfq-U5dcNZM5k/edit?usp=sharing)
(Note - if translation in file is not adequate - please create a better translation)

**Flask Babel**
For updating messages.pot with all strings for translation - use the following command: `pybabel extract -F babel.cfg -o messages.pot .`
For updating existing po files with new strings: `pybabel update -i messages.pot -d translations`

**Comment by ziv17** [comment]
Hi @atalyaalon ,
currently, the returned items are:
`
"specific_road_segment_fatal_accidents": [
                        {
                            "desc": "חזיתיות",
                            "count": 1
                        },
                        {
                            "desc": "אחרות",
                            "count": 1
                        }
                    ],
                    "all_roads_fatal_accidents": [
                        {
                            "desc": "חזיתיות",
                            "count": 178
                        },
                        {
                            "desc": "אחרות",
                            "count": 541
                        }
                    ]
                }
`
Should `"specific_road_segment_fatal_accidents"`, `"all_roads_fatal_accidents"`, be translated?
Should `"desc"`, `"count"` be translated?

**Comment by atalyaalon** [comment]
@ziv17 desc's value should be translated - not the key

Regarding specific_road_segment_fatal_accidents and all_roads_fatal_accidents - ideally we'll structure this with translation, right now it's already translated in FE (see this widget here - Hebrew: https://anyway-infographics.web.app/newsflash/62242 and here - english https://anyway-infographics.web.app/en/newsflash/62242)
(And see open issue here: https://github.com/hasadna/anyway-newsflash-infographics/issues/497)

But we do need to make sure all translations comes from BackEnd - so I think it's better to add it.

**Comment by ziv17** [comment]
Implemented
