### ISSUE TITLE
Localize Widget - accident_count_by_driver_type

### ISSUE THREAD

**Issue by atalyaalon** [hasadna/anyway#1594]
**Widget ID**
accident_count_by_driver_type

**Widget Fields**
driver_type
**Dictionaries Missing**
Dictionaries to create: Driver type
Note: Create a dictionary containing using the DB code as a key and not the Hebrew translation (for example `{1: 'fatal'}` rather than `{'קטלנית': 'fatal'}`)

**Widget Title**
current title to localize: מעורבות נהגים בתאונות לפי סוג במקטע _

**Additional context**
- Existing translation to CBS fields - [see here](https://docs.google.com/spreadsheets/d/1gjeMsPEWayMZ4Z0tGDKkL0mDsXgIRQ4-aAadRpEP9Oc/edit?usp=sharing)
- Existing CBS Fields - [see here](https://docs.google.com/spreadsheets/d/1qaVV7NKXVYNmnxKZ4he2MKZDAjWPHiHfq-U5dcNZM5k/edit?usp=sharing)
(Note - if translation in file is not adequate - please create a better translation)

**Flask Babel**
For updating messages.pot with all strings for translation - use the following command: `pybabel extract -F babel.cfg -o messages.pot .`
For updating existing po files with new strings: `pybabel update -i messages.pot -d translations`

**Comment by ziv17** [comment]
Implemented
