### ISSUE TITLE
Add urban accidents (street resolution)

### ISSUE THREAD

**Issue by atalyaalon** [hasadna/anyway#1642]
These accidents are filtered both when creating infographics cache and when querying the newsflash API.
Make sure these accidents aren't filtered in both locations

**Comment by ziv17** [comment]
Hi @atalyaalon , by newsflash API, you mean `news_flash()` in `anyway/views/news_flash/api.py`?

**Comment by ziv17** [comment]
Hi @atalyaalon Does this mean to accept all news-flash items that has `accident == true`?

**Comment by ziv17** [comment]
Implemented by PR #1752
