### ISSUE TITLE
Modify injured_count_per_age_group API

### ISSUE THREAD

**Issue by atalyaalon** [hasadna/anyway#1645]
1. Modify age ranges to fit the following image:
![101387514-355f0880-38c7-11eb-98f2-890614e47fe1](https://user-images.githubusercontent.com/20992625/102692610-180e3080-421d-11eb-8f0b-3aab424884ff.jpg)
2. Split to by injury severity - modify API to contain injured data per age group per severity
3. Add the title: "מספר הרוגים ופצועים קשה במקטע ___"
4. @galraij  - Please Add mock image that contains.
5. Once image and Backend API are ready - open issue it Front End team

**Comment by BarVolunteering** [comment]
FE issue:
https://github.com/hasadna/anyway-newsflash-infographics/issues/564
