### ISSUE TITLE
Download accidents as CSV file doesn't corresponding with accidents showing on the map

### ISSUE THREAD

**Issue by samuelregev** [hasadna/anyway#165]
changing the arguments (show_fatal, show_severe, show_light, show_inaccurate) in the url don't have any effect on the result csv(or json)

**Comment by danielhers** [comment]
Should be easy to fix - good task for a new team member.

**Comment by samuelregev** [comment]
Tnx, but i'm not a python developer(for now).
I'm building android app for Anyway and i was trying to use this to get accidents details to my app.
https://github.com/samuelregev/anywayAndroidApp/

**Comment by danielhers** [comment]
Well, then you don't depend on the front-end. Just use the /markers route
on the server, for example:

http://www.anyway.co.il//markers?ne_lat=31.772323244855926&ne_lng=35.22266857810973&sw_lat=31.764314581839038&sw_lng=35.20475142189025&zoom=17&start_date=1356991200&end_date=1388527200&show_fatal=1&show_severe=1&show_light=1&show_inaccurate=0

This will get you the data in json format. Just add &format=csv to get it
in CSV format:
http://www.anyway.co.il//markers?ne_lat=31.772323244855926&ne_lng=35.22266857810973&sw_lat=31.764314581839038&sw_lng=35.20475142189025&zoom=17&start_date=1356991200&end_date=1388527200&show_fatal=1&show_severe=1&show_light=1&show_inaccurate=0&format=csv

Good luck

**Comment by samuelregev** [comment]
i figured it out already, the bug is - if i change URL arguments(show_fatal, show_severe, show_light, show_inaccurate) i seems to get the same details every time

even if i change all of the, to 0, like this(which should give me empty list):
http://www.anyway.co.il//markers?ne_lat=31.772323244855926&ne_lng=35.22266857810973&sw_lat=31.764314581839038&sw_lng=35.20475142189025&zoom=17&start_date=1356991200&end_date=1388527200&show_fatal=0&show_severe=0&show_light=0&show_inaccurate=0

**Comment by danielhers** [comment]
Interesting. Looks like a bug in Marker.bounding_box_fetch. We'll take a
look.
