### ISSUE TITLE
Logging in with Facebook disables reset-map-control button

### ISSUE THREAD

**Issue by danielhers** [hasadna/anyway#167]
Click the "Login with Facebook" button and log in.
Then try clicking the reset-map-control ("my location") button at the top right corner of the map. It should go to your current location but it doesn't do anything.

**Comment by danielhers** [comment]
@OmerSchechter want to take a look?

**Comment by OmerSchechter** [comment]
Sure, i'll look into it.

**Comment by OmerSchechter** [comment]
@danielhers  Are you familiar with this problem?
I get this alert after clicking on "Login with Facebook".

![screen shot 2015-03-24 at 7 48 39 pm](https://cloud.githubusercontent.com/assets/11275466/6808782/be7d5ce6-d25e-11e4-9410-279952ad9128.png)

**Comment by samuelregev** [comment]
I think this issue not relevant any more now that login with Facebook no longer required. Daniel?

**Comment by danielhers** [comment]
Right
