### ISSUE TITLE
Widget: Total pedestrians injuries on a specific street by injury severity and year

### ISSUE THREAD

**Issue by DorAdam** [hasadna/anyway#1680]
**Name**

Query for pedestrians injuries count at a specific street and by injury severity and year
Currently mock data exists - Widget name: injured_accidents_with_pedestrians

**Title**

pedestrians injuries at __street __ , __city ___ (years)
נפגעים בתאונות עם הולכי רגל ברחוב ____ , בעיר___ (טווח השנים)

**Visualization**

![image](https://user-images.githubusercontent.com/74875001/104808667-6dc00380-57f0-11eb-9c6f-08fdb76fc760.png)

**Visualization explanation**

stacked bar chart

**Use case**
When this infographic should be displayed

**SQL query**
[query on redash
](https://app.redash.io/hasadna/queries/599117/source?p_street%20name=%27%D7%96_%D7%91%D7%95%D7%98%D7%99%D7%A0%D7%A1%D7%A7%D7%99%27&p_street%20symbol=905&p_yishuv%20name=%27%D7%A4%D7%AA%D7%97%20%D7%AA%D7%A7%D7%95%D7%95%D7%94%27&p_yishuv%20symbol=7900)

Modified parameters:
street1_hebrew
street2_hebrew
accident_yishuv_name

**Additional context**

**Comment by atalyaalon** [comment]
@DorAdam looks great!
@MichalOren can you review the query before we send this to implementation in the BackEnd? Any comments?

**Comment by MichalOren** [comment]
Hi, 
1.Is this infographic is ment to be **general** to pedestrian severity of injury at any street and city.... or we would like to show ציר המוות and infloence of road separatior?

There is mismatch between the infographic and query results.
In the infographic years are limited to 2009-2015 the query generate results for 2008-2020

**Comment by shaysw** [comment]
1. in the sample redash query:

where accident_yishuv_name  like {{yishuv name}}  and injured_type = 1 and (street1_hebrew like {{street name}} or street2_hebrew like {{street name}}) parameter representing a street name: "street name". 

However, in the specification of "Modified parameters" there exist 2 parameters: street1_hebrew and street2_hebrew. Which is it?
2. invoking the API request: I've found the following API request to actually invoke InjuredAccidentsWithPedestriansWidget: http://localhost:8080/api/infographics-data?news_flash_id=1&street1_hebrew=%22a%22&street2_hebrew=%22a%22&accident_yishuv_name=%22a%22&road_segment_name=%22a%22, but it seems more of a hack and resulted in various failures along the way. The question is, how is this API request supposed to be invoked in production?
