### ISSUE TITLE
Create information data per widget

### ISSUE THREAD

**Issue by atalyaalon** [hasadna/anyway#1686]
Start with the table widget, the map widget and the summary widget

**Comment by ChayneAzriel** [comment]
Hi, can you please put here the links, so we know were to look

**Comment by atalyaalon** [comment]
@ChayneAzriel top priority widgets:
1. accident_count_by_severity
2. most_severe_accidents_table
3. most_severe_accidents
4. head_on_collisions_comparison

[API/graphs description is here](https://docs.google.com/document/d/1Hv5ItvwM3z9nn95LjlsYHL-o18V8PgWrrQOKIPiPymU/edit?usp=sharing)

You can find these widgets code in our github.

Let me know if you have any questions

**Comment by ChayneAzriel** [comment]
created information tags for first review:

1. **accident_count_by_severity**

information = 'Number of road accidents on road section {location_info} between {st_year} - {en_yaer} summed by accident severity -light, severe and fatal'.format(st_year = (start_year), en_year = (end_year), location_info = (location_info))

heb_information = 'לפי חומרת התאונה - קלה, קשה וקטלנית {en_year} - {st_year} בין השנים {location_info} סכום תאונות הדרכים במקטע'.format(st_year = (start_year), en_year = (end_year), location_info = (location_info))

2. **most_severe_accidents_table**

information = 'Ten most serious road accidents in road section {location_info} between {st_year} - {en_yaer} arranged by accident severity. listed date and hour of the accident, accident type, number of killed and seriously injured for each accident'.format(st_year = (start_year), en_year = (end_year), location_info = (location_info))

heb_information = ' מסודר על פי חומרת התאונה. מפורט תאריך, שעת התאונה, סוג התאונה וכמות ההרוגים והפצועים קשה של כל תאונה. {en_year} - {st_year} בין השנים {location_info} עשרת תאונות הדרכים החמורות ביותר במקטע'.format(st_year = (start_year), en_year = (end_year), location_info = (location_info))

3. **most_severe_accidents**

information = 'Ten most serious road accidents in road section {location_info} are located on the map according to a landmark, between {st_year} - {en_yaer}. listed date, accident severity and accident type'.format(st_year = (start_year), en_year = (end_year), location_info = (location_info))

heb_information = ' מפורט תאריך, חומרת התאונה וסוג התאונה {en_year} - {st_year} ממוקמות על המפה על פי נ"צ. בין השנים {location_info} עשרת תאונות הדרכים החמורות ביותר במקטע '.format(st_year = (start_year), en_year = (end_year), location_info = (location_info))

4. **head_on_collisions_comparison**

information = 'Percentage of frontal collision accidents in road section {location_info} compared to the percentage of frontal collision accidents in the rest of the country (same road type urban \ interurban respectively), between {st_year} - {en_yaer}.'.format(st_year = (start_year), en_year = (end_year), location_info = (location_info))

heb_information = ' {en_year} - {st_year} בהשוואה לאחוז תאונות הדרכים מסוג התנגשות חזיתית בשאר כבישי הארץ (מאותו סוג, עירוני \ בינעירוני בהתאמה). בין השנים {location_info} אחוז תאונות הדרכים מסוג התנגשות חזיתית במקטע'.format(st_year = (start_year), en_year = (end_year), location_info = (location_info))

**Comment by atalyaalon** [comment]
Thanks @ChayneAzriel! Added a pr - containing these 4 widgets.
We're missing information and translations for additional widgets that are not in production yet - I will make sure to add them
