### ISSUE TITLE
Add an option to show only the discussions on the current view on the sidebar frame

### ISSUE THREAD

**Issue by danielhers** [hasadna/anyway#169]
![dynamic_list](https://cloud.githubusercontent.com/assets/3368312/6288735/c2ce0952-b923-11e4-8c33-4aee804b16fb.jpg)

**Comment by danielhers** [comment]
Depends on #155

**Comment by omerxx** [comment]
@galraij What is `ענן מילים` ??
(shown in the screen shot above)

**Comment by omerxx** [comment]
![image](https://cloud.githubusercontent.com/assets/12237955/8170419/1e919f5c-13b9-11e5-8099-c7ea6a341806.png)

**Comment by omerxx** [comment]
Another question: The description wants to filter the sidebar alone, but the example picture describes filtering the markers on map as well. Which is the correct?

**Comment by galraij** [comment]
Ignore it for now, it's a dream I have for later days. Analyzing the data and comments and present it as word cloud.



‫ב-15 ביוני 2015, בשעה 21:59, ‏‏omerxx ‏<notifications@github.com> כתב/ה:‬
