### ISSUE TITLE
Widget: Killed in accidents on a certain day compared to the same day in previous years

### ISSUE THREAD

**Issue by ChayneAzriel** [hasadna/anyway#1709]
**Name**
Killed in accidents on a certain month compared to the same month in previous years

**Title**
count of killed in road accident on month X over the years

**Visualization**
![killed_sep](https://user-images.githubusercontent.com/61120310/102711815-0b451780-42c5-11eb-8146-bb7b70698ec0.png)

**Visualization explanation**
Percentage change of killed in accidents on month X over the years compered to the current 

**Use case**
general info. on the beginning of each month

**SQL query**
[redash query 1](https://app.redash.io/hasadna/queries/570358?p_Current%20Month=9)

**Additional context**

**Comment by atalyaalon** [comment]
Goal is to show accidents up to latest month on DB of current year (we get the accidents from the CBS on a delay of ~2 months)
Across all years (in infographics query the wanted years are specified)

**Comment by atalyaalon** [comment]
Data structure will be similar to single bar chart structure
@BarVolunteering Is there a documentation of this structure in our repo?

**Comment by BarVolunteering** [comment]
@atalyaalon We don't have documentation for it, I created an issue about it : #2095 

The structure should look like this:
```    
{
   "name":"accident_count_by_accident_year",
   "data":{
      "items":[
         {
            "label_key": 2017,
            "value": 55
         },
         {
            "label_key": 2018,
            "value": 42
         }
      ]
   }
}
```
You can see an example at:
https://dev.anyway.co.il/api/infographics-data?lang=he&news_flash_id=86293&years_ago=5
for widget: killed_and_injured_count_per_age_group

More info in:
https://github.com/hasadna/anyway-newsflash-infographics/issues/779#issuecomment-971718076

**Comment by volsky** [comment]
@BarVolunteering  I have
