### ISSUE TITLE
Address is not changing when clicking on a marker/when changing view

### ISSUE THREAD

**Issue by galraij** [hasadna/anyway#173]
And it worked in the past!

For example- when user changes the view the address should change to: http://www.anyway.co.il/?start_date=2005-01-01&end_date=2023-12-31&show_fatal=1&show_severe=1&show_light=0&show_inaccurate=1&zoom=17&lat=32.01830003055751&lon=34.8217462317383&map_only=true

@moshe742

**Comment by moshe742** [comment]
Hi,
I will try to come to the meeting on Monday to understand what is going on, but on my computer it worked well both on changing zoom/changing position and on clicking on the marker.
Thus, how can I debug it? meaning, if it still works on my computer, how can I check what is different on the server from my computer?

**Comment by danielhers** [comment]
I'm looking at this.
