### ISSUE TITLE
User Permissions Management

### ISSUE THREAD

**Issue by BarVolunteering** [hasadna/anyway#1753]
This is a duplicate of :
https://github.com/hasadna/anyway-newsflash-infographics/issues/517

**Comment by BarVolunteering** [comment]
- [ ] Change folder name from dataclasses
- [ ] Add logout to Docs

**Comment by atalyaalon** [comment]
@BarVolunteering regarding hiding tables from the DB dump - I just want to make sure we're referring the developers dump, but not the full dump that's goal is backup - there we do need all of to tables

**Comment by BarVolunteering** [comment]
@atalyaalon I don't know how our backup is being performed, what i have done is to change the file [`anyway/db_docker/dumpdb.sh`](https://github.com/BarVolunteering/anyway/blob/dev/db_docker/dumpdb.sh).

**Comment by BarVolunteering** [comment]
For reference the first part is done in #1762

**Comment by atalyaalon** [comment]
@BarVolunteering that seems right - you've changed the anyway-partial-db-dumps part.

**Comment by atalyaalon** [comment]
@BarVolunteering do we have a documentation to where Ori needs to change that command? I understand that something is being defined behind the scene, not in this repo?

**Comment by BarVolunteering** [comment]
@atalyaalon We don't have any documentation about that, he is defining something behind the scene last time we changed this file Ori has send me this [commit](https://github.com/hasadna/hasadna-k8s/commit/cc3f4e2bb27a7006d786376796be870b33dd0774).

**Comment by BarVolunteering** [comment]
Closing, the left tasks are in #1789
