### ISSUE TITLE
Remove unused webhooks

### ISSUE THREAD

**Issue by atalyaalon** [hasadna/anyway#1786]
@OriHoch which current webhooks are still relevant for our production and which can we delete?

**Comment by OriHoch** [comment]
which webhooks are you referring to? I'm not aware of any webhooks..

**Comment by atalyaalon** [comment]
@OriHoch check out the webhooks here: https://github.com/hasadna/anyway/settings/hooks
For example, I assume that the slack webhook is related to the github app in our slack.

**Comment by OriHoch** [comment]
I'm not familiar with any of them, none of them are relevant for our CI/CD
