### ISSUE TITLE
Installing environment for new comers

### ISSUE THREAD

**Issue by atalyaalon** [hasadna/anyway#1787]
Make sure instructions are up to date for:

- [x] Installing environment - Windows
- [x] Installing environment - Mac
- [x] Installing environment - Linux
- [x] Add environment variables needed for all processes (news flash scraping, waze data, etc)

**Comment by atalyaalon** [comment]
@OriHoch for start we need to make sure that both installations and tests can run locally - and add environment variables if needed - so that new volunteers can quickly ramp up and join the team - can you take a look at the installation process and the tests?
(Regarding the tests - added issue here - https://github.com/hasadna/anyway/issues/1656_

**Comment by OriHoch** [comment]
The local development environment seems to work fine on Linux and the instructions seem to be up to date for Windows and Mac too

the only issue is the map, I opened another issue to fix that - https://github.com/hasadna/anyway/issues/1819

**Comment by OriHoch** [comment]
to fully test I need access to the dev .env file, I requested access from the Google doc

**Comment by OriHoch** [comment]
regarding env vars - it's possible to add all the production env vars to the dev .env file but I wouldn't recommend it

I think we need to first map all the processes which require to use env vars to determine the best course of action

Some examples:

* twitter scraping - should be split to 2 processes, one process is very simple and only gets the raw data from twitter, another process processes this raw data. That way only the process that gets the raw data needs the twitter API keys, the other process just downloads the raw data it needs (e.g. from anyway S3) and continues the processing. The only process that really needs to be tested is the 2nd one.
* google app login - should provide some way to bypass it for development (e.g. set a special cookie which is only valid for dev and contains the logged-in user name). Developers that really need to test google app login should have a doc which explains how to generate the required api key for themselves.

Suggested next steps:

* @atalyaalon write description of all the required processes (e.g. news flash scraping, waze, etc..) and how each process runs
* @OriHoch write issues for each process detailing the required work to allow easy development of them (including any code changes if needed as described above and documentation)

**Comment by atalyaalon** [comment]
@OriHoch I created an initial documentation and future suggestions for improvements here:
https://github.com/hasadna/anyway/pull/1827
Let me know what you think

**Comment by atalyaalon** [comment]
@OriHoch can we close this one? Are we missing anything?

**Comment by OriHoch** [comment]
@atalyaalon yes, I think it can be closed
