### ISSUE TITLE
User System - Additional Requirements

### ISSUE THREAD

**Issue by atalyaalon** [hasadna/anyway#1789]
Our user system is in good progress, and now we need to specify additional requirements both for FE and BE regarding:

- [x] Admin Interface - BE: API needed, FE: Admin interface to manage users and groups
- [x] Widgets personalization: Use cases needed (widgets designs for specific users / group, unique widgets for a specific user / group, etc) 
- [x] Given the use cases for personalization - which will be made in FE and which in BE? Open relevant issues both in FE and in BE

**Comment by BarVolunteering** [comment]
About the Admin Interface, we need (WIP):
- [ ] Disable User
- [ ] Add group
- [ ] API docs for the FE Team (Partly done, in progress)
- [ ] Other? 

About Widgets personalization:
1. Do we filter the widgets by their rank field?
2. Who is deciding what filter will be done for a user? - is it the admin or the user it self?

**Comment by atalyaalon** [comment]
@BarVolunteering is there something left in this issue?

**Comment by BarVolunteering** [comment]
@atalyaalon All is complete, I am closing it.

**Comment by atalyaalon** [comment]
Thank you @BarVolunteering !
