### ISSUE TITLE
Receive email updates on failures from jenkins

### ISSUE THREAD

**Issue by atalyaalon** [hasadna/anyway#1813]
We don't get email updates on failures - can you please make sure we're receiving emails on failures:
both my personal email and anyway@anyway.co.il

**Comment by atalyaalon** [comment]
@OriHoch can we prioritize this?

**Comment by atalyaalon** [comment]
And also add email updates when airflow fails (same emails)

**Comment by OriHoch** [comment]
I could move all tasks to run via Airflow, shouldn't be hard to do (no code changes or refactoring to the tasks themselves, just trigger them via Airflow), WDYT?

**Comment by atalyaalon** [comment]
Does airflow provide us notifications at the moment?

**Comment by atalyaalon** [comment]
We are currently working on prs for this repo on some of the running processes - if it won't affect this at all and we'll continue developing on anyway at the moment - then it's possible.

**Comment by OriHoch** [comment]
> Does airflow provide us notifications at the moment?

no

**Comment by OriHoch** [comment]
superseded by #1881
