### ISSUE TITLE
local development environment .env file should include the development maps api key

### ISSUE THREAD

**Issue by OriHoch** [hasadna/anyway#1819]
**reproduction steps**

* follow the docs to [setup local docker development environment](https://github.com/hasadna/anyway/blob/dev/docs/DOCKER.md)
* access the local app at http://localhost:8080

**expected**

* show the map

**actual**

* javascript errors, map is not shown

**implementation notes**

* should include the development api key in the secret .env file which is added as part of the development environment seutp
* the [relevant template](https://github.com/hasadna/anyway/blob/eb7132c0c85b8e0724a7d9f3b9261df96336abd5/templates/index.html#L1116) should be modified to use the api key from env var (with default being for production environment)

**Comment by atalyaalon** [comment]
@carmelp16 - this is a small non-urgant task - when you have some time please take this one
