### ISSUE TITLE
Fix walla scraping - see test_scrape_sanity_online_walla

### ISSUE THREAD

**Issue by atalyaalon** [hasadna/anyway#1824]

**Comment by atalyaalon** [comment]
@elazarg , if you can take this one it's great - on you free time of course :)

**Comment by elazarg** [comment]
@atalyaalon can you elaborate? The test passes both on my machine and [on the CI](https://github.com/hasadna/anyway/runs/2921683963).

**Comment by atalyaalon** [comment]
@elazarg you are right, my bad, closing this one

**Comment by atalyaalon** [comment]
@elazarg from some reason this test is failing here: https://github.com/hasadna/anyway/runs/2985420814?check_suite_focus=true#step:6:200

**Comment by elazarg** [comment]
The root cause is that Reuters does not have a link

**Comment by elazarg** [comment]
Interestingly, `רויטרס` can be a very good hint for non-accident.
