### ISSUE TITLE
Add functionality: From GPS to Infographics

### ISSUE THREAD

**Issue by atalyaalon** [hasadna/anyway#1838]
1. Create an API that receives a GPS and return CBS Location (needs to be in reasonable performance for user) [Check out the following function](https://github.com/hasadna/anyway/blob/0fd4f869f48476bfb85097435c82ab097486584c/anyway/parsers/location_extraction.py#L300)
2. Create infographics Cache Tables and Backfill processes that receives CBS Location (Road Segment or street in city) and returns infographics (similar to the current cache)
- We need to plan how tables are built - I suggest an urban cache (using streets), and road segments cache
- Similar to news flash cache - it will contain the years number
3. Create an API that receives a CBS location and years count (similar to the current infographics ) and returns infographics (similar to current infographics API)
4.  Trigger the processes of section 2 - to run whenever new CBS data is loaded to the system

**Comment by atalyaalon** [comment]
@yuvalbl FYI - we'll need to decide on the exact structure of the 2 new APIs:
1. GPS -> Location
2. Location -> Infographics

**Comment by ziv17** [comment]
Hi @atalyaalon, what will be the scenario of a user using it?

**Comment by atalyaalon** [comment]
> Hi @atalyaalon,
> 
> * What will be the scenario of a user using it?
Scenario: Accident we don't have a news flash for / location a user is interested in / Accident with GPS from MADA

> * What currently triggers CBS data loading?
This only the load from email to s3 is triggered. We need to trigger also the load of data from s3 to the DB tables.
When triggered we can recreated the tables (or recreate relevant data in relevant years)

> * Regarding 2: I understand we want to fill the cache only with locations that appear in a news-flash we have.
Not necessarily - since the user will be able to choose any GPS - we want to fill the cache with data of all locations in Israel

**Comment by ziv17** [comment]
Hi @atalyaalon,
> > 
> > * What will be the scenario of a user using it?
> >   Scenario: Accident we don't have a news flash for / location a user is interested in / Accident with GPS from MADA

Will the process be interactive? I.e. user will point on map or accident and then we will be able check with user whether our location is right?
> 
> > * What currently triggers CBS data loading?
> >   This only the load from email to s3 is triggered. We need to trigger also the load of data from s3 to the DB tables.
> >   When triggered we can recreated the tables (or recreate relevant data in relevant years)

Why not doing the two parts immediately one after the other (i.e. combine it to a single process)?

> > * Regarding 2: I understand we want to fill the cache only with locations that appear in a news-flash we have.
> >   Not necessarily - since the user will be able to choose any GPS - we want to fill the cache with data of all locations in Israel

How many such items are there (approx.)?

**Comment by ziv17** [comment]
Hi @atalyaalon , regarding the infographics by CBS location. I understand the input of the API is:

- `years ago: int`
- `lang: str`
- CBS location:
  - `resolution: str`, validity expression: `val in resolution_dict` (`anyway/parsers/__init__.py`)
  - `location_info: dict`, keys are subset of `resolution_dict[resolution]`
  - `gps: dict`, keys: `lat:float`, `lon: float`
  - `location_text: str`. If not exist can be calculated as in `get_news_flash_location_text()`(`anyway/infographics_utils.py`)

I am thinking to split it to tasks:

-  `news_flash_obj`
    - In `anyway/infographics_utils.py::get_head_to_head_stat()`: Replace usage of `request_params.news_flash_obj` by fields from `location_info`
    - Remove `news_flash_obj` from `RequestParams`
- Cache tables
    - Get list of values and codes (or generate codes) for `street name`, `yishuv_name`, `road_segment_name`, `non_urban_intersection_name`
    - Decide on location infographics cache DB tables structure (I will consult Eliav)
    - Build cache tables
- Create location infographics api

I have a question: Where can I get the list of codes and values of  `street name`, `yishuv_name`, `road_segment_name`, `non_urban_intersection_name`?

**Comment by atalyaalon** [comment]
@ziv17 I assume we can close this one?

**Comment by ziv17** [comment]
Implemented.
