### ISSUE TITLE
Add severity text to widgets

### ISSUE THREAD

**Issue by atalyaalon** [hasadna/anyway#1852]
Split to severity with localized text of severity 
accident_count_by_accident_year (severity of accidents)
injured_count_by_accident_year (severity of injured)

@MichalOren FYI

**Comment by ziv17** [comment]
Hi @atalyaalon , 
The current data should be replaced by a dict with severity levels as keys and values the relevant items from current data?

**Comment by atalyaalon** [comment]
@ziv17 what do you think?
Here we had for example text separated from count- perhaps we should keep it as better practice? Not having translations as keys - since then do need to differentiate them (killed should be in red - and the FE needs to know how many killed using the key - in any language

**Comment by atalyaalon** [comment]
Also here: https://github.com/hasadna/anyway/blob/dev/static/data/widgets/accident_severity_by_cross_location.json
We will soon need to decide on templates we want to use - and we'll need to adjust best practices.
What do you think?

**Comment by ziv17** [comment]
Hi @atalyaalon , 
We want two levels of grouping? The severity should be the outer level or the inner?

**Comment by ziv17** [comment]
> 
> 
> @ziv17 what do you think?
> Here we had for example text separated from count- perhaps we should keep it as better practice? Not having translations as keys - since then do need to differentiate them (killed should be in red - and the FE needs to know how many killed using the key - in any language

Hi @atalyaalon , I don't understand

**Comment by ziv17** [comment]
> 
> 
> Also here: https://github.com/hasadna/anyway/blob/dev/static/data/widgets/accident_severity_by_cross_location.json
> We will soon need to decide on templates we want to use - and we'll need to adjust best practices.
> What do you think?

Here too, I do not understand.

**Comment by atalyaalon** [comment]
@ziv17 
I suggest the following structure no.3 here: https://github.com/hasadna/anyway/blob/dev/docs/WIDGETS.md

Meaning we'll have this for accident_count_by_accident_year (and create a similar one to injured_count_by_accident_year):
```
{
    "name": accident_count_by_accident_year,
    "data": {
                "items": {
                            "label1":
                                    [
                                        {
                                            "category1_name": 2017,
                                            "category1_value": 3
                                        },
                                        {
                                            "category2_name": 2018,
                                            "category2_value": 2
                                      
                                        {
                                            "category3_name": 2019,
                                            "category3_value": 2
                                        }
                                    ],
                            "label2":
                                    [
                                        {
                                            "category1_name": 2017
                                            "category1_value": 10
                                        },
                                        {
                                            "category2_name": 2018,
                                            "category2_value": 15
                                        },
                                        {
                                            "category2_name": 2019,
                                            "category2_value": 15
                                        }
                                    ],
                            "label3":
                                    [
                                        {
                                            "category1_name": 2017
                                            "category1_value": 40
                                        },
                                        {
                                            "category2_name": 2018,
                                            "category2_value": 55
                                        },
                                        {
                                            "category2_name": 2019,
                                            "category2_value": 34
                                        }
                                    ],

                        },
              "text": {
                          "title": "כמות התאונות לפי שנה במקטע כניסה למצפה שלם - צומת שדי תרומות"
                           "labels": {
                                            "label1": "קטלנית",
                                            "label2": "קשה",
                                            "label3": "קלה"
                                      }
                        }
            }
    "meta": {
        "rank": 8,
        "information": ""
        type: "stacked_bar"
    }
}
```

Also on the way - please add information for each of them (localized of course)
Let me know if I missed anything.
Thanks!

**Comment by atalyaalon** [comment]
@ziv17 also - when count of accidents/injured in specific year and severity is 0 - we should still display the category.
Thanks!

**Comment by ziv17** [comment]
@atalyaalon OK. Why are we naming the first level `label`, and the second level `category`? Both are attributes of accident.

**Comment by ziv17** [comment]
> 
> 
> @ziv17 what do you think?
> Here we had for example text separated from count- perhaps we should keep it as better practice? Not having translations as keys - since then do need to differentiate them (killed should be in red - and the FE needs to know how many killed using the key - in any language

@atalyaalon  I think it is a good idea to not use translated text as labels, and not use it in any logic.
It will be even better not to use the English string, but a code, or `Enum`, and only translate it just before it is sent outside.

**Comment by atalyaalon** [comment]
@ziv17 sounds good! Go for it.

**Comment by ziv17** [comment]
Hi @atalyaalon , regarding the `labels` part.

- Can `seriese<i>` be the actual code, i.e. actual accident severity code?
- I understand that `value` is the translated name of the accident severity. What is `name`? Is it the English name of the accident severity?

**Comment by ziv17** [comment]
Hi @atalyaalon ,
in `anyway/infographics_utils.py:1621`, there is a filter for injury severity. It seems to use non-existing values, and looks like it can be replaced by testing for `isnot(None)`.
I will implement it as part of this issue. Just take a brief look check whether my assumptions are correct.

**Comment by atalyaalon** [comment]
> Hi @atalyaalon , regarding the `labels` part.
> 
> * Can `seriese<i>` be the actual code, i.e. actual accident severity code?

I don't see any value in using the actual severity code.
I think that ideally this template should be used for any new stacked bar we create - hence we can either:

- Keep a generic name for the series keys (series1, series2, etc) (I think that this option is better)
- Replace them with the series value localized (same for category1 with the name) - in that case we need to make sure that the FE can receive from the BE, the colors,icons etc - for example - so they can differ the categories no matter what language we're in.
- Perhaps you have a better suggestion?

You can also consult with the FE team regarding this template (I suggest starting with Sergey)

> * I understand that `value` is the translated name of the accident severity. What is `name`? Is it the English name of the accident severity?

The goal of having the name is, for example, make sure that the FE team can tell the difference between fatal and severe no mater what language we're in (for example, differ colors, icons, etc)

**Comment by ziv17** [comment]
> 
> 
> > Hi @atalyaalon , regarding the `labels` part.
> > 
> > * Can `series<i>` be the actual code, i.e. actual accident severity code?
> 
> I don't see any value in using the actual severity code.
> I think that ideally this template should be used for any new stacked bar we create - hence we can either:
> 
>     * Keep a generic name for the series keys (series1, series2, etc) (I think that this option is better)
> 
>     * Replace them with the series value localized (same for category1 with the name) - in that case we need to make sure that the FE can receive from the BE, the colors,icons etc - for example - so they can differ the categories no matter what language we're in.
I thought we want to avoid using localized values as keys. In addition, in this case, The `labels` will have redundant data, ,and should change to `{value1: name1, value2: name2, ...`
> 
>     * Perhaps you have a better suggestion?
The `series<i>` values appear twice in the widget output, and its sole function is to link the `name` and `value` from the `labels` to the outer level `items` dict keys. So as long as these values are unique, they fulfill their goal. So I would use the entity codes as it is minimal, simple and. I do not see what value generic names brings (Maybe I do not understand what do you mean).


> 
> 
> You can also consult with the FE team regarding this template (I suggest starting with Sergey)
> 
> > * I understand that `value` is the translated name of the accident severity. What is `name`? Is it the English name of the accident severity?
> 
> The goal of having the name is, for example, make sure that the FE team can tell the difference between fatal and severe no mater what language we're in (for example, differ colors, icons, etc)

**Comment by atalyaalon** [comment]
@ziv17 as we discussed - what ever you think is best :)

**Comment by ziv17** [comment]
Closed by PR 1875
