### ISSUE TITLE
Getting a 404 error when attempting to get an accident query with the accidents_around_location script [Bug]

### ISSUE THREAD

**Issue by darlev** [hasadna/anyway#1853]
Hello,
When I attempt to run a query through the accidents_around_location.py script I keep getting a 404 error when requesting markers through the ANYWAY_MARKERS_FORMAT url. I cloned the script from the dev branch. Is there any other URL I can use?
Thanks

**Comment by atalyaalon** [comment]
@darlev Welcome :)
Perhaps I can help you - what kind of data are you looking for?

**Comment by darlev** [comment]
Hello :) I was trying export traffic accident data around Tel Aviv from June 2020 to June 2021 - specifically events involving bicycles, e-bikes and e-scooters with timestamps and locations. Is it still possible to do with your API?

**Comment by atalyaalon** [comment]
@darlev please contact us via anyway@anyway.co.il

**Comment by atalyaalon** [comment]
Not a bug
