### ISSUE TITLE
Overlapping Marker Spiderfier lines stay after unspiderfying

### ISSUE THREAD

**Issue by danielhers** [hasadna/anyway#187]

**Comment by danielhers** [comment]
When unspiderfying the `oms` by moving the map or by other means, the marks that the `oms` left when spiderfied remain:
![screenshot](https://cloud.githubusercontent.com/assets/263363/6349563/9812126c-bc34-11e4-9981-cded3fd88d4c.png)
They should be erased when unspiderfying.
Clicking the map unspiderfies properly and removes the mark, but all other means of unspiderfying don't.

**Comment by OmerSchechter** [comment]
Occurs when changing the filter at the sidebar, while the spider-net is open.

**Comment by OmerSchechter** [comment]
This can be closed.
