### ISSUE TITLE
[Only interest points are visible on the map when choosing newsflash]

### ISSUE THREAD

**Issue by karzmei** [hasadna/anyway#1874]
**Describe the bug**
On https://anyway-infographics-staging.web.app/, I click on some newsflash, in the results, the map is sometimes displayed without the streets/roads, only the "cars with dates" are visible. After I do zoom in/out it appears and all is good.

**To Reproduce**
1. Go to https://anyway-infographics-staging.web.app/
2. Click on some newsflash on the right-hand-side menu.
3. Look at the map part in the results.
4. Do zoom in/out of the map in case there's something missing and see if it appears afterwards.

**Expected behavior**
Expect to see the complete map, no missing roads.

**Screenshots**
![no_map_anyway](https://user-images.githubusercontent.com/13590934/129070325-d2cb8db4-d22f-400c-8e77-512dab3cda27.png)

**Environment**
System: Ubuntu, with Firefox.

**Additional context**
People reported (on Slack) the same issue in other browsers: safari and chrome.

**Comment by atalyaalon** [comment]
@karzmei Wonderful!
However this is the BE repo - and the FE repo[ can be found here.](https://github.com/hasadna/anyway-newsflash-infographics). Can you please close the issue here and open it in the FE repo?

**Comment by karzmei** [comment]
Oh! Thanks, I didn't realize that it's separate. Done.
