### ISSUE TITLE
Modify variables in meta field in infographics-data API

### ISSUE THREAD

**Issue by atalyaalon** [hasadna/anyway#1902]
In meta field of the API we send "dates_comment"

FE request is as follows:
we have issue with "dates_comment"
8:02
currently is comes as one text:
"2017-2021, עדכון אחרון: 2021-06-30"
8:05

We would like to split it into 2 properties? like:
{
 dates: [2017, 2021]
 last_update: 2021-06-30 // can be other format if you prefer, like ISO or unix time
}

@yuvalbl FYI

**Comment by shaysw** [comment]
will return last_update as Unix timestamp (decimal). 
Example:
{
    'dates': [2014, 2021], 
    'last_update': 1627689600.0
}
