### ISSUE TITLE
Add user API to swagger 

### ISSUE THREAD

**Issue by BarVolunteering** [hasadna/anyway#1903]
reference to user API
https://github.com/hasadna/anyway/pull/1890#pullrequestreview-751961294

Regarding our swagger:
See [this issue](https://github.com/hasadna/anyway/issues/1780) (not done yet) and [this pr](https://github.com/hasadna/anyway/pull/1794)

Our current swagger https://www.anyway.co.il/swagger

**Comment by atalyaalon** [comment]
@BarVolunteering can you elaborate which API functions should be added to swagger?

**Comment by BarVolunteering** [comment]
I planed on converting those [Docs](https://github.com/hasadna/anyway/blob/dev/docs/USERAPI.md) to swagger
