### ISSUE TITLE
Add data test to make sure all CBS tables are updated after importing data

### ISSUE THREAD

**Issue by atalyaalon** [hasadna/anyway#1906]
Should be tested in aifrlow after CBS executer is done and alert to our emails for an error
See [this bug fixed](https://github.com/hasadna/anyway/pull/1905)
And see [this redash query](https://app.redash.io/hasadna/queries/975346/source) shows the vehicles table hasn't updated in a while (!) (will be fixed by me soon so attaching here the past results)

@OriHoch any best practices for data quality tests?

![Screen Shot 2021-09-16 at 20 27 48](https://user-images.githubusercontent.com/20992625/133657849-c7abe794-d5d0-4918-941b-45b38fd2b61f.png)

**Comment by OriHoch** [comment]
@atalyaalon we can add a dag that checks some things in DB. What exactly should be checked for this case?

**Comment by OriHoch** [comment]
if you want to test the max_timestamp, so what's the condition for failing? if max_timestampt is older then how many days?

**Comment by atalyaalon** [comment]
We set the default to 90.

**Comment by OriHoch** [comment]
deployed in https://github.com/hasadna/anyway-etl/releases/tag/v0.0.4

https://airflow.anyway.co.il/log?dag_id=cbs&task_id=check-data-in-datastore&execution_date=2021-09-17T15%3A19%3A50.069135%2B00%3A00
