### ISSUE TITLE
check why vehicles table from cbs import is not updated

### ISSUE THREAD

**Issue by OriHoch** [hasadna/anyway#1909]
[this redash query](https://app.redash.io/hasadna/queries/975346/source) shows the vehicles table hasn't updated in a while

**Comment by atalyaalon** [comment]
@OriHoch I created a fix in anyway-etl (that was merged and created a new release)
When the flask babel issue is fixed, I believe this issue will be fixed as well.

**Comment by OriHoch** [comment]
yes, looks like it will fix it

**Comment by OriHoch** [comment]
https://github.com/hasadna/anyway-etl/pull/5

**Comment by OriHoch** [comment]
fixed in https://github.com/hasadna/anyway-etl/releases/tag/v0.0.4

https://airflow.anyway.co.il/log?dag_id=cbs&task_id=check-data-in-datastore&execution_date=2021-09-17T15%3A19%3A50.069135%2B00%3A00
