### ISSUE TITLE
Separate description to individual fields in process.py

### ISSUE THREAD

**Issue by danielhers** [hasadna/anyway#192]

**Comment by danielhers** [comment]
Required for #49

**Comment by danielhers** [comment]
@tedwin007 have you started working on this?

**Comment by omerxx** [comment]
I changed process.py and added missing names to field_names.py
Should I change Marker class in models.py too and separate the description there as well?
I'm not familiar with the exact structure, but isn't that a must before updating marker.js?

**Comment by danielhers** [comment]
Yes, `Marker` needs to be updated to have the extra fields. Otherwise `process.py` won't have where to save the extra data it's loading...

**Comment by danielhers** [comment]
@omerxx need any help?

**Comment by omerxx** [comment]
Working on it, I'll let you know where I stand soon

**Comment by omerxx** [comment]
I managed to split the description and present to raw data (integers) in the marker.
Modified:
models.py (class marker) - Should I modify 'update' function as well?
process.py (import_accidents) - 
field_names.py for extra fields
marker.js
index.html (needed to add fields for the jQuery)

* I only took what I thought was part of the description, there are still many values in the csv that are not dealt with or referred. should this contain *every* value in the csv?

* I managed to present only raw data, how do I translate the integer I got to Hebrew?
(for example an accident 'roadType' gives the value '2', how does it convert to actual Hebrew?)

**Comment by danielhers** [comment]
You can ignore `update`. It will probably be removed soon.
For now, let's just take the values that appear in the description. Later we can think what other fields we want.
The file `localization.py` contains the translation from integers to field values in Hebrew.

**Comment by omerxx** [comment]
Okay.
This is what I've put in:
            "roadType":int(accident[field_names.road_type]),
            "accidentType":int(accident[field_names.accident_type]),
            "roadShape":int(accident[field_names.road_shape]),
            "subtype":int(accident[field_names.accident_type]),
            "severity":int(accident[field_names.accident_severity]),
            "dayType":int(accident[field_names.day_type]),
            "igun":int(accident[field_names.igun]),             # is this the same as locationAccuracy?
            "unit":int(accident[field_names.unit]),

let me know if I'm missing anything.
I'll check the localization translation

**Comment by danielhers** [comment]
`igun` is the same as `locationAccuracy`, yes. No need for a separate field.
Take a look at `load_extra_data`: you need the same data that it loads, but
save it in separate fields rather than in a single description.
It uses `localization.get_supported_tables()` which simply returns the keys
of the dictionary in `localization.py`. So you need all of these.

**Comment by omerxx** [comment]
@danielhers 
The python code for loading the data is ready.
For presenting each value I have to also edit the description functions under models.py
There are fomat_description and json_to_description that form the localization.

How do you want to do it?

**Comment by danielhers** [comment]
Well, if we send each field separately then we won't need these functions.
You can send a pull request with what you have and we'll see what's left.

**Comment by omerxx** [comment]
I'm taking localization.get_field(field, value) but this creates a unicode error.
How do I decode it so it can be used?

**Comment by danielhers** [comment]
Just like in `format_description`:
`localization.get_field(field, value).decode(db_encoding)`

**Comment by omerxx** [comment]
I tried this with content_encoding (db_encoding is not acceptable) and I get no result

**Comment by omerxx** [comment]
Just got what my problem was... I'm almost there.
I'll let you know when it's ready
