### ISSUE TITLE
Improve performance of widget motorcycle_accidents_vs_all_accidents

### ISSUE THREAD

**Issue by atalyaalon** [hasadna/anyway#1922]
Possibly with agg tables / cache, @ziv17 is leading this.
Ziv - I suggest we'll perform this after deciding on architecture.

**Comment by atalyaalon** [comment]
FE issue - waiting for API - https://github.com/hasadna/anyway-newsflash-infographics/issues/541

**Comment by ziv17** [comment]
Hi @atalyaalon I do not understand what is required here.
Cache is already implemented.

**Comment by ziv17** [comment]
Hi @atalyaalon 
What is the use-case that this issue intends to resolve? I am asking, because the way I see it, the solution is either small tables, or cache, which we already have.

**Comment by atalyaalon** [comment]
@ziv17 I agree.
If you find options for performance improvements [while working on this widget](https://github.com/hasadna/anyway/issues/2080) - please improve.
