### ISSUE TITLE
auth code improvements: permission checks, allowed fields

### ISSUE THREAD

**Issue by OriHoch** [hasadna/anyway#1925]
a couple of patterns I see in the auth code which I think could be improved:

### permission checks

Current code example:

```
@app.route("/admin/get_all_users_info")
def get_all_users_info() -> Response:
    if current_user.is_anonymous:
        return return_json_error(Es.BR_USER_NOT_LOGGED_IN)
    if not is_current_user_have_permission(db, request):
        return return_json_error(Es.BR_MISSING_PERMISSION)
   ## function code ##
```

Recommended code:

```
@app.route("/admin/get_all_users_info")
@check_permissions(role="admin")
def get_all_users_info() -> Response:
   ## function code ##
```

Also, for enhanced security - returned error should just be a generic "auth error", should not provide any details about the reason for the error

### allowed fields

Some functions check a list of allowed fields before performing some admin operations, for example:

```
@app.route("/admin/update_user", methods=["POST"])
def admin_update_user() -> Response:
    allowed_fields = [
        "user_current_email",
        "first_name",
        "last_name",
        "email",
        "phone",
        "user_type",
        "user_url",
        "user_desc",
        "is_user_completed_registration",
    ]
    res = look_for_errors_in_request_admin(request, allowed_fields)
    if res:
        return res
   ## function code ##
```

Having this list of allowed_fields implies that somewhere down the function there is code that iterates over all the request fields and updates in bulk. This can cause security problems when fields or security requirements change. Instead, the function code should use specific field names, and make it's own checks regarding validity and not get data from the request in bulk. So the function look_for_errors_in_request_admin with allowed_fields will not be needed.

**Comment by OriHoch** [comment]
note that the issue is regarding all instances of these examples, not the specific functions in the code examples

**Comment by OriHoch** [comment]
following talk with @BarVolunteering - clarification regarding allowed fields - the main problem is separation of concerns. Permission checks should be separate and simple using check permissions as described above.

**Comment by BarVolunteering** [comment]
@atalyaalon This is already done, we moved to use `roles_accepted` decorator
