### ISSUE TITLE
update mock data with 3 updated widgets data

### ISSUE THREAD

**Issue by atalyaalon** [hasadna/anyway#1929]
- accident_count_by_accident_year
- injured_count_by_accident_year
- injured_accidents_with_pedestrians

Reference material:
[mock data in api](https://github.com/hasadna/anyway/blob/55bda1fa60e16bd3c68d0f74b2f41aa2daa54e7c/anyway/flask_app.py#L1378)

[static mock data of widgets ](https://github.com/hasadna/anyway/tree/dev/static/data/widgets)

**Comment by shaysw** [comment]
@atalyaalon asides from the newly modified "injured_accidents_with_pedestrians", the other 2 widgets seem to have mock data in the desired format. Am i missing somthing?
