### ISSUE TITLE
timeout accessing gps-to-location api

### ISSUE THREAD

**Issue by OriHoch** [hasadna/anyway#1940]
**reproduction steps**
* access the gps-to-location api: http://www.anyway.co.il/api/gps-to-location?longitude=35.385893&latitude=31.361586

**expected**
* successful response

**actual**
* http error 504 gateway timeout

**Comment by OriHoch** [comment]
@atalyaalon it times out at 3 minutes, I highly recommend to check the reason, it looks like something wrong in this code if it takes this long and it has potential for easy DOS attacks on the site

**Comment by atalyaalon** [comment]
@OriHoch I agree. Closing for now

**Comment by atalyaalon** [comment]
I will solve the api issue instead of increasing timeout
