### ISSUE TITLE
[Bug] CORS error in production

### ISSUE THREAD

**Issue by atalyaalon** [hasadna/anyway#1951]
**Describe the bug**
we get CORS error in production in user/info API

@BarVolunteering can you explain how to login?

**To Reproduce**
go to www.media.anyway.co.il

**Expected behavior**
temporary fix: https://github.com/hasadna/anyway/pull/1949

**Screenshots**
<img width="709" alt="Screen Shot 2021-10-05 at 19 43 35" src="https://user-images.githubusercontent.com/20992625/136072693-3a542b61-a26a-4c10-89d3-5f2ac4a42416.png">

**Environment**
System: mac, chrome

**Additional context**

**Comment by atalyaalon** [comment]
@OriHoch this fix didn't work
https://github.com/hasadna/anyway/pull/1950/files
If you have a quick workaround would appreciate it.

**Comment by OriHoch** [comment]
Please send me instructions on how to login

**Comment by BarVolunteering** [comment]
@OriHoch As the web gui not working, please access the flowing URL to login:
https://dev.anyway.co.il/authorize/google

**Comment by OriHoch** [comment]
fixed in https://github.com/hasadna/anyway/pull/1953
deployed to dev
looks like it works

**Comment by atalyaalon** [comment]
Amazing, thank you so much @OriHoch
