### ISSUE TITLE
anyway Dev environment

### ISSUE THREAD

**Issue by atalyaalon** [hasadna/anyway#1964]
- [x] Duplicate prod DB to dev
- [x] Create airflow processes that constantly run in prod - to run in dev airflow as well.

@BarVolunteering do we need to keep the data from users tables in dev? Or can we just copy the data from prod users?
Perhaps we should check this with the FE before deciding on it?

**Comment by BarVolunteering** [comment]
If you overwrite all the relevant tables in dev - then there should be no problem.
I don't think that FE have any important data in those tables, but we can ask to be on the safe side.
@yuvalbl @danielsh28

**Comment by OriHoch** [comment]
I'll duplicate the entire db and then you can delete any data you don't want

**Comment by OriHoch** [comment]
https://github.com/hasadna/hasadna-k8s/pull/18

dev DB is currently being restored from backup

**Comment by OriHoch** [comment]
restore complete

**Comment by OriHoch** [comment]
I enabled all the airflow tasks in dev
