### ISSUE TITLE
DB dump for dev - truncate instead of drop tables

### ISSUE THREAD

**Issue by atalyaalon** [hasadna/anyway#1989]
Dropping the tables and then using them in local dev environment causes problems (for example when dropping a column of a specific table - just like we did [in this pr](https://github.com/hasadna/anyway/pull/1890/files#diff-37593c096e4e6c7baad38084911e6cdf736a8884d7e4cdfbb658c88d45974b10R20) - alembic upgrade head does not work locally)

Hence - instead of dropping tables when dumping the DB - perhaps it's possible to dump and then truncate the relevant user tables (and only then make it available after truncating so no one can see the users data?)

**Comment by OriHoch** [comment]
see related comment: https://github.com/hasadna/anyway/pull/1991#pullrequestreview-793729124

**Comment by atalyaalon** [comment]
@OriHoch do you need anything from us to perform this ticket?
@BarVolunteering is the final list of tables known? Perhaps add it also here?

**Comment by BarVolunteering** [comment]
Tables list:
users
roles
locationsubscribers
users_to_roles
users_to_organizations
organization

**Comment by OriHoch** [comment]
no, I don't need anything

**Comment by OriHoch** [comment]
we cannot truncate the tables because the dump is performed on prod db

The solution I'm trying to implement is to have 2 dump files: one same as today without the tables, another one with only the schemas of the missing tables.

**Comment by OriHoch** [comment]
done, opened PRs: #2013, #2014
