### ISSUE TITLE
Using the navigator on the left to move the map doesn't trigger refreshing map data

### ISSUE THREAD

**Issue by samuelregev** [hasadna/anyway#204]
![uploads/11eb2d92-d5e9-448a-ae71-47ccf2403625/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F11eb2d92-d5e9-448a-ae71-47ccf2403625%2Fblob)

**Comment by danielhers** [comment]
Also when using the arrow keys.
