### ISSUE TITLE
Widget: injured_accidents_with_pedestrians - modify API

### ISSUE THREAD

**Issue by atalyaalon** [hasadna/anyway#2044]
**Name**
injured_accidents_with_pedestrians

Task: widget already exists - modify API to fit the structure of stacked bar graph API - similar to API structure of widget accident_count_by_accident_year
Please talk to @ziv17 that is familiar with the wanted API structure

**Title**
already exists

**Visualization**
stacked bar graph

**Visualization explanation**
Explain visualization content.

Design is here: https://github.com/hasadna/anyway-newsflash-infographics/issues/602

**Comment by BarVolunteering** [comment]
The data of this widget need to ordered, From @atalyaalon message on Slack:
>The stacked bar widgets in BE should be changed as following:
>1.Ordering will be done in BE of each item (in the above example - year items are indeed in increasing order: 2017, 2018, 2019)
>2.Ordering will be done in BE of each data series (in the above example - we're not consistent - let's order with fatal in the bottom of the stacked bar - hence order should be fatal, severe, light).
>3.label key should be string as FE requested


Relevant issue on FE side: [anyway-newsflash-infographics/pull/842](https://github.com/hasadna/anyway-newsflash-infographics/pull/842)
