### ISSUE TITLE
Urban Widgets - add existing widgets to urban resolution

### ISSUE THREAD

**Issue by atalyaalon** [hasadna/anyway#2045]
We want new widget for Urban - Street resolution
(works in street resolution - such that the wanted street can be either in street1 or in street2 - see InjuredAccidentsWithPedestriansWidget widget)

- accident_count_by_severity_urban - see https://github.com/hasadna/anyway/issues/2093

- map_accidents_urban - EDIT: similar structure to most_severe_accidents but with SAME logic:
https://github.com/hasadna/anyway/issues/2107

- accidents_table_urban - similar structure to most_severe_accidents_table but with different logic: https://github.com/hasadna/anyway/issues/2096
Order by severity, first take fatal and sever accidents
If their number is less than 10, order the light accidents by date and add light accidents up to total (all severities) of 10 (or less if there are less in total)  using latest light accidents.

**Comment by ziv17** [comment]
Hi @atalyaalon , are there additional widgets to work in within this issue, or can it be closed?

**Comment by atalyaalon** [comment]
@ziv17 great work, closing this one
