### ISSUE TITLE
Widget: Order the data in accident_count_by_car_type

### ISSUE THREAD

**Issue by BarVolunteering** [hasadna/anyway#2071]
The data of this widget need to ordered, From atalyaalon message on Slack:

>The stacked bar widgets in BE should be changed as following:
>1.Ordering will be done in BE of each item (in the above example - year items are indeed in increasing order: 2017, 2018, 2019)
>2.Ordering will be done in BE of each data series (in the above example - we're not consistent - let's order with fatal in the bottom of the stacked bar - hence order should be fatal, severe, light).
>3.label key should be string as FE requested

Relevant issue on FE side: [anyway-newsflash-infographics/pull/842](https://github.com/hasadna/anyway-newsflash-infographics/pull/842)

**Comment by atalyaalon** [comment]
Thank you @BarVolunteering .
Also there are additional two changes that are needed for this Widget:

- [ ]  Change data model in the widgets to the vehicles_markers_hebrew (relates to #1481) 
- [ ] Return only top 3 categories (order by top 3 count of segment, not average of country)
