### ISSUE TITLE
Widget motorcycle_accidents_vs_all_accidents - new data structure

### ISSUE THREAD

**Issue by atalyaalon** [hasadna/anyway#2080]
- [ ] This widget contains a stacked bar graph - modify structure accordingly 
Discuss with Chen (FE team) to make sure you're aligned (since she needs to present percentage but I believe she will expecting absolute numbers)
- [ ] Re-register widget

FE issue - waiting for API - hasadna/anyway-newsflash-infographics#541

**Comment by ziv17** [comment]
https://github.com/hasadna/anyway-newsflash-infographics/issues/541#issuecomment-1018708915
