### ISSUE TITLE
When adding new table to DB - add redash permissions to it by default

### ISSUE THREAD

**Issue by atalyaalon** [hasadna/anyway#2081]
Perhaps @OriHoch can advise in what's the best way to do so.

**Comment by OriHoch** [comment]
Because you have tables with private data, there is some risk in doing that, but if you are sure no private tables will ever be added in the future you can do it with the following SQL:

```
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO readonly;
```

**Comment by atalyaalon** [comment]
After a discussion we decided not to grant access, but to do it table by table - see [this pr](https://github.com/hasadna/anyway/pull/2142/files) with an explanation how to grant access to a table
