### ISSUE TITLE
Widget: accidents_table_urban

### ISSUE THREAD

**Issue by MichalOren** [hasadna/anyway#2096]
**Name**
Widget for accidents in **urban street resolution** for all accident types at a specific street.

**Title**
accidents_table_urban

**Visualization**
![image](https://user-images.githubusercontent.com/61007501/151230407-53f24564-f612-4768-8d3c-7f0aaca7665a.png)
Sample graphic image of the widget that will be displayed by FE.

**Visualization explanation**
similar structure to most_severe_accidents_table but with different logic:
Order by severity, first take fatal and severe accidents.
If their number is less than 10, order the light accidents by date and add light accidents up to total (all severities) of 10
(or less if there are less in total) using latest light accidents.

**Use case**
This infographic should be displayed only when street name and city name are identified (not final. expected new logic- TBC)
(works in street resolution - that the wanted street can be either in street1 or in street2 - see InjuredAccidentsWithPedestriansWidget widget)

**SQL query**
New logic- TBC
(When creating the query and filtering CBS data - it's better to use the numeric values of the categorical fields (accident_severity = 1 is better than accident_severity_hebrew = 'תאונה קטלנית'). For code redeablity - one can create constants and dictionaries.)

**Additional context**
Example for the API widget structure provided by BE team:
"name": "accidents_table_urban",
            "data": {
                "items": [
                    {
                        "accident_year": 2020,
                        "accident_severity": "קשה",
                        "type": "החלקה",
                        "date": "23/10/20",
                        "hour": "09:00",
                        "killed_count": 0,
                        "severe_injured_count": 1,
                        "light_injured_count": 0,
                        "injured_count": 1
                    }
                ],
                "text": {
                    "title": "תאונות חמורות ברחוב ז'בוטינסקי , פתח תקווה
                }
            },
            "meta": {
                "rank": ***,
                "information": ".התאונות החמורות (קשות וקטלניות) האחרונות, מסודרות לפי תאריך בסדר יורד. מוצגות עד 10 תאונות"
            }
        },
        {
Find full structure in an existing news flash
https://www.anyway.co.il/api/infographics-data?lang=he&news_flash_id=101235&years_ago=8

**Comment by ziv17** [comment]
Hi @MichalOren , two questions:

1. Actually we want to order first by severity, and then (within each severity) by date (last first), and take the first ten. right?
2. Do we want to change the behavior of the sub_urban widget to be the same as the urban?

**Comment by atalyaalon** [comment]
@ziv17 
1. Yes
2. No, Each table widget (urban/sub urban) will have a different behavior. Information should be accordingly in each widget

**Comment by atalyaalon** [comment]
@ziv17 after a discussion, this widget WILL contain only fatal and severe accidents.
We'll open a different issue for a table containing all severities.

**Comment by ziv17** [comment]
BE part is completed (PR #2146)
