### ISSUE TITLE
Sort stacked bar widgets

### ISSUE THREAD

**Issue by atalyaalon** [hasadna/anyway#2097]
@BarVolunteering wasn't sure if this widget already sorted - injured_accidents_with_pedestrians
Any other stacked bars that you know of that are not sorted?

**Comment by BarVolunteering** [comment]
I will check about injured_accidents_with_pedestrians, but maybe @shaniwein remember if its sorted?

The other bars that need to be sorted are:
accident_count_by_car_type  (issue #2071)
injured_count_by_accident_year (issue #2070)
accident_count_by_accident_year (issue #2050)

**Comment by BarVolunteering** [comment]
Update after PR - The bars that need to be sorted are:
accident_count_by_car_type (issue #2071)

and maybe injured_accidents_with_pedestrians

**Comment by shaniwein** [comment]
injured_accidents_with_pedestrians is sorted

**Comment by atalyaalon** [comment]
@BarVolunteering great work! Can I close this one?

**Comment by BarVolunteering** [comment]
Yes
