### ISSUE TITLE
Widget: Add a title to map_accidents_urban

### ISSUE THREAD

**Issue by MichalOren** [hasadna/anyway#2107]
**Name**
Widget for **map accidents in urban street resolution** for srvere & fatal accident at a specific street.

**Title**
map_accidents_urban

**Visualization**
![image](https://user-images.githubusercontent.com/61007501/153255740-7fd43f53-9e9f-4bc6-b7f3-70ad4aa2389e.png)

Sample graphic image of the diagram that will be displayed by FE.

**Additional context**
Currently the json dosent include title section
     "text": {
                    "title": "תאונות חמורות ברחוב ז'בוטינסקי, פתח תקווה"
                }

**Comment by atalyaalon** [comment]
@MichalOren @ziv17 
Just to clarify, this task requires 2 tasks
1. Add the urban version (only with severe and fatal accidents) in the street, including a title
2. Add title to the non-urban version
3. Regarding the variation we discussed of the map and table containing light accidents, @MichalOren we'll create different issues for that.

**Comment by ziv17** [comment]
@atalyaalon what is the suburban widget we want to add urban version for?

**Comment by atalyaalon** [comment]
@ziv17  most_severe_accidents

**Comment by ziv17** [comment]
Hi @MichalOren 
For the suburban case, do we want also the road number in the title? E.g.
`Severe accidents at road 90 from place x to place y`, or
`Severe accidents at  road segment place x to place y`

**Comment by atalyaalon** [comment]
@ziv17 great work, closing this one

**Comment by atalyaalon** [comment]
@ziv17 actually I assume the urban widget does not exist yet? reopening

**Comment by ziv17** [comment]
Hi @MichalOren @danielsh28 @atalyaalon 
The urban widget already exists (in BE repo, dev branch). Is it OK?

**Comment by MichalOren** [comment]
Hi @ziv17 and @atalyaalon 
I can see we have a TAG called "label_map" that specify graph or map legend. 
do we to add it in both interuban and urban **map** widgets?

**Comment by ziv17** [comment]
Hi @MichalOren Can you elaborate? What TAG do you refer to? Where does it appear?

**Comment by ziv17** [comment]
BE work is completed.
