### ISSUE TITLE
Widget: Update title to accident_count_by_driver_type widget

### ISSUE THREAD

**Issue by MichalOren** [hasadna/anyway#2109]
**Feature request**
Update to widget **accident_count_by_driver_type**

**Required changes**
As a part of update (facelift) to this widget the following changes are expected: 
- Title changes - remove segment name from title - (BE team)
- Logic modification: at the moment we're counting  ALL involved instead of accidents (we're counting involved with the specific vehicle type instead of counting distinct provider_and_id) AND we're counting all involved type instead of counting only the drivers (see field involved_type / involved_type_hebrew) - there are 3 involved_types, please consider drivers only (נהג and נהג_נפגע) - see [fields meaning here](https://docs.google.com/spreadsheets/d/1qaVV7NKXVYNmnxKZ4he2MKZDAjWPHiHfq-U5dcNZM5k/edit#gid=266079360)
- Information modification: 
instead of "מעורבות נהגים בתאונות לפי סוג נהג..." use "מספר תאונות לפי סוג נהג"

- Enlarge pie size - (FE team)
- Remove years details below - (FE team)

**Visualization**
New display
![image](https://user-images.githubusercontent.com/61007501/152477237-8a2ad1cf-7897-4711-b04f-27e74fccca15.png)

Current display
![image](https://user-images.githubusercontent.com/61007501/152477295-c679d451-64fe-4129-b8e9-3ae95ff71b01.png)

**Additional context**

**Comment by atalyaalon** [comment]
[Local API Link](127.0.0.1:8080/api/infographics-data?news_flash_id=16577&years_ago=8&lang=he)
[Server API Link](www.anyway.co.il/api/infographics-data?news_flash_id=16577&years_ago=8&lang=he)

`{
            "name": "accident_count_by_driver_type",
            "data": {
                "items": [
                    {
                        "driver_type": "נהג רכב פרטי",
                        "count": 229
                    },
                    {
                        "driver_type": "נהג מקצועי",
                        "count": 51
                    },
                    {
                        "driver_type": "אחר",
                        "count": 8
                    }
                ],
                "text": {
                    "title": "מספר תאונות לפי סוג הנהג"
                }
            },
            "meta": {
                "rank": 16,
                "information": "מעורבות נהגים בתאונות לפי סוג נהג: מקצועי - משאיות, מוניות, אוטובוס, רכב עבודה, מיניבוס, טרקטור, נהג פרטי - רכב פרטי, אופנוע, חשמלי קל - קלנועית, קורקינט ואופניים חשמליים."
            }
        },`

@MichalOren @shaysw FYI

**Comment by atalyaalon** [comment]
@volsky note to this pr that is not finished (I assume we'll close it once you create your pr)
https://github.com/hasadna/anyway/pull/2147/files

**Comment by atalyaalon** [comment]
Also note that the title is already present, but we're missing the logic change
