### ISSUE TITLE
Markers in group reset to the default after clicking for the second time

### ISSUE THREAD

**Issue by uda** [hasadna/anyway#212]
If I click on a marker within a group once, close the popup and then click on it again, the marker resets to the default icon.
Additionally, any marker, within any group, clicked on later will also reset to the default.

**Comment by danielhers** [comment]
@OmerSchechter please take a look

**Comment by OmerSchechter** [comment]
Yes, I'm already looking into it.
It's a bit weird, but i'll figure it out.

**Comment by OmerSchechter** [comment]
O.K. I've fixed it. But there's something I'm wondering about from looking at the code:
Why do we fetchMarkers() and through that reloadSidebar() when a user is closing the infoWindow for a marker?(and after that also setMultipleMarkersIcon())
```javascript
clickMarker : function() {
        this.highlight();
        app.closeInfoWindow();

        app.selectedMarker = this;
        app.infoWindow = new google.maps.InfoWindow({
            content: this.el
        });

        app.infoWindow.open(this.map, this.marker);
        app.updateUrl(this.getUrl());

        google.maps.event.addListener(app.infoWindow,"closeclick",function(){
            app.fetchMarkers();
        });
    }
```

Shouldn't the:
```javascript
google.maps.event.addListener( this.map, "idle", _.bind(this.fetchMarkers, this) );
```
be taking care of that?

**Comment by danielhers** [comment]
That's right. It's a remnant from before I changed it to "idle", so now the
markers are loaded right when the info window is loaded (thanks to "idle")
and there's no need for fetching after it closes. Want to remove it?

**Comment by OmerSchechter** [comment]
Sure, will do.

**Comment by danielhers** [comment]
@OmerSchechter what's the progress on this?
