### ISSUE TITLE
Widget: Update accident_count_by_accident_type widget

### ISSUE THREAD

**Issue by MichalOren** [hasadna/anyway#2122]
**Name**
Required changes to widget accident count by accident type

**Title**
accident_count_by_accident_type widge

**Required changes**
•  Add Title - years and widget name to heading (BE & FE)
•  Add filter “top 3 types” results (BE)
•  Pie will display only “top 3 types” results (FE)
•  Enlarge pie size  (FE)
•  Remove years details below (FE)
•  Add information text (BE)

**Visualization explanation**
New display
![image](https://user-images.githubusercontent.com/61007501/154673271-3ef202ad-c17b-4d30-aa24-cdebd6ea310d.png)

Current display
![image](https://user-images.githubusercontent.com/61007501/154672077-f8d35c5a-a72b-4797-9e08-a549fe4b3cf4.png)

**Use case**
When this infographic should be displayed: allways

**Information Tag**
Will include the following description:
התפלגות תאונות לפי סוג התאונה במקטע, בפרק הזמן הנבחר. מוצגים 3 סוגי התאונות הנפוצים ביותר במקטע זה. 

**Additional context**
- Definition will be used by BE team to generate a Json response to FE
- Definition will be provided by Data team, after internal review
- Definition will be written in English and should use language agnostic definitions and data structures 
(e.g. SQL columns) as much as possible.

**Comment by ziv17** [comment]
Hi @atalyaalon @yuvalbl ,
Who from the FE team should I work with to coordinate the API format for this widget?
Thanks,  Ziv

**Comment by atalyaalon** [comment]
@ziv17 Let's keep the same format for now - since widget already exists in FE, but with multiple categories.
Also, widget uses Hebrew field (accident_type_hebrew), I suggest using the accident_type and create relevant constants.

**Comment by ziv17** [comment]
Hi @MichalOren , @atalyaalon 
The current code excludes the following accident types:
    PEDESTRIAN_INJURY = 1
    SWERVING_OFF_THE_ROAD_OR_ONTO_THE_PAVEMENT = 9
    OVERTURNED_VEHICLE = 10
    SKID = 11
    INJURY_OF_A_PASSENGER_IN_A_VEHICLE = 12
    A_FALL_FROM_A_MOVING_VEHICLE = 13
    FIRE = 14
    OTHER = 15
    DAMAGE_CAUSED_BY_A_FALLING_LOAD_OFF_A_VEHICLE = 20

Is it OK?

**Comment by ziv17** [comment]
Hi @MichalOren @atalyaalon
BE work is done and merged. Is there a twin task in the FE repository?

**Comment by MichalOren** [comment]
Hi @ziv17 👍  greate
@atalyaalon @danielsh28
No twin task in the FE repository. will it help if I open one for FE?

**Comment by ziv17** [comment]
Hi @MichalOren , what do you mean by "multiple types"?
I do not know what environment you are using. It is visible in this repository in branch `dev`.

**Comment by atalyaalon** [comment]
Local API Link for example- 127.0.0.1:8080/api/infographics-data?news_flash_id=16577&years_ago=8&lang=he
[Server API Link for example](www.anyway.co.il/api/infographics-data?news_flash_id=16577&years_ago=8&lang=he)

        {
            "name": "accident_count_by_accident_type",
            "data": {
                "items": [
                    {
                        "accident_type": "התנגשות",
                        "count": 120
                    },
                    {
                        "accident_type": "החלקה",
                        "count": 4
                    },
                    {
                        "accident_type": "התהפכות",
                        "count": 3
                    }
                ],
                "text": {
                    "title": "מספר תאונות לפי סוג"
                }
            },
            "meta": {
                "rank": 6,
                "information": "התפלגות תאונות לפי סוג התאונה במקטע, בפרק הזמן הנבחר. מוצגים 3 סוגי התאונות הנפוצים ביותר במקטע זה."
            }
        },

**Comment by ziv17** [comment]
BE work is completed.
