### ISSUE TITLE
The marker's title does not match the accident type within the popup

### ISSUE THREAD

**Issue by uda** [hasadna/anyway#213]
Example included

![uploads/d885b092-70bb-453d-99de-d98d87ad1f87/2015-04-21_18-52-34_001.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fd885b092-70bb-453d-99de-d98d87ad1f87%2F2015-04-21_18-52-34_001.png)

**Comment by danielhers** [comment]
Fixed by d73188e
