### ISSUE TITLE
Add rule to motorcycle_accidents_vs_all_accidents

### ISSUE THREAD

**Issue by atalyaalon** [hasadna/anyway#2132]
Only show widget if:
אם אחוז תאונות האופנוע במקטע גדול פי 2 או יותר מאחוז תאונות האופנוע בשאר הארץ ובנוסף היו לפחות 3 תאונות אופנוע קשות וקטלניות במקטע בתקופת הזמן
Hence:
segment motorcycle accidents % >= 2 * (country motorcycle accidents %)
AND
segment motorcycle accidents >= 3

use is_included function

See widget's visualization here: https://github.com/hasadna/anyway-newsflash-infographics/issues/541

@MichalOren FYI

**Comment by MichalOren** [comment]
Hi Shani
1. We need to update "information" tag for this widget description. kindly see if you can update it:
אחוז תאונות האופנוע הקשות והקטלניות במקטע הנבחר לעומת אחוז תאונות ממוצע במקטעי כביש אחרים בכל הארץ

2. There is a mismatch above between hebrew text and english syntax 5 vs 3 (should be 3)
