### ISSUE TITLE
Data loading is too slow

### ISSUE THREAD

**Issue by danielhers** [hasadna/anyway#217]
process.py takes too long to load all the data - around 3 days. There should be ways to make it run faster. The code can be refactored and optimized.

**Comment by eladkarakuli** [comment]
As describe in [SQLAlchemy  F&Q](http://docs.sqlalchemy.org/en/rel_0_8/faq.html#i-m-inserting-400-000-rows-with-the-orm-and-it-s-really-slow), for better performance, that is competitive with using the raw database API directly. We can use SQLAlchemy Core. I've implemented the changes(see [branch](https://github.com/eladkarakuli/anyway/tree/data-loading-is-too-slow-%23217)) with Core, now running process.py takes 14 seconds with demo data(47506 rows). I've asked permission to get the complete accidents file, for real data/time testing.

**Comment by danielhers** [comment]
Excellent! Granted. Please create a pull request when done :)
