### ISSUE TITLE
Modify title of Widget accident_count_by_accident_year

### ISSUE THREAD

**Issue by atalyaalon** [hasadna/anyway#2203]
Widget: accident_count_by_accident_year
modify title from 
"מספר תאונות לפי שנה, מחולקות לפי חומרה, במקטע ..."
to
"תאונות במקטע ..."
Relevant FE issue: https://github.com/hasadna/anyway-newsflash-infographics/issues/885

**Comment by atalyaalon** [comment]
We're using Flask Babel - [see here](https://github.com/hasadna/anyway/blob/dev/.github/ISSUE_TEMPLATE/localize_widget.md)

**Comment by ziv17** [comment]
@atalyaalon, @MichalOren 
in issue [646](https://github.com/hasadna/anyway-newsflash-infographics/issues/646#issuecomment-1011078117) title is different from issue [885](https://github.com/hasadna/anyway-newsflash-infographics/issues/885#issuecomment-1103862533)
Do we want to set title as it is written in issue issue definition above?

**Comment by atalyaalon** [comment]
@galraij what do you say?

**Comment by MichalOren** [comment]
Hi i think the title according to issue 646 describe the graph meaning, in a better way.
"תאונות לפי חומרה..."
