### ISSUE TITLE
[Bug] Airflow DAG is considered a SUCCESS

### ISSUE THREAD

**Issue by atalyaalon** [hasadna/anyway#2208]
**Describe the bug**
For some reason, this task of the DAG was considered as success even though it failed

https://airflow.anyway.co.il/log?dag_id=import-email-to-s3-and-update-data&task_id=cbs-import-from-s3&execution_date=2022-05-27T15%3A39%3A23.116949%2B00%3A00

**Comment by carmelp16** [comment]
@atalyaalon I suspect in [this](https://github.com/hasadna/anyway/blob/master/anyway/parsers/cbs/executor.py#L1156) line, we catch the exception but we don't re-raise it after the print

**Comment by carmelp16** [comment]
And here is the PR:
https://github.com/hasadna/anyway/pull/2209
