### ISSUE TITLE
"Go to my location" button doesn't seem to work on Safari

### ISSUE THREAD

**Issue by OmerSchechter** [hasadna/anyway#221]
The "Relocate me" button doesn't seem to work on Safari, currently checked on a Mac's "Snow Leopard" but presumably fails for Safari in general.
![screen shot 2015-04-27 at 9 27 52 pm](https://cloud.githubusercontent.com/assets/11275466/7354613/34515982-ed25-11e4-89b6-8a2df1503350.png)

**Comment by danielhers** [comment]
@galraij please confirm this also happens on your Safari.

**Comment by galraij** [comment]
It does...

Like the button is not functioning at all... Not urgent however.



‫ב-11 במאי 2015, בשעה 19:44, ‏‏Daniel Hershcovich ‏<notifications@github.com> כתב/ה:‬

**Comment by galraij** [comment]
It used to work by the way. Is it possible that Safari itself changed? Apple released a few updates recently. My version is the newest (8.0.6)

**Comment by danielhers** [comment]
Here's a version from 5 months ago: http://anyway-danielh.herokuapp.com/
Does it work there?

**Comment by danielhers** [comment]
@galraij please check to see if it works on my Heroku (see above)

**Comment by galraij** [comment]
I'm not near my computer today but on my iPad and iPhone (safari) it works fine on the current version



‫ב-16 במאי 2015, בשעה 19:53, ‏‏Daniel Hershcovich ‏<notifications@github.com> כתב/ה:‬

**Comment by danielhers** [comment]
So when you're at your computer please check and we can close this issue :)

**Comment by galraij** [comment]
On your version I don't even see the icon :)
