### ISSUE TITLE
[Bug] parsers.cbs.executor.create_tables fails frequently

### ISSUE THREAD

**Issue by tkalir** [hasadna/anyway#2229]
insertion to tables frequently fails. presumably because currently too much data is inserted at once.

**Comment by atalyaalon** [comment]
@tkalir awesome work. 
Next work - do you think we should make sure no "data downtime" when loading? Meaning having cache tables for CBS data?
@ziv17 what do you think?

**Comment by ziv17** [comment]
> @tkalir awesome work. Next work - do you think we should make sure no "data downtime" when loading? Meaning having cache tables for CBS data? @ziv17 what do you think?

I think we do. I.e. write to a temporary table, and then copy the temporary to the actual in a single transaction.

**Comment by tkalir** [comment]
@ziv17 @atalyaalon 
Are you sure there is still data downtime right now?
I think using Delete instead of Truncate shoud have solved that

**Comment by ziv17** [comment]
No, not sure.
What will happen when a query for the accidents table will arrive while it is being filled?

**Comment by tkalir** [comment]
The old data deletion and new data insertion all happen in a transaction together, so queries that run before the transaction is done are supposed to see the old data. The documentation for Truncate specifically says that other queries that run at the same time may see empty tables even before the transaction with Truncate is done, so I believe this is why we had this data downtime before. 
I did some experiment locally which seems to support it, but it would be better to make sure in production.

**Comment by ziv17** [comment]
I see. Do I believe it is what we need.
