### ISSUE TITLE
[Bug] widget: killed_and_injured_count_per_age_group - unknown 

### ISSUE THREAD

**Issue by MichalOren** [hasadna/anyway#2276]
**Describe the bug**
Unknown group display in the middle of the graph and should be last one
![image](https://user-images.githubusercontent.com/61007501/198373441-3d5313ce-5ccc-4757-8d73-35d403b73e0a.png)

neew to chage order in JSON
![image](https://user-images.githubusercontent.com/61007501/198373727-0282f437-23cf-4789-a9ec-68fe8cde1fee.png)

**To Reproduce**
Run 
https://anyway-infographics-staging.web.app/newsflash/128333

**Comment by elazarg** [comment]
IMO the displayed order should not depend on the order of the JSON.
