### ISSUE TITLE
Store users location and address searches

### ISSUE THREAD

**Issue by galraij** [hasadna/anyway#231]
Create a file that contains coordinates of where our users are (the ones who allowed GPS access) and the addresses that people searched using the search option.

Only the coordinates are important so let's keep the information stored as minimal and detached from the individual user as much as possible.

This will allow us at some point to create a new layer that will show "interest zones", and will help us a lot even before that to research and understand our audience.

**Comment by eladkarakuli** [comment]
Hey @galraij, is it important to label each location coordinate in the file as "user location" or "search location"?
@danielhers , why did you labelled the issue as frontend, do you see any work needed be done in end side?

**Comment by galraij** [comment]
Not necessarily, if that's easy to do it could be nice, if it takes more effort/time we can live with the coordinates alone.



‫ב-4 במאי 2015, בשעה 04:01, ‏‏Elad Karakuli ‏<notifications@github.com> כתב/ה:‬

**Comment by danielhers** [comment]
I suppose you need JS to gather this information and send it to the server.
That's why I labeled it as such.

**Comment by samuelregev** [comment]
we also going to need some kind of interface so i can access it from the android app

**Comment by galraij** [comment]
I suggest in the first step to just store it, later we can decide if and how to present it on the website + Android.
