### ISSUE TITLE
Firefox/chrome won't load the map in some cases

### ISSUE THREAD

**Issue by moshe742** [hasadna/anyway#232]
Hi,
i can't see the map when using firefox or chrome when on the computer at john bryce on some of the computers.
I pictured the screen, if need more info let me know and how to get it.
![anyway](https://cloud.githubusercontent.com/assets/1392908/7444615/179e8e4a-f194-11e4-93d4-500bfe4938d8.JPG)
we have a javascript error-
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead.

the errors of the CSS-
Expected declaration but found '*'.  Skipped to next declaration. app.min.css:10:50694
Expected declaration but found '*'.  Skipped to next declaration. app.min.css:10:50711
Expected declaration but found '*'.  Skipped to next declaration. app.min.css:10:50878
Expected declaration but found '*'.  Skipped to next declaration. app.min.css:10:50895
Expected declaration but found '*'.  Skipped to next declaration. app.min.css:10:50971
Expected declaration but found '*'.  Skipped to next declaration. app.min.css:10:50988
Expected declaration but found '*'.  Skipped to next declaration. app.min.css:10:51062
Expected declaration but found '*'.  Skipped to next declaration. app.min.css:10:51079
Unknown property '-moz-box-shadow'.  Declaration dropped. app.min.css:10:51216
Unknown property '-moz-border-radius'.  Declaration dropped. app.min.css:10:51341
Expected declaration but found '*'.  Skipped to next declaration. app.min.css:10:51474
Expected declaration but found '*'.  Skipped to next declaration. app.min.css:10:51547
Expected declaration but found '*'.  Skipped to next declaration. app.min.css:10:51707
Expected declaration but found '*'.  Skipped to next declaration. app.min.css:10:51723
Unknown property '-moz-border-radius'.  Declaration dropped. app.min.css:10:51905
Unknown property '-moz-border-radius-bottomleft'.  Declaration dropped. app.min.css:10:52336
Unknown property '-moz-border-radius-topleft'.  Declaration dropped. app.min.css:10:52367
Unknown property '-moz-border-radius-topright'.  Declaration dropped. app.min.css:10:52584
Unknown property '-moz-border-radius-bottomright'.  Declaration dropped. app.min.css:10:52619
Unknown property '-moz-border-radius-bottomleft'.  Declaration dropped. app.min.css:10:52836
Unknown property '-moz-border-radius-topleft'.  Declaration dropped. app.min.css:10:52867
Unknown property '-moz-border-radius-topright'.  Declaration dropped. app.min.css:10:53096
Unknown property '-moz-border-radius-bottomright'.  Declaration dropped. app.min.css:10:53131
Expected declaration but found '*'.  Skipped to next declaration. app.min.css:10:53347
Expected declaration but found '*'.  Skipped to next declaration. app.min.css:10:53381
Unknown property '-moz-box-shadow'.  Declaration dropped. app.min.css:10:53554
Expected declaration but found '*'.  Skipped to next declaration. app.min.css:10:53806
Expected declaration but found '*'.  Skipped to next declaration. app.min.css:10:53840
Expected declaration but found '*'.  Skipped to next declaration. app.min.css:10:53917
Expected declaration but found '*'.  Skipped to next declaration. app.min.css:10:53934
Expected declaration but found '*'.  Skipped to next declaration. app.min.css:10:53993
Expected declaration but found '*'.  Skipped to next declaration. app.min.css:10:54028
Unknown property '-moz-box-shadow'.  Declaration dropped. app.min.css:10:54216
Expected declaration but found '*'.  Skipped to next declaration. app.min.css:10:55286
Expected declaration but found '*'.  Skipped to next declaration. app.min.css:10:55302
Unknown property '-moz-border-radius'.  Declaration dropped. app.min.css:10:55413
Unknown property '-moz-border-radius'.  Declaration dropped. app.min.css:10:55582
Unknown property '-moz-border-radius'.  Declaration dropped. app.min.css:10:55709
Unknown property '-moz-border-radius'.  Declaration dropped. app.min.css:10:55843
Unknown property '-moz-border-radius'.  Declaration dropped. app.min.css:10:55976
Unknown property '-moz-border-radius'.  Declaration dropped. app.min.css:10:56217
Expected declaration but found '*'.  Skipped to next declaration. app.min.css:10:57451
Expected declaration but found '*'.  Skipped to next declaration. app.min.css:10:57489
Expected declaration but found '*'.  Skipped to next declaration. app.min.css:10:57599
Unknown property '-moz-border-radius'.  Declaration dropped. app.min.css:10:58117
Unknown property '-moz-border-radius'.  Declaration dropped. app.min.css:10:58481
Unknown property '-moz-border-radius'.  Declaration dropped. app.min.css:10:58773
Unknown property '-moz-border-radius-topright'.  Declaration dropped. app.min.css:10:58984
Unknown property '-moz-border-radius-topleft'.  Declaration dropped. app.min.css:10:59015
Unknown property '-moz-border-radius-bottomright'.  Declaration dropped. app.min.css:10:59226
Unknown property '-moz-border-radius-bottomleft'.  Declaration dropped. app.min.css:10:59260
Unknown property '-moz-border-radius'.  Declaration dropped. app.min.css:10:59506
Unknown property '-moz-border-radius'.  Declaration dropped. app.min.css:10:59615
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. app.min.css:10:60405
Expected declaration but found '*'.  Skipped to next declaration. app.min.css:10:60480
Unknown property '-moz-border-radius'.  Declaration dropped. app.min.css:10:60997
Unknown property '-moz-border-radius'.  Declaration dropped. app.min.css:10:61565
Expected declaration but found '*'.  Skipped to next declaration. app.min.css:10:61777
Unknown property '-moz-border-radius'.  Declaration dropped. app.min.css:10:61977
Expected declaration but found '*'.  Skipped to next declaration. app.min.css:10:62192
Expected declaration but found '*'.  Skipped to next declaration. app.min.css:10:62341
Expected declaration but found '*'.  Skipped to next declaration. app.min.css:10:62360
Error in parsing value for 'background-image'.  Declaration dropped. app.min.css:10:62583
Error in parsing value for 'background-image'.  Declaration dropped. app.min.css:10:62659
Error in parsing value for 'background-image'.  Declaration dropped. app.min.css:10:62718
Unknown property '-moz-border-radius'.  Declaration dropped. app.min.css:10:62908
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. app.min.css:10:62938
Unknown property '-moz-box-shadow'.  Declaration dropped. app.min.css:10:63109
Expected declaration but found '*'.  Skipped to next declaration. app.min.css:10:63752
Unknown property '-moz-border-radius'.  Declaration dropped. app.min.css:10:64632
Unknown property '-moz-border-radius'.  Declaration dropped. app.min.css:10:64794
Unknown property '-moz-border-radius'.  Declaration dropped. app.min.css:10:65160
Unknown property '-moz-box-shadow'.  Declaration dropped. app.min.css:10:65463
Unknown property '-moz-box-shadow'.  Declaration dropped. app.min.css:10:65748
Unknown property '-moz-box-shadow'.  Declaration dropped. app.min.css:10:66498
Expected declaration but found '*'.  Skipped to next declaration. app.min.css:10:66746
Error in parsing value for 'background-image'.  Declaration dropped. app.min.css:10:66789
Error in parsing value for 'background-image'.  Declaration dropped. app.min.css:10:66868
Error in parsing value for 'background-image'.  Declaration dropped. app.min.css:10:66930
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. app.min.css:10:67222
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. app.min.css:10:67338
Unknown property '-moz-box-shadow'.  Declaration dropped. app.min.css:10:67498
Expected declaration but found '*'.  Skipped to next declaration. app.min.css:10:67821
Expected end of value but found '\9 '.  Error in parsing value for 'background-color'.  Declaration dropped. app.min.css:10:67923
Unknown property '-moz-border-radius'.  Declaration dropped. app.min.css:10:68061
Unknown property '-moz-box-shadow'.  Declaration dropped. app.min.css:10:68143
Unknown property '-moz-border-radius'.  Declaration dropped. app.min.css:10:70001
Error in parsing value for 'background-image'.  Declaration dropped. app.min.css:10:70196
Error in parsing value for 'background-image'.  Declaration dropped. app.min.css:10:70269
Error in parsing value for 'background-image'.  Declaration dropped. app.min.css:10:70325
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. app.min.css:10:70468
Unknown property '-moz-box-shadow'.  Declaration dropped. app.min.css:10:71905
Unknown pseudo-class or pseudo-element '-ms-input-placeholder'.  Ruleset ignored due to bad selector. app.min.css:10:72241
Unknown pseudo-class or pseudo-element '-webkit-input-placeholder'.  Ruleset ignored due to bad selector. app.min.css:10:72320
Unknown property '-moz-box-shadow'.  Declaration dropped. app.min.css:10:72614
Expected declaration but found '*'.  Skipped to next declaration. app.min.css:10:72778
Error in parsing value for 'background-image'.  Declaration dropped. app.min.css:10:72821
Error in parsing value for 'background-image'.  Declaration dropped. app.min.css:10:72900
Error in parsing value for 'background-image'.  Declaration dropped. app.min.css:10:72962
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. app.min.css:10:73251
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. app.min.css:10:73367
Expected declaration but found '*'.  Skipped to next declaration. app.min.css:10:73640
Expected end of value but found '\9 '.  Error in parsing value for 'background-color'.  Declaration dropped. app.min.css:10:73755
Unknown property '-moz-border-radius'.  Declaration dropped. app.min.css:10:73888
Expected declaration but found '*'.  Skipped to next declaration. app.min.css:10:73947
Expected declaration but found '*'.  Skipped to next declaration. app.min.css:10:73988
Expected declaration but found '*'.  Skipped to next declaration. app.min.css:10:74147
Unknown property '-moz-border-radius'.  Declaration dropped. app.min.css:10:74238
Expected declaration but found '*'.  Skipped to next declaration. app.min.css:10:74261
Unknown property '-moz-box-shadow'.  Declaration dropped. app.min.css:10:74330
Unknown property '-moz-border-radius'.  Declaration dropped. app.min.css:10:75024
Unknown property '-moz-border-radius'.  Declaration dropped. app.min.css:10:75174
Expected declaration but found '*'.  Skipped to next declaration. app.min.css:10:75341
Unknown property '-moz-border-radius'.  Declaration dropped. app.min.css:10:75600
Expected declaration but found '*'.  Skipped to next declaration. app.min.css:10:75902
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. app.min.css:10:76169
Expected declaration but found '*'.  Skipped to next declaration. app.min.css:10:76367
Unknown property '-moz-border-radius'.  Declaration dropped. app.min.css:10:76434
Unknown property '-moz-box-shadow'.  Declaration dropped. app.min.css:10:76517
Unknown property '-moz-background-clip'.  Declaration dropped. app.min.css:10:76637
Unknown property '-moz-border-radius'.  Declaration dropped. app.min.css:10:77323
Expected declaration but found '*'.  Skipped to next declaration. app.min.css:10:77362
Unknown property '-moz-box-shadow'.  Declaration dropped. app.min.css:10:77423
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. app.min.css:10:77792
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. app.min.css:10:77858
Unknown property '-moz-border-radius'.  Declaration dropped. app.min.css:10:78163
Unknown property '-moz-border-radius'.  Declaration dropped. app.min.css:10:78937
Unknown property '-moz-box-shadow'.  Declaration dropped. app.min.css:10:79021
Unknown property '-moz-background-clip'.  Declaration dropped. app.min.css:10:79143
Unknown property '-moz-border-radius'.  Declaration dropped. app.min.css:10:79509
Expected declaration but found '*'.  Skipped to next declaration. app.min.css:10:80784
Unknown property '-moz-border-radius'.  Declaration dropped. app.min.css:10:81119
Unknown property '-moz-box-shadow'.  Declaration dropped. app.min.css:10:81204
Unknown property '-moz-box-shadow'.  Declaration dropped. app.min.css:10:81513
Unknown property '-moz-border-radius'.  Declaration dropped. app.min.css:10:81961
Unknown property '-moz-border-radius'.  Declaration dropped. app.min.css:10:82055
Error in parsing value for 'background-image'.  Declaration dropped. app.min.css:10:83485
Error in parsing value for 'background-image'.  Declaration dropped. app.min.css:10:83564
Error in parsing value for 'background-image'.  Declaration dropped. app.min.css:10:83626
Unknown property '-moz-border-radius'.  Declaration dropped. app.min.css:10:83797
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. app.min.css:10:83827
Unknown property '-moz-box-shadow'.  Declaration dropped. app.min.css:10:84002
Error in parsing value for 'background-image'.  Declaration dropped. app.min.css:10:84308
Error in parsing value for 'background-image'.  Declaration dropped. app.min.css:10:84387
Error in parsing value for 'background-image'.  Declaration dropped. app.min.css:10:84449
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. app.min.css:10:84583
Unknown property '-moz-box-shadow'.  Declaration dropped. app.min.css:10:84758
Unknown property '-moz-box-shadow'.  Declaration dropped. app.min.css:10:85150
Error in parsing value for 'background-image'.  Declaration dropped. app.min.css:10:85353
Error in parsing value for 'background-image'.  Declaration dropped. app.min.css:10:85630
Error in parsing value for 'background-image'.  Declaration dropped. app.min.css:10:86005
Unknown property '-moz-background-size'.  Declaration dropped. app.min.css:10:86407
Error in parsing value for 'background-image'.  Declaration dropped. app.min.css:10:86910
Error in parsing value for 'background-image'.  Declaration dropped. app.min.css:10:86989
Error in parsing value for 'background-image'.  Declaration dropped. app.min.css:10:87051
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. app.min.css:10:87185
Error in parsing value for 'background-image'.  Declaration dropped. app.min.css:10:87405
Error in parsing value for 'background-image'.  Declaration dropped. app.min.css:10:87682
Error in parsing value for 'background-image'.  Declaration dropped. app.min.css:10:88057
Error in parsing value for 'background-image'.  Declaration dropped. app.min.css:10:88552
Error in parsing value for 'background-image'.  Declaration dropped. app.min.css:10:88631
Error in parsing value for 'background-image'.  Declaration dropped. app.min.css:10:88693
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. app.min.css:10:88827
Error in parsing value for 'background-image'.  Declaration dropped. app.min.css:10:89049
Error in parsing value for 'background-image'.  Declaration dropped. app.min.css:10:89326
Error in parsing value for 'background-image'.  Declaration dropped. app.min.css:10:89701
Error in parsing value for 'background-image'.  Declaration dropped. app.min.css:10:90190
Error in parsing value for 'background-image'.  Declaration dropped. app.min.css:10:90269
Error in parsing value for 'background-image'.  Declaration dropped. app.min.css:10:90331
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. app.min.css:10:90465
Error in parsing value for 'background-image'.  Declaration dropped. app.min.css:10:90681
Error in parsing value for 'background-image'.  Declaration dropped. app.min.css:10:90958
Error in parsing value for 'background-image'.  Declaration dropped. app.min.css:10:91333
Error in parsing value for 'background-image'.  Declaration dropped. app.min.css:10:91828
Error in parsing value for 'background-image'.  Declaration dropped. app.min.css:10:91907
Error in parsing value for 'background-image'.  Declaration dropped. app.min.css:10:91969
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. app.min.css:10:92103
Error in parsing value for 'background-image'.  Declaration dropped. app.min.css:10:92325
Error in parsing value for 'background-image'.  Declaration dropped. app.min.css:10:92602
Error in parsing value for 'background-image'.  Declaration dropped. app.min.css:10:92977
Unknown property '-moz-border-radius'.  Declaration dropped. app.min.css:10:93459
Unknown property '-moz-border-radius'.  Declaration dropped. app.min.css:10:94634
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. app.min.css:10:94677
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. app.min.css:10:94814
Unknown property '-moz-border-radius'.  Declaration dropped. app.min.css:10:95199
Unknown property '-moz-border-radius'.  Declaration dropped. app.min.css:10:98104
Unknown property '-moz-border-radius'.  Declaration dropped. app.min.css:10:98497
Unknown property '-moz-border-radius'.  Declaration dropped. app.min.css:10:99564
Unknown property '-moz-border-radius'.  Declaration dropped. app.min.css:10:99874
Error in parsing value for 'background-image'.  Declaration dropped. app.min.css:10:100048
Error in parsing value for 'background-image'.  Declaration dropped. app.min.css:10:100100
Error in parsing value for 'background-image'.  Declaration dropped. app.min.css:10:100173
Error in parsing value for 'background-image'.  Declaration dropped. app.min.css:10:100229
Expected color but found 'top'.  Error in parsing value for 'background-image'.  Declaration dropped. app.min.css:10:100296
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. app.min.css:10:100345
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. app.min.css:10:100550
Unknown property '-moz-box-shadow'.  Declaration dropped. app.min.css:10:100788
Unknown property 'boxShadow'.  Declaration dropped. www.anyway.co.il
Unknown property '-moz-border-radius'.  Declaration dropped. www.anyway.co.il:8:20
Error in parsing value for 'background'.  Declaration dropped. www.anyway.co.il

**Comment by danielhers** [comment]
Maybe they have a firewall blocking Google Maps.
Have you tried http://maps.google.com ?

**Comment by moshe742** [comment]
google maps works just fine, but according to the teacher the internet is
going through a proxy, what else should i look for?

On Sun, May 3, 2015 at 1:14 PM, Daniel Hershcovich <notifications@github.com

**Comment by danielhers** [comment]
Try other apps with Google Maps, e.g. http://jsfiddle.net/B3a86/2
Try other embedded maps, e.g. in http://opentaba.info and http://www.vzv.nyc
