### ISSUE TITLE
Add "notify on new features" button to context menu

### ISSUE THREAD

**Issue by galraij** [hasadna/anyway#233]
Today right click on the map opens an incomplete "open new discussion" popup. Instead, should be a popup that lets the user send us his email address, so we have indication how many are interested in this feature and also- lets us notify them when it works and keep in touch with them.

**Comment by danielhers** [comment]
@aviklai see #155: the popup now opens Disqus. There are still improvements to do but I'm not sure it's worthwhile to implement the subscription. @galraij what do you think?

**Comment by galraij** [comment]
WOW, Brilliant! looks really good! Thanks Daniel.

First, I commented but it didn’t create a new marker on the map (we do have an icon for discussion). I guess you’ll make it happen soon.

Second, I would add in the menu after “Create new discussion” the option “notify me when new features are available” and keep the subscription there. If a user invested the time to right click he might be someone we want to keep in touch with.

**Comment by danielhers** [comment]
This can be implemented by adding another item to the context menu in app.js, and another modal (like discussion-dialog) that will send a request to the server when submitted.

**Comment by aviklai** [comment]
That's what I did. I commented the non-working marker modal and put instead the open-discussion that enables a user to register to get an update when the feature will be available.

**Comment by njenia** [comment]
I think that adding the "new features" context menu item is wrong. This action should be put as a button on the topbar or something, next to the About button. The context menu is (as its name suggests) in the context of the click position. Putting a static non-position-related button is weird..
And another thing: the term תכונות is a bit weird. I didn't understand what it was at first, and it took me a minute to understand the real meaning is updates on new features.. Maybe we should change it to פיצ'רים
What do you think?

**Comment by aviklai** [comment]
I agree with you. And about the text, maybe something like רוצה לקבל עדכונים?
because this users list can be used no only for features.

**Comment by aviklai** [comment]
@galraij Gal, what do you think?

**Comment by galraij** [comment]
Good idea- write ״לעידכונים״



‫ב-22 ביוני 2015, בשעה 18:45, ‏‏Avi Klaiman ‏<notifications@github.com> כתב/ה:‬
