### ISSUE TITLE
Change the text of the guided tour

### ISSUE THREAD

**Issue by galraij** [hasadna/anyway#239]
1. Use ANYWAY in capital letters
2. Change the text:

Step 1:
ברוכים הבאים ל-ANYWAY, על גבי המפה ניתן לראות היכן התרחשו תאונות דרכים עם נפגעים.

Step 2:
באמצעות התפריט ניתן לבחור טווח תאריכים ולהציג תאונות מרמות חומרה שונות.

**Comment by agamaloni** [comment]
Working on it :)

**Comment by galraij** [comment]
Hi @agamaloni , can you please send me an email so I can add you to our mailing list?

**Comment by agamaloni** [comment]
Hi gal,

this my mail

thanks,
agam
