### ISSUE TITLE
Multiple requests for markes on app loading

### ISSUE THREAD

**Issue by eladkarakuli** [hasadna/anyway#245]
There are 8 requests for markers when the app is loading:

    "GET /markers?ne_lat=32.07441697068722&ne_lng=34.80294092162626&sw_lat=32.06612544135497&sw_lng=34.785549478373696&zoom=17&thin_markers=false&start_date=1356991200&end_date=1388527200&show_fatal=1&show_severe=1&show_light=1&show_inaccurate=0 HTTP/1.1" 200

I suspect, it's about the ```app.model.set```, called at ```navigateSelectedMarker```, when every set, initialize each property and activates the bindings, then it's fetching the markers unneeded.

**Comment by OmerSchechter** [comment]
What do you mean by `navigateSelectedMarker`?

It seems to me like the "idle" event of the map is being fired-up a few times(which calls `fetchMarkers()`), plus `setCenterWithMarker` also calls `fetchMarkers()`, plus `this.model.bind("change:dateRange", this.reloadMarkers, this);` also being fired-up for some reason and calls `fetchMarkers()` as well, and maybe others as well.

Basically, we do want each of them to run and call `fetchMarkers()` on it's own, but when they all go-off on first load it's not reasonable to make so many GET requests.

I think that an "ad hoc" solution is required here.

I think i'm gonna create a variable, something like:
```javascript
this.firstLoad = true;
```
and set a TimeOut for a second or two to switch it to false.
And by using it in the problematic functions, we'll be able to take it down to 1 GET request.

**Comment by danielhers** [comment]
@OmerSchechter is this fixed by your commits?

**Comment by OmerSchechter** [comment]
Yes.
