### ISSUE TITLE
R*Tree Module for better quering performance

### ISSUE THREAD

**Issue by eladkarakuli** [hasadna/anyway#246]
An R-Tree is a special index that is designed for doing range queries.
Use the module to index the queries of markers and highlights.

**Comment by eladkarakuli** [comment]
This should also help with server side clustering (#190) performance.

**Comment by danielhers** [comment]
@eladkarakuli how is it going?

**Comment by danielhers** [comment]
@eladkarakuli @simonaho should someone else take over this or should we close the issue?
