### ISSUE TITLE
Show discussion markers on the map

### ISSUE THREAD

**Issue by danielhers** [hasadna/anyway#249]
Depends on #247 and #248.
When opening the map, like the request to show the accident markers in the bounding box, we should get all the discussion markers in the same area, to display them on the map.

**Comment by galraij** [comment]
Relevant only to zoom levels before aggregation starts

**Comment by danielhers** [comment]
Need to send new markers to the server so they're saved in the DB, and send them to the client when fetching markers.

**Comment by danielhers** [comment]
Code worked in localhost but failed on production (SQL error where the discussions.type column was not found).
f38d6e2 commented out code to load discussions from DB and send to client, so currently only accidents are sent.
Need to uncomment and fix the SQL problem.
