### ISSUE TITLE
Use PostGIS for faster queries

### ISSUE THREAD

**Issue by danielhers** [hasadna/anyway#257]
https://devcenter.heroku.com/articles/postgis
And geoalchemy: https://geoalchemy-2.readthedocs.org/en/latest/orm_tutorial.html#spatial-relationship

**Comment by njenia** [comment]
But the heroku docs state that it's only available with Django or Rails..

**Comment by yosiat** [comment]
@njenia PostGIS is a feature that is implemented at the database level (postgres), the heroku docs shows you an example for django/rails, but this feature could be used with any other frameworks.

**Comment by eladkarakuli** [comment]
I should point out that #246, is this issue, only on SQLite. 
I didn't knew that the prod runs PostgreSQL, so I implemented the faster queries feature for SQLite, only to find out I need to implement it for Postgre, and PostGIS as well.
I think this is a bit of a problem, and code confusion, when this and future implementation for DB, requiring implementations and tests for two different DBs.

There for we should inspire to use only one DB type at both the environments, after a quick look at SQLite for Heruko, it seems best to change the dev environment DB to PostgreSQL.
What's your opinion on this matter?
