### ISSUE TITLE
Improve google analytics

### ISSUE THREAD

**Issue by galraij** [hasadna/anyway#260]
Since we have only one page, we can investigate which buttons are being clicked using the information described here: https://support.google.com/analytics/answer/2558867/?hl=en&utm_id=ad&authuser=3

If it's possible to know which individual markers (or at least discussion markers) users clicked that's superb!

**Comment by danielhers** [comment]
This just required adding

    ga('require', 'linkid', 'linkid.js');

In `templates/index.html`, between the `ga` calls.
I don't know if we can track clicks on markers, though, because there's no way I know of to get their element ids.
