### ISSUE TITLE
Clicking a link to specific discussion pops an "illegal discussion" error

### ISSUE THREAD

**Issue by omerxx** [hasadna/anyway#261]
Each discussion has a lower field of 'more from anyway': `עוד באתר anyway`
Clicking a specific discussion (title or grid point) moves to it but pops a top right hand side error:
`דיון לא חוקי`

Moreover, sometimes it loads when the green marker of the current location is hiding the discussion icon. (Different issue?)

**Comment by danielhers** [comment]
Please give an example. I think it's only for the first discussions that were added, before I changed the discussion URL format.

As for the green marker, yes, that's because the discussion URL points to the location of the marker, and when loading the app with a specific location, the green marker is added.
It can be fixed to not show the green marker if the page was loaded from a discussion link, but again, since only the old discussions have this format, I'm not sure it's worthwhile.

**Comment by omerxx** [comment]
Understood.. old ones are the only ones I see there. Maybe it's worth deleting every discussion prior to the fix date?

![image](https://cloud.githubusercontent.com/assets/12237955/7746274/a2814560-ffb9-11e4-881f-30f4c64ee5a3.png)

**Comment by danielhers** [comment]
I edited the old discussions using my Disqus admin powers. Should be fine now.

**Comment by omerxx** [comment]
Discussions that have been deleted still exist as a link from the optional section in disqus, trying to click them gives an error:
![image](https://cloud.githubusercontent.com/assets/12237955/7769939/57cd738a-0091-11e5-9530-ee9384c5a201.png)


There is still one that cannot be found:

![image](https://cloud.githubusercontent.com/assets/12237955/7769920/39789130-0091-11e5-9ced-0c44b87b3ea2.png)

**Comment by danielhers** [comment]
You can restore it suing the load_discussions.py script I wrote (it's in
git), just set your DATABASE_URL before to the URL I'm sending you by email
by doing 'export DATABASE_URL=' and the URL in single quotes.

**Comment by samuelregev** [comment]
did discussion id changed?
for example - this discussion marker:
http://oway.org.il/?start_date=2013-01-01&end_date=2014-01-01&show_fatal=1&show_severe=1&show_light=1&show_inaccurate=0&zoom=20&lat=31.74582429075062&lon=35.23056580978697

I commented there few days ago, later comment disappeared. when I re-comment the discussion got different id
sea first comment:
https://disqus.com/home/discussion/anyway-feedback/317457974525944_3523064103187721/

second comment:
https://disqus.com/home/discussion/anyway-feedback/317457974525944_3523064103187721_34/

notice the url different(title is the same)

**Comment by samuelregev** [comment]
I might found the reason, in the json returned for discussion marker identifier now have '\n' at the end which I'm certain that wasn't there before

"identifier": "(31.7457974525944, 35.23064103187721)\n"

http://oway.org.il/markers?ne_lat=31.74812799660888&ne_lng=35.23191764313049&sw_lat=31.743036958134315&sw_lng=35.226499580920404&zoom=17&thin_markers=false&start_date=1356991200&end_date=1388527200&show_fatal=1&show_severe=1&show_light=1&show_inaccurate=0

**Comment by danielhers** [comment]
That's probably because of my load script...

**Comment by danielhers** [comment]
Still not sure where this newline comes from - need to further investigate.

**Comment by omerxx** [comment]
@danielhers  the 'discussion not found' error still persists..

**Comment by danielhers** [comment]
Still happens?

**Comment by omerxx** [comment]
@galraij ?

**Comment by galraij** [comment]
Can you elaborate on that? I think I didn't understand the problem/never saw it happening 



‫ב-1 ביולי 2015, בשעה 00:26, ‏‏omerxx ‏<notifications@github.com> כתב/ה:‬

**Comment by omerxx** [comment]
Thought you knew it.

Anyway I can't reproduce it.. I think this can be closed
