### ISSUE TITLE
Tour step 3 dialog is over streched

### ISSUE THREAD

**Issue by omerxx** [hasadna/anyway#262]
Getting to the third step of the tour `המקום שחיפשתם` I noticed the window extends it's basic design:

![image](https://cloud.githubusercontent.com/assets/12237955/7746192/25ef2d96-ffb9-11e4-9274-76d0ad0c72a0.png)
VS:
![image](https://cloud.githubusercontent.com/assets/12237955/7746205/37243fb6-ffb9-11e4-99aa-e6d41d3d4c86.png)

**Comment by danielhers** [comment]
@agamaloni

**Comment by omerxx** [comment]
While at it I think it would be nice adding a last step with a greeting notifying that the tour is over

**Comment by samuelregev** [comment]
Maybe also add a description about opening a discussion

**Comment by agamaloni** [comment]
thanks @omerxx  change back for cleaner view and resize .popover

**Comment by agamaloni** [comment]
can add more steps,
now i get hard time to find inside the code the easy way for setting up the current date
any idea?

**Comment by danielhers** [comment]
You need to update the daterangepicker's startDate and endDate, and then notify it: https://github.com/hasadna/anyway/blob/master/static/js/app.js#L484

**Comment by omerxx** [comment]
Hi @agamaloni 
The tour step is still stretched, I tried to modify it locally but I can't see the tour here (do you know why..?) 
plus, why is this specific step at `app.js` and not in `tour` ?

**Comment by agamaloni** [comment]
Hi @omerxx ,
yes, 
For locate step over the map i go out from the tour and popup an infoWindow i know it not look exactly like the different steps.. do you know how to modify specific infoWindow ? (i will figure it out) 
that was my best solution for dealing with pointing on exactly spot over the map.
according to that logic step 3 set inside setCenterWithMarker of app.js
to catch the location after find place "this.locationMarker" and open infowindow.open(this.map, location);
