### ISSUE TITLE
Separate marker id from provider code

### ISSUE THREAD

**Issue by danielhers** [hasadna/anyway#279]
Loading the complete data on a new DB gives:

    static/data/lms/Accidents Type 3/H20121161: (DataError) integer out of range

@eladkarakuli

**Comment by danielhers** [comment]
Of course, it's because it's constructing the id by joining the provider code ('1') with the id from the CSV, giving a very large number.
We could keep the id from the CSV as a separate column or something, and use simple autoincrementing integers for the real id.

**Comment by omerxx** [comment]
What's the status here?
@galraij wanted to have the provider code pulled separately from the accident id for further use.

**Comment by danielhers** [comment]
Right, so the request is to separate the id from the provider code.
