### ISSUE TITLE
Creating new discussion doesn't return the new discussion marker

### ISSUE THREAD

**Issue by samuelregev** [hasadna/anyway#283]
At first, when I sent post request to '/discussion' I received back the new discussion marker as json.
after this commit 
https://github.com/hasadna/anyway/commit/3cd982784e8cdc755dbe5762c4e772005fa70fd2#diff-5bc02cefb3ea9e27f1a6776eabd1935dL140

the discussion is created but no response being sent back to the client, only new requests to '/markers' gets the new discussion marker

**Comment by eladkarakuli** [comment]
Hi @samuelregev, I did a post request, and got the object back as json.
from the console:

> $.post("discussion", JSON.stringify({
                    "latitude"  : "32.01936",
                    "longitude" : "34.78287829999997",
                    "identifier": "abcd",
                    "title"     : "test"
                }), function(data, textStatus, jqXHR) { console.log(data); });

 > Object { readyState: 1, setRequestHeader: .ajax/x.setRequestHeader(), getAllResponseHeaders: .ajax/x.getAllResponseHeaders(), getResponseHeader: .ajax/x.getResponseHeader(), overrideMimeType: .ajax/x.overrideMimeType(), abort: .ajax/x.abort(), state: .Deferred/d.state(), always: .Deferred/d.always(), then: .Deferred/d.then(), promise: .Deferred/d.promise(), 8 more… }

> Object { created: "2015-05-28T03:13:36.260081", id: "1", identifier: "abcd", latitude: 32.01936, longitude: 34.78287829999997, title: "test", type: 2 }

Are you sure the creation of the discussion was succeeded? if it was not, you'll get an empty response and a log message at server side.

**Comment by samuelregev** [comment]
That's weird,  I'm trying the same request from an outside request maker like https://www.hurl.it/
And the response body is always empty (This is what i do in the android app, it worked before)

I'm sure the the discussion is created, after returning empty request body when I'm refreshing the marker list it's there.
Maybe I need to add some headers to the request?
@eladkarakuli can you try sending this request from there and tell me what you get?

Thanks

**Comment by samuelregev** [comment]
It's still doesn't work. but i handling it differently in the android app now. so this issue is not needed anymore
