### ISSUE TITLE
Delete old disqus threads

### ISSUE THREAD

**Issue by samuelregev** [hasadna/anyway#284]
In disqus thread list appears many discussion that was created for testing, with old address (localhost, 127.0.0.1 etc.) as you can see here:
https://disqus.com/home/forum/anyway-feedback/

The only way to delete disqus thread is their api
https://disqus.com/api/docs/threads/remove/

We need to request API key and preform that.
https://disqus.com/api/applications/

**Comment by omerxx** [comment]
Were deleted on #261

**Comment by samuelregev** [comment]
I'm not talking about the discussion list in our database, I'm talking about the list of discussions in Disqus system
go to https://disqus.com/home/forum/anyway-feedback/ and scroll all the way down, notice the some of the links pointing to localhost and so on.

Those discussion appear to everyone in the box under every discussion so we need to delete them
