### ISSUE TITLE
Replace the multiple marker icon

### ISSUE THREAD

**Issue by galraij** [hasadna/anyway#299]
This:
![anyway_-_ _ _](https://cloud.githubusercontent.com/assets/3368312/8019229/6fbf87be-0c4c-11e5-917b-1127b1ee73dc.jpg)
Should be replaced with:
![anyway_-_ _ _](https://cloud.githubusercontent.com/assets/3368312/8019231/94f5b8b4-0c4c-11e5-8a4d-895848f6756a.jpg)

**Comment by OmerSchechter** [comment]
@galraij It's not as simple as I thought.. It can be done though.
Let me know when we get the new icons.

**Comment by galraij** [comment]
Don't wait for it, use one of the normal aggregation markers and when we have it we can replace... Hopefully soon.



‫ב-11 ביוני 2015, בשעה 16:49, ‏‏OmerSchechter ‏<notifications@github.com> כתב/ה:‬

**Comment by omerxx** [comment]
Maybe ask @LironRS to create a css for that too

**Comment by galraij** [comment]
Yep. Use the CSS version of the aggregation that @LironRS made. If possible Liron, try to create an icon that looks like this (or any other way that combines aggregation + exact location):
![untitled-1___100___cluster_3_copy__rgb_8___](https://cloud.githubusercontent.com/assets/3368312/8634399/0488951a-2800-11e5-82b4-f063831880bd.png)
