### ISSUE TITLE
Add the "involved" data to the accident marker

### ISSUE THREAD

**Issue by galraij** [hasadna/anyway#301]
info about the involved people in an accident is available in the: H********InvData.csv file, and should be connected with the specific accident using the identical ID.

**Comment by omerxx** [comment]
@aviklai Thought I could assign myself to help you..
Let me know when you want to start working on this

**Comment by aviklai** [comment]
@omerxx I already started. Do you want to talk today? we can discuss on the best way to do it and we will be able to do issue #302 the same way.

**Comment by omerxx** [comment]
I'll only be available late but sure sounds good. We'll continue tomorrow



ב-7 ביונ 2015, בשעה 17:57, Avi Klaiman <notifications@github.com> כתב/ה:

**Comment by omerxx** [comment]
Working on the client side...
