### ISSUE TITLE
Accident marker title presented as a story

### ISSUE THREAD

**Issue by galraij** [hasadna/anyway#304]
Instead of presenting only the accident type in the title, tell this story:

תאונה קשה מסוג התהפכות 100 מטרים דרומית לצומת השרון ביום ראשון בשעה 14:00

**Comment by omerxx** [comment]
Current state (based on #295) looks like this:
![image](https://cloud.githubusercontent.com/assets/12237955/8020774/373d5b22-0c8e-11e5-8647-dcc2e6420929.png)

@galraij, should `תאריך` and the junction on the bottom still be part of the marker's details?

**Comment by galraij** [comment]
Looks beautiful! Date and junction at the bottom can be deleted, it's enough to see it one time.

**Comment by omerxx** [comment]
Cool.
I also want to add some light coloring.
For example having the severity change color according to its level 
What do think?
Any other ideas?


ב-7 ביונ 2015, בשעה 00:41, Gal Raij <notifications@github.com> כתב/ה:
