### ISSUE TITLE
Working with branches in Anyway

### ISSUE THREAD

**Issue by omerxx** [hasadna/anyway#328]
We've been working with `dev` for a couple of weeks and there's a mess.
No one knows what branch should we work with and how should we keep our lost features.
@njenia has created `dev2` which is a branch that has both `dev` and `master` merged.
In my opinion we should have **all standing pull requests merged** to `dev2` as well. 
Then, once it is merged / replaced with `master` successfully, we should keep opening pull requests.

Right know, not everyone are updated, we have 3 different branches that receive requests.
If we keep this way we're going to face a much bigger problem..

Other opinions?
@galraij @OmerSchechter @aviklai @danielhers

**Comment by danielhers** [comment]
All changes should be in dev, and changes proven stable should be merged to
master too. Why is that not the case?

**Comment by omerxx** [comment]
Since dev was opened, some pull requests kept being opened to the master branch and even merged in the hackaton 3 weeks ago.
The dev branch is way ahead now but some features exist only in the master.

**Comment by OmerSchechter** [comment]
@danielhers @omerxx What happened was that some of us didn't know of the existence of the `dev` branch and obviously kept working on `master`, and pushing to it.
And then, some of those features were merged to `master` and created a situation in which `master` is ahead of `dev` in some terms, and `dev` is ahead of `master` in others(like it should be).
But I believe we solved it last Monday, by rebasing `dev` with `master`.

So the current situation is: everything that we have in `master` is also in `dev`, everyone should be working on `dev` and `dev` should always be ahead of `master`

##### Now, 2 more thing:

* We have `dev` and `dev2`. The reason for that is, when @njenia rebased `dev` with master, we wanted to have a backup for it, so we created a duplication of `dev`(i.e. `dev2`) and rebased it with `master`.
It went well, so now you can either rebase `dev` also, or get rid of it and work with `dev2`. Just make sure everyone know which one got chosen, so we wont have "`dev`/`master` crisis 2".

* I suppose people have local branches for features they are working on, which are based with `master`. Those should be rebased with `dev`.

**Comment by omerxx** [comment]
I'm pretty sure `dev` hasn't got all `master`'s features. 
I know @njenia has created `dev2` to test the option of merging both. If you're positive about it being stable then we can keep working on `dev` and rebasing it to master in the future with no worries.

**Comment by OmerSchechter** [comment]
As I mentioned here:

>We have dev and dev2. The reason for that is, when @njenia rebased dev with master, we wanted to have a backup for it, so we created a duplication of dev(i.e. dev2) and rebased it with master.
It went well, so now you can either rebase dev also, or get rid of it and work with dev2. Just make sure everyone know which one got chosen, so we wont have "dev/master crisis 2".

`dev2` was created to check if rebasing it with `master` will go smoothly, it did.
So, we can either rebase `dev` as well(with `master`), or get rid of `dev` and work with `dev2`(and presumably change it's name).
What do you mean by 'rebasing it in the future'?

And you're right, `dev` hasn't got all of `master`'s features yet, it will, once we rebase it with master(provided this is the way we'll choose to go).

*p.s. When I referred to `dev` earlier I meant the Developing branch in general, which currently includes `dev` + `dev2.`*

**Comment by danielhers** [comment]
I'm going to merge `master` into `dev`, and then we keep working on `dev`.
You don't rebase published branches, since it causes problems for clones. Only local branches should be rebased, generally.

**Comment by danielhers** [comment]
I merged `master` to `dev`, so now the pull requests that have been merged to `master` can be closed. You can see that they will have an empty diff.
From now on, pull requests should be made to `dev`, and we will merge them together into `master` when proven stable.
