### ISSUE TITLE
Safari locates marker scroll-bar on the right on top of the text

### ISSUE THREAD

**Issue by omerxx** [hasadna/anyway#329]
Don't know whether the scroll bar side position is a result of localization settings of either of my browsers but when it's located on the right it shadows the text.

I guess the simplest solution would be to indent text (and future accordion one tab left)

![image](https://cloud.githubusercontent.com/assets/12237955/8376192/ea83ba72-1c0c-11e5-8275-82e1cc1b683d.png)

**Comment by omerxx** [comment]
@OmerSchechter any ideas?

**Comment by danielhers** [comment]
@omerxx still a problem?

**Comment by omerxx** [comment]
Nope, closing.
