### ISSUE TITLE
Add accident type filter option to the menu

### ISSUE THREAD

**Issue by galraij** [hasadna/anyway#330]
Allow the user to choose which types of accidents to see.
Default should be ALL CHECKED.

The codes mentioned in the mockup are described in AccCodebook.pdf

![sort_by_kind_psd___100___layer_4__rgb_8__](https://cloud.githubusercontent.com/assets/3368312/8388075/0035692e-1c67-11e5-8512-bf7996ee5372.jpg)

@omerxx and @LironRS you might wanna take a look

**Comment by omerxx** [comment]
We'll do it, it's not to big of an effort. But only once all previous enhancements are merged... 
Otherwise we'll mess up things in the same files with different code.
If @LironRS can do the UI, I'll add the server side requirements.

**Comment by LironRS** [comment]
@omerxx, as I understood from Gal last Monday, he wants us to add all of the sorting options in the sidebar, just with the accordion effect @OmerSchechter was working on. I think UI-wise it's not best practice but it's much better than the popup selection window.

**Comment by LironRS** [comment]
@galraij,  if we're on it.. please open two new "issues" for the cluster and markers design update (from photo icons to css) so we can follow up on their progress.

**Comment by danielhers** [comment]
The lists of checkboxes should be expandable (and collapsed on app load), to avoid clutter

**Comment by omerxx** [comment]
Done in #412
