### ISSUE TITLE
Add time filter option to the menu

### ISSUE THREAD

**Issue by galraij** [hasadna/anyway#331]
Add Day/Night/Holiday and day picker options.
by default all options should be checked.

See the mockup for more details:

![sort_by_time_psd___100___ _ __rgb_8__](https://cloud.githubusercontent.com/assets/3368312/8388925/8925aadc-1c71-11e5-9a6a-55bb21a851c5.jpg)

@omerxx 
@LironRS

**Comment by omerxx** [comment]
@OmerSchechter

**Comment by LironRS** [comment]
@omerxx -  let me know once you have the "server side" ready and I'll set it up

**Comment by omerxx** [comment]
Done in #412
