### ISSUE TITLE
Add weather filter option to the menu

### ISSUE THREAD

**Issue by galraij** [hasadna/anyway#332]
Let the user choose kind of weather. 
by default all options should be checked.

See the Mockup below for more details.

![sort_by_weather_psd___100___layer_4__rgb_8__](https://cloud.githubusercontent.com/assets/3368312/8389115/39dc17ec-1c74-11e5-928a-b658fbe89c28.jpg)

@omerxx 
@LironRS

**Comment by danielhers** [comment]
As for #330, the filter lists should be expandable

**Comment by omerxx** [comment]
Done in #412
