### ISSUE TITLE
Copy current display link to clip board is not functional

### ISSUE THREAD

**Issue by omerxx** [hasadna/anyway#349]
Clicking `קישור לתצוגה נוכחית` --> then either of the `העתק` buttons copy nothing to clip board.

(I'm using chrome/safari on mac)

**Comment by LironRS** [comment]
Talked with @omerxx, I think the common practice is to select all and not copy on behalf of an end user (causes issues on several browsers and considered intrusive). Perhaps we should change the label on the buttons.. @galraij, what do you think?

**Comment by danielhers** [comment]
I think the label should be changed to what the button actually does.

**Comment by omerxx** [comment]
It was meant to copy to clipboard - it was given the html class name `btn btn-default js-btn-copytoclipboard`

I'll change the button text
