### ISSUE TITLE
batch_size parameter in process.py is unused

### ISSUE THREAD

**Issue by danielhers** [hasadna/anyway#355]
The parameter should control how many accidents are committed at once.

**Comment by omerxx** [comment]
I used `batch_size` in a function I built to commit everything in batches.
process.py performance seems worse now, from ~6:00 it grew to ~8:00 (complete csv's)
Is there something else I can use?

**Comment by danielhers** [comment]
Batches should be especially necessary when loading over the network, but
it's not a good sign if it increases the runtime locally by 25%. Is that
when you don't supply the parameter?

**Comment by omerxx** [comment]
I didn't give the batch size, it loaded the default (100) and used it.
That's what I used:
```
def batch_to_datastore(datalist, batch_size, table):
    batch_list = []
    i = 0
    for data in datalist:
        if i < batch_size:
            batch_list.append(data)
            i += 1
        else:
            db.session.execute(table.__table__.insert(), batch_list)
            db.session.commit()
            i = 0
            batch_list = []
```

**Comment by danielhers** [comment]
It's better to split the list into chunks, I think:
http://stackoverflow.com/a/434328/223267

**Comment by omerxx** [comment]
That's roughly the same, took ~8:00 minutes:

```
def batch_to_datastore(datalist, batch_size, table):
    batch_list = (datalist[pos:pos + batch_size] for pos in xrange(0, len(datalist), batch_size))
    for chunk in batch_list:
        db.session.execute(table.__table__.insert(), chunk)
        db.session.commit()
```

**Comment by danielhers** [comment]
Then the default should be without batches. Need to check how it affects
loading over the network.

**Comment by omerxx** [comment]
Chunk sizes and performance in db deployment:

100 - 8:00 min
1000 - 6:50 min
5000 - 6:30 min
10000 - 6:40 min

**Comment by omerxx** [comment]
Close this issue for now?

**Comment by danielhers** [comment]
Ok
