### ISSUE TITLE
Keep years.js out of version control

### ISSUE THREAD

**Issue by danielhers** [hasadna/anyway#356]
`statis/js/years.js` is generated when running `process.py`. Therefore, it should be ignored by Git and kept in a special location.

**Comment by danielhers** [comment]
Also, since we can run `process.py` on one computer with a `DATABASE_URL` that corresponds to another computer's database (e.g. the production server), and `years.js` is created on the computer where the script is run and not on the database, there is a problem.

**Comment by omerxx** [comment]
I can have it create a new DB table with the years. But that's just 1 table for 4 single column entries, and every load would have another ajax call..

Any better ideas?

**Comment by danielhers** [comment]
It would be best if you can make main.py generate the files to send when it
starts running.

**Comment by omerxx** [comment]
I have it ready, but it makes main.py loop through the DB markers to find distinct years and then creates the file with them..
Do you want that?

**Comment by danielhers** [comment]
If it doesn't take too long then it's ok. How long does it take?
@michalten can we do this in the DB?
