### ISSUE TITLE
Add provider_code as a primary key in markers and as a foreign key in vehicles and involved

### ISSUE THREAD

**Issue by danielhers** [hasadna/anyway#358]
Apparently some accidents have the same `id`:

    static/data/lms/Accidents Type 1/H20081042/H2008104AccData.csv:2008000016,1,1,2,8300,528,,2,,,,,,52,2008,11,10,1,4,5,2,9,1,1,8,3,0,1,0,4,3,3,,1,1,9,9,9,1,2,2,4,44,442,0,10,1,183180,652071
    static/data/lms/Accidents Type 3/H20081161/H20081161AccData.csv:2008000016,3,1,1,1200,9992,,,,,,,,52,2008,11,3,1,4,5,2,9,3,1,9,9,0,0,0,0,5,6,,9,9,9,9,9,0,0,9,4,43,431,0,15,2,202001,644818

But their `provider_code` is different (1 for the first and 3 for the second). This results in a UNIQUE constraint failure when adding the second accident.

**Comment by omerxx** [comment]
@galraij Please note this - type1 and type3 accidents have duplicates referring the same accident id, contradicting what the LMS were telling us.
