### ISSUE TITLE
Each click on a marker adds/increments the same data to it, infinitely.

### ISSUE THREAD

**Issue by OmerSchechter** [hasadna/anyway#360]
The first time you click on a marker it shows the info-window correctly with the data.

![screen shot 2015-07-09 at 20 33 08](https://cloud.githubusercontent.com/assets/11275466/8602299/43bb386e-267a-11e5-9e42-58e146eff5ea.png)
![screen shot 2015-07-09 at 20 33 17](https://cloud.githubusercontent.com/assets/11275466/8602302/4cbefbf8-267a-11e5-8bfe-9b9207bfc7ec.png)

Each time you click it again though, it will add again the "injured" and "vehicles" data to it, infinitely.

![screen shot 2015-07-09 at 20 33 38](https://cloud.githubusercontent.com/assets/11275466/8602336/832b9278-267a-11e5-8531-d45e1ea22ef4.png)
![screen shot 2015-07-09 at 20 33 48](https://cloud.githubusercontent.com/assets/11275466/8602345/8c0d115a-267a-11e5-95e7-f3ebf34b73dd.png)
![screen shot 2015-07-09 at 20 33 58](https://cloud.githubusercontent.com/assets/11275466/8602357/95278914-267a-11e5-9bc9-f3c4f76e633f.png)

And so on..

**Comment by omerxx** [comment]
You're right.. Since the data is being called with every marker click, and markers are not loaded again unless the map has been moved.
