### ISSUE TITLE
Clicking on a marker shows text from the info-window's data floating on the map for a really small period of time(pic included)

### ISSUE THREAD

**Issue by OmerSchechter** [hasadna/anyway#361]
It is displayed for only a few milliseconds.

![screen shot 2015-07-09 at 20 55 08](https://cloud.githubusercontent.com/assets/11275466/8602891/842bf5a2-267d-11e5-86fe-26836921f500.png)

**Comment by omerxx** [comment]
Good eye!
Do you think that's worth dealing with?
We can move the AJAX call for data to the info window block..

**Comment by omerxx** [comment]
Now that you've mentioned it I can't un-see it :)
It should be fixed.

**Comment by OmerSchechter** [comment]
I'm not really familiar with the code behind it.. I just noticed that after updating `dev`
