### ISSUE TITLE
Create a toggle and a dots view

### ISSUE THREAD

**Issue by galraij** [hasadna/anyway#370]
User would choose to see the accidents as icons or dots.

![toggle_amd_dots_psd___100___layer_2__rgb_8__](https://cloud.githubusercontent.com/assets/3368312/8635578/b4e3c11a-2831-11e5-8745-f928418c8159.jpg)

@LironRS we discussed it, but it's not first priority right now. If someone else wants to take it that's fine too.

**Comment by LironRS** [comment]
@galraij it's almost ready, but I'd like to change all markers design (including toggle) option at once.. let's talk tonight
