### ISSUE TITLE
Accessing the site with a pre-chosen marker(e.g. anyway-unstable.herokuapp.com/?marker=2013043043&start_da..), loads an empty map without markers

### ISSUE THREAD

**Issue by OmerSchechter** [hasadna/anyway#375]
Loading the site with a marker in the url causes the map to load without markers.
Happens if a user refreshes the site while a marker is open, or if a user clicked on a link that had a marker in it.

**Comment by danielhers** [comment]
I just saw that simply loading http://anyway-unstable.herokuapp.com/ also results in no markers.
