### ISSUE TITLE
Type1 non-urban-intersection file misspelled

### ISSUE THREAD

**Issue by omerxx** [hasadna/anyway#390]
Trying to process the complete input files yield this:
![image](https://cloud.githubusercontent.com/assets/12237955/8721493/8f335f8a-2bc3-11e5-9077-a9bc1c7aff33.png)

The reason is a missing **t** so that process can't locate the file:
![image](https://cloud.githubusercontent.com/assets/12237955/8721423/2c917aa6-2bc3-11e5-93be-d7afd9b76c89.png)

Required: changing the original files in our directory 
`static/data/lms/Accidents Type 1/H20081042/`H20081042Intersec**t**NonUrban.csv

**Comment by danielhers** [comment]
I think I fixed that. Do you have the latest file from Drive?

**Comment by omerxx** [comment]
I only got what you sent. If it's fixed in the original file we can close this..

**Comment by danielhers** [comment]
In our zip file:
https://drive.google.com/open?id=0B4yX8HDe1VaTdWdPMXV5c2gycW8
It's called "H20081042IntersectNonUrban.csv".
