### ISSUE TITLE
Create a web page for new discussions (for the android app)

### ISSUE THREAD

**Issue by samuelregev** [hasadna/anyway#395]
at the moment, the android app use this page for existing discussions:
[URL](http://anywaycluster.azurewebsites.net/disqus/anyway-feedback?identifier=(32.08677421202568, 34.81188654899597))

and for new discussion just add "&newDiscussion=true" to the URL
[New discussion URL](http://anywaycluster.azurewebsites.net/disqus/anyway-feedback?identifier=(32.08677421202568, 34.81188654899597)&newDiscussion=true)
(notice the different in the source code when changing newDiscussion to true/false)
this is needed for the android app to recognize the first comment for adding the marker to the db.

now that my final project is almost over this server is going down and I need a similar page in order to maintain this behavior in the android app.

(I know i can use http://www.oway.org.il/discussion?identifier=... for existing discussions
but for new discussions - I don't)

**Comment by danielhers** [comment]
Are you talking about adding a discussion marker to the DB, or about
creating a thread on Disqus? For the latter I suppose you already do this
by sending a request to Disqus. For the former there is a URL that accepts
a POST parameter with the discussion details. Aren't you using it? So
discussions created on Android will only appear on Android?...

**Comment by samuelregev** [comment]
I was misunderstood.
first, every discussion created through the android app is created in ANYWAY server only.

I'll try to explain better - 
On anyway website, once a first comment has been added to new discussion a POST request is being send (as you already know)

To copy this behavior on the Android app(Sending this POST request only after first comment) I'm transferring the user to another page like this
function disqus_config() {
                this.callbacks.onNewComment = [
                    function (comment) {
                        window.location.replace("/disqus/new-discussion");
                    }
                ];
            }

but the user don't really get this page, the app stop the loading of the page and send POST request to add new marker (see [her](https://github.com/hasadna/anywayAndroidApp/blob/master/app/src/main/java/il/co/anyway/app/DisqusActivity.java#L161) )

What i need now is one of this two options
1. A webpage [like this one](http://anywaycluster.azurewebsites.net/disqus/anyway-feedback?identifier=(32.08677421202568, 34.81188654899597)&newDiscussion=true)
see source code, please notice the URL and the callback in the source code

or 

2. A webpage that will handle the POST request by itself for the first comment.

**Comment by danielhers** [comment]
You have a web page that handles the POST request, it just doesn't really
show any web page... It's meant to be used in AJAX. Do you need it to show
a web page?

**Comment by samuelregev** [comment]
Yes, I just need to show disqus for new discussions.

**Comment by danielhers** [comment]
The `/discussion` route render `disqus.html` when used with the GET method. When used with the POST method, it creates the marker in the DB according to the POST parameters, and then returns it jsonified (because that's the standard in POST routes that are supposed to be called from AJAX, I understand).
Can't you just call the `/discussion` with POST and then call it with GET (that is, redirect to it) to see the discussion web page?

**Comment by samuelregev** [comment]
That's exactly what I did at the beginning, but it caused (and will cause) empty discussion markers

**Comment by danielhers** [comment]
Oh, because the user might not submit the comment. Now I get it. So you want a web page to show the discussion dialog and then send the POST request only when it's done.

**Comment by danielhers** [comment]
Now you can use `/discussion` to open Disqus for a discussion that doesn't exist yet:
`/discussion?identifier=...&lat=...&lon=...`

Note that this is only in anyway-unstable.herokuapp.com until we merge to `master`.

**Comment by samuelregev** [comment]
Thanks, that's exactly what i needed.

only one thing tho - have you consider the option of user leaving more then one comment at once? it will cause sending the POST request few times.
(it happened [here](http://www.oway.org.il/discussion?identifier=%2832.17952521357131,%2034.9094894528389%29))

**Comment by danielhers** [comment]
Right... I'm not sure it's a problem though. It will just fail the second
one but the user won't notice.

**Comment by samuelregev** [comment]
OK, great.
I'll make the changes in the app but i won't publish it before you merge the new page.
Do you have a schedule  for this?

**Comment by danielhers** [comment]
Probably by the end of the week, once we're sure there are no major bugs...

**Comment by samuelregev** [comment]
I've found a small bug here
https://github.com/hasadna/anyway/blob/dev/templates/disqus.html#L22

it should be 
                            "identifier": "{{ identifier }}",
                            "title"     : "{{ identifier }}"

(see what happened [here](http://anyway-unstable.herokuapp.com/markers?ne_lat=30.499975995203283&ne_lng=34.57584294164735&sw_lat=30.49444775850836&sw_lng=34.55410631979066&zoom=16&thin_markers=false&start_date=1388527200&end_date=1420063200&show_fatal=1&show_severe=1&show_light=1&show_inaccurate=0&show_markers=1&show_discussions=1))

**Comment by danielhers** [comment]
Thanks! Forgot the quotes. Fixed.

**Comment by samuelregev** [comment]
Can you also add
                var disqus_url = 'http://www.anyway.co.il/discussion?identifier={{ identifier }}';

below 
                {%  if new %}

so the url saved in disqus won't be the one with "&lat=&lon=..."

**Comment by danielhers** [comment]
Done

**Comment by danielhers** [comment]
@samuelregev have you tested it from the Android app? Do you think it's ready to merge to `master`?

**Comment by samuelregev** [comment]
just need to change the disqus_url
the url saved in disqus is 
http://anyway-unstable.herokuapp.com/discussiondiscussion?identifier=(30.49392533863158,%2034.55747466534376)

**Comment by samuelregev** [comment]
my guess is that 'request.base_url' contain the 'discussion' already

https://github.com/hasadna/anyway/blob/dev/main.py#L171

**Comment by danielhers** [comment]
How about now?

**Comment by samuelregev** [comment]
looking good

**Comment by danielhers** [comment]
Not sure if you saw - it's in `master` now.

**Comment by samuelregev** [comment]
I saw, thanks.
I released a new app version in the play store that using the new page.
