### ISSUE TITLE
SQLAlchemy migration to create foreign key constraint

### ISSUE THREAD

**Issue by danielhers** [hasadna/anyway#403]
In c8c113c I added the ondelete cascade to the foreign key constraints of involved and vehicles. But the data was loaded already without this constraint. Need to write a migration to add it:
http://alembic.readthedocs.org/en/latest/ops.html

**Comment by michalten** [comment]
http://stackoverflow.com/a/27557798/585701

**Comment by danielhers** [comment]
Need to run `alembic/versions/1569548127f0_create_fk_from_vehicles_and_involved_to_.py` on `anyway-danielh`
