### ISSUE TITLE
Link from discussion back to map

### ISSUE THREAD

**Issue by danielhers** [hasadna/anyway#406]
When viewing a discussion page such as [this page](http://www.oway.org.il/discussion?identifier=(31.7457974525944,%2035.23064103187721)), there is currently no way to easily view the map in that location, although it should be easy by just taking the lat and lon from the identifier or from the DB. There should be a link in the page!

**Comment by danielhers** [comment]
Hey @samuelregev , I'd like your input in this:
Generally the URL for a Disqus thread is the full-page discussion you requested, e.g. http://www.oway.org.il/discussion?identifier=(32.3426691328871,%2034.86209750175476)
But this doesn't really show where the discussion is on the map.
That's why I added the option to link to a specific discussion and open it on the map, as in http://anyway-unstable.herokuapp.com/?discussion=(31.755411703851692,%2035.19602179527283)
I think it makes sense for the `/discussion` route to open the latter when in the web app. However, in the Android app it won't work.
I could check if the browser is a mobile device or not, but perhaps an easier approach would be to add a parameter to the `/discussion` URL that you would supply from the app. What do you think?

**Comment by samuelregev** [comment]
I think URL parameters is problematic because user can go to other discussion from inside the discussion activity(which open the full map), checking for mobile browser is better.

**Comment by danielhers** [comment]
I disabled the links to other discussions, but I see what you mean about it being more robust without extra parameters required.
Are you thinking of implementing a link back to the map from a discussion in the Android app?

**Comment by samuelregev** [comment]
I can do it easily (by extracting the identifier from the url)
But I'm not sure it's needed (unless there will be an option to show an
active discussions list to users) because in the app user can only enter
discussion from the map.

**Comment by danielhers** [comment]
Right, once I removed the links to other discussions, there's no list of links anywhere, so we can only get to it from the map.
(Except from the Disqus admin section, but that's inaccessible to the users)
