### ISSUE TITLE
* unstable * Clusters appear in wrong zoom level

### ISSUE THREAD

**Issue by galraij** [hasadna/anyway#416]
Clusters shouldn't appear when individual accidents are visible.
Here: http://anyway-unstable-pr-412.herokuapp.com/

![anyway_-_ _ _](https://cloud.githubusercontent.com/assets/3368312/9067971/3be02a9a-3ae9-11e5-8c02-297c59e9c186.jpg)

@LironRS

**Comment by omerxx** [comment]
This is not the unstable version but the new feature we're working on...
It's very buggy and clusters are not even connected yet. Issues would have to wait to when we're done

**Comment by omerxx** [comment]
All cluster issues were solved in pr-412, please reopen if this reoccurs
