### ISSUE TITLE
Add statistical charts to anyway

### ISSUE THREAD

**Issue by aviklai** [hasadna/anyway#417]
![untitled](https://cloud.githubusercontent.com/assets/3368312/15627747/57d45c56-24f6-11e6-93c5-82fb18f9e7c5.jpg)

![untitled](https://cloud.githubusercontent.com/assets/3368312/15627753/80645f68-24f6-11e6-8bf4-445c43b70977.jpg)

And add support for viewing all of the charts on clustered mode as well.

**Comment by danielhers** [comment]
@aviklai When zoomed out to cluster mode, the charts come out empty. There should be a message instead.

**Comment by aviklai** [comment]
@danielhers No problem - will do.

**Comment by danielhers** [comment]
@aviklai are you still working on charts?
@benzione has plans for more informative charts as well as a BI dashboard.

**Comment by aviklai** [comment]
Currently finished, unless you have more ideas of charts you think we should add do ANYWAY.
Or do you want to switch the whole chart development to vizway?

**Comment by danielhers** [comment]
No, the opposite - I want vizway to merge into ANYWAY :)

**Comment by aviklai** [comment]
What help do you need there? I still didn't get a chance to view it but I didn't see any open issues.

**Comment by danielhers** [comment]
There is #505... It's not very specific but the idea is to make that a
module in ANYWAY, perhaps similar to the charts.

**Comment by danielhers** [comment]
@galraij @aviklai please add a link her to the mock-up for more charts.

**Comment by danielhers** [comment]
@aviklai would you say this is done?

**Comment by aviklai** [comment]
@danielhers I think for now it is.
