### ISSUE TITLE
Missing instructions on readme file - Installing phyton-tk

### ISSUE THREAD

**Issue by jiddisch** [hasadna/anyway#419]
After insalling the project on a clean Ubuntu I got an error.
The solution was to install it with the following command: apt-get install python-tk

**Comment by omerxx** [comment]
Python's tkinter lib should be updated to `requirements.txt`

@aviklai

**Comment by aviklai** [comment]
I haven't found a package that I can put in  requirements.txt.
Seems lik using 
apt-get install python-tk 
is the best way and it needs to be updated in the readme file.

**Comment by omerxx** [comment]
There has to be a way to automate it..

Beyond that I think we should start thinking of automating the whole environment config step

עומר

ב-18 באוג 2015, בשעה 00:44, Avi Klaiman <notifications@github.com> כתב/ה:
