### ISSUE TITLE
Design font icon library for ANYWAY

### ISSUE THREAD

**Issue by LironRS** [hasadna/anyway#420]
The library will include unique icons for markers, info-window, filter buttons, and menus.
An icon that replaces text must have an on-hover explanatory title.

**Comment by LironRS** [comment]
@galraij let's make a list of icons next Monday so we can add them to the new markers

**Comment by galraij** [comment]
Yep, and If i’m not coming we will do it online.

**Comment by danielhers** [comment]
@LironRS @galraij still relevant?

**Comment by galraij** [comment]
Finished!
