### ISSUE TITLE
Compile and add an "ANYWAY Contribution Guidelines" .md doc to repos

### ISSUE THREAD

**Issue by LironRS** [hasadna/anyway#421]
The doc should include the following:
- Reporting a bug
- Pull Requests
- General workflow
- Conventions
- Coding style
- Periodic Slack meetings
- Community Guidelines
- Open-source restrictions

If you have any suggestions, please feel free to share!

**Comment by danielhers** [comment]
Anything left to do for this issue?

**Comment by LironRS** [comment]
Nope.
