### ISSUE TITLE
Automate last 4 years in the new filter bar

### ISSUE THREAD

**Issue by omerxx** [hasadna/anyway#424]
As it used to be in the old bar - use `ACCYEARS` to remove hardcoded years in `changeDate`

**Comment by danielhers** [comment]
See here: https://github.com/hasadna/anyway/blob/dev/static/js/app.js#L1003

This list of years for the filter is hard-coded. It should be loaded from the variable `ACCYEARS` which is written to `static/js/years.js` by `main.py`.

**Comment by AKorets** [comment]
How to assign this issue to me, and close it?

**Comment by omerxx** [comment]
No need to assign if it's done. Closing.
