### ISSUE TITLE
New sidebar scrollbar glitches

### ISSUE THREAD

**Issue by danielhers** [hasadna/anyway#428]
There are two scrollbars where there should be one, and neither is properly aligned:

![uploads/86d5f808-abe5-4d36-b90d-11258dfe1be1/Selection_001.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F86d5f808-abe5-4d36-b90d-11258dfe1be1%2FSelection_001.png)

**Comment by omerxx** [comment]
I've encountered that mostly with the marker scroll.
What browser are you using?

**Comment by omerxx** [comment]
Happens on Safari, seem ok on Chrome.
@LironRS will take a look when she finds time

**Comment by LironRS** [comment]
@omerxx @danielhers Does this still happen (both on infoWindows and sidebar)? If so, please provide more info so I can reproduce and debug it.

**Comment by danielhers** [comment]
Here it is on Chromium 44.0.2403.107:
![screenshot](https://cloud.githubusercontent.com/assets/263363/10915670/68686cf8-8260-11e5-8b8e-81bafd9dab83.png)
![screenshot-1](https://cloud.githubusercontent.com/assets/263363/10915696/8e237c62-8260-11e5-804c-b3dcaacb96b8.png)

Both the sidebar and the InfoWindow contain disabled scrollbars in addition to the usable ones.

**Comment by HamutalCohen3** [comment]
I want to assign to the issue. are you still working on it @LironRS ?

**Comment by omerxx** [comment]
@HamutalCohen3 enjoy.
@LironRS has a lot on her plate already.
Reassigning this to you
