### ISSUE TITLE
New sidebar compatibility with safari

### ISSUE THREAD

**Issue by danielhers** [hasadna/anyway#429]
Changing tabs in the new sidebar sometimes fails to make the previous tab disappear, so they tabs overlap rather than replace each other:

![uploads/861cc52c-1b7d-4139-a8c1-1bcb8bc368bd/Selection_002.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F861cc52c-1b7d-4139-a8c1-1bcb8bc368bd%2FSelection_002.png)

**Comment by omerxx** [comment]
Happens on Safari, seem ok on Chrome.
@LironRS will take a look when she finds time

**Comment by LironRS** [comment]
Sidebar safari fix #446 was merged, issue closed.
