### ISSUE TITLE
Change downloaded CSV filename to a meaningful name

### ISSUE THREAD

**Issue by danielhers** [hasadna/anyway#430]
Right now when clicking the "download CSV" button, the generated file's name is simply `data.csv`, but the contents are generated according to the current view.

![uploads/db90529c-68ef-4882-9bfd-965b39f807a0/Selection_003.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fdb90529c-68ef-4882-9bfd-965b39f807a0%2FSelection_003.png)

For added clarity, the filename should also be generated according to the current view parameters.

**Comment by danielhers** [comment]
Perhaps depends on #423 for a short unique identifier for the current view.
@omerxx

**Comment by omerxx** [comment]
Actually when it comes to a file name I think it should be something like
`Anyway-accidents-<DATE>.csv`
The file will only contain accidents data from the view so I don't know if having the complete path would be helpful

**Comment by danielhers** [comment]
Not the complete path, but something to identify the view so that you know
where the data came from.

**Comment by kilaka** [comment]
Discussing with Omer, we thought the search dates are most important and the most user friendly metadata. Example:
Anyway-accidents-from-2014-01-01-to-2015-01-01.csv
@danielhers, what do you think?

**Comment by danielhers** [comment]
This is fine, until we have a unique short identifier for the exact view (a
hash of all the parameters).
