### ISSUE TITLE
New sidebar "menu" icon still does nothing

### ISSUE THREAD

**Issue by danielhers** [hasadna/anyway#431]
Either remove it or make it do something.

![uploads/4d57bfd8-6ae7-4b5a-91b3-a5058315103b/Selection_004.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F4d57bfd8-6ae7-4b5a-91b3-a5058315103b%2FSelection_004.png)

**Comment by omerxx** [comment]
It's going to scroll the menu out. 
@LironRS is in final stages of implementing this.
