### ISSUE TITLE
Add filter option for type 1/3

### ISSUE THREAD

**Issue by omerxx** [hasadna/anyway#432]
Under `עוד` section add another filter for presenting accidents of type 1 or 3

Please reassign to me when the buttons are ready

**Comment by danielhers** [comment]
Why is this interesting for the user?

**Comment by galraij** [comment]
The LAMAS will יתבעו לנו את הצורה אם לא

**Comment by LironRS** [comment]
@omerxx Ready.. pull from here: https://github.com/LironRS/anyway/tree/typeFilterOption

**Comment by omerxx** [comment]
@LironRS could you please push it to the public repo as a new branch?

**Comment by LironRS** [comment]
@omerxx - there you go https://github.com/hasadna/anyway/tree/typeFilterOption

**Comment by omerxx** [comment]
Fixed.
