### ISSUE TITLE
Facebook logon and link on about page is broken

### ISSUE THREAD

**Issue by robi-y** [hasadna/anyway#433]
Menu -> About -> Upper level corner

**Comment by danielhers** [comment]
Please provide a screenshot, I'm not sure what's broken.
Also, please label either `master` or `dev` according to whether the bug is in oway.org.il or anyway-unstable.herokuapp.com

**Comment by robi-y** [comment]
![image](https://cloud.githubusercontent.com/assets/1009495/9709544/45e96a08-5536-11e5-9a13-c53a7d8f4938.png)

**Comment by omerxx** [comment]
Looks fine here..

**Comment by robi-y** [comment]
sorry. It was probably an anti social firewall. closing
בתאריך 7 בספט׳ 2015 19:20,‏ "Omer Hamerman" <notifications@github.com> כתב:
