### ISSUE TITLE
Fix Grey Area on Sidebar Toggle via Google Maps API

### ISSUE THREAD

**Issue by LironRS** [hasadna/anyway#443]
<img width="663" alt="screen shot 2015-09-22 at 12 21 52 am" src="https://cloud.githubusercontent.com/assets/12143791/10005442/f9dfc702-60bf-11e5-91a8-e72a7218f0c8.png">

**Comment by omerxx** [comment]
Waiting for this to be on `dev`

**Comment by omerxx** [comment]
I looked around a little, it's not straight forward as I thought it is.
Something with google api and the map reload just don't work.
I can work on this but I'll be away for the close week, if you guys want to deal with it you are more than welcome... @LironRS @OmerSchechter @aviklai @danielhers @HamutalCohen3

**Comment by omerxx** [comment]
The grey area disappears when the window size is changing or the chrome dev tools is opened
