### ISSUE TITLE
Add Accident Icons to Sidebar List

### ISSUE THREAD

**Issue by LironRS** [hasadna/anyway#444]
**after Icon Library is complete
<img width="299" alt="screen shot 2015-09-22 at 12 27 29 am" src="https://cloud.githubusercontent.com/assets/12143791/10005586/bebdc754-60c0-11e5-82d6-7075b1c84cea.png">

**Comment by omerxx** [comment]
This involves adding an `else` containing the relevant case under `getIcon()` which is located in `constants.js`

**Comment by danielhers** [comment]
@ronish31 are you working on this or should someone else do it?
