### ISSUE TITLE
Share constants between client and server

### ISSUE THREAD

**Issue by danielhers** [hasadna/anyway#447]
See http://stackoverflow.com/a/14204193/223267

Both `static/js/constants.js` and the server files such as `models.py` and `main.py` define constants, sometimes the same ones. They can be shared to avoid duplication.

**Comment by AKorets** [comment]
I am planing to share the constans by bootstraping them to index.htm. like in this checkin  05ba8d44916eac8ac32ca0bd8b317876b6c9a852
