### ISSUE TITLE
Remove TK dependency in process.py

### ISSUE THREAD

**Issue by danielhers** [hasadna/anyway#450]
`process.py` uses TK for the file browsing dialog, but it means that the script can't be run from a headless server (such as Heroku) even if the user doesn't need the file browser currently.
Need to remove this requirement so it can be used.

**Comment by omerxx** [comment]
What would you like to change the file selection mechanism to?
* cmd line arg?
* User input?

**Comment by danielhers** [comment]
I think TK is a nice option, but it should only be imported if it is
available (try/catch maybe). Otherwise I think it should fallback to
console input.

**Comment by omerxx** [comment]
Literally move the `import tkinter` to a `try`?
Never thought of doing such a thing as an option

**Comment by danielhers** [comment]
Sure, why not?
