### ISSUE TITLE
Update united.py to load from new CSV format

### ISSUE THREAD

**Issue by danielhers** [hasadna/anyway#457]
The CSV files received from United Hatzalah now has another column: the first column is the Mission ID, which will be used as the `id` field instead of the convoluted solution we used with the data and line number.
Once the script is updated, we'll remove all existing United accidents from the DB (due to the change in the `id` field) and re-load everything.

**Comment by danielhers** [comment]
Related to #427

**Comment by omerxx** [comment]
@danielhers - Should we ignore all past accidents with the old csv structure?

**Comment by danielhers** [comment]
Yes. We can always ask for a historical report with all the required columns.

**Comment by omerxx** [comment]
So it would be also okay to delete all gmail data with old structure too...

**Comment by danielhers** [comment]
Right.

**Comment by omerxx** [comment]
Do you have exact date and time point of change from which I should keep?

**Comment by danielhers** [comment]
October 6, 2015, 10:00AM
