### ISSUE TITLE
Update the project to be compatible with Flask-Login 0.3.2 version

### ISSUE THREAD

**Issue by SimonMand** [hasadna/anyway#466]
Flask-Login has a new version 0.3.2. This version updates the class "flask_security.core.AnonymousUser". 
Now "is_authenticated" became a property instead of a method.
We should:
1) Update the project that each call to is_authenticated is a call to a property
2) Add new line to requirements.txt: Flask-Login==0.3.2
![screen shot 2015-10-17 at 4 49 32 pm](https://cloud.githubusercontent.com/assets/13013858/10602269/086bb814-7720-11e5-861b-bc8a90f96965.png)

**Comment by omerxx** [comment]
@SimonMand did you make sure this happens with every new installation?
Yesterday after running `requirements.txt` I had no trouble.
If you did, I think the best approach would be `try`ing it as a method and catching an exception as a property, so that people with already installed environments wouldn't have to reinstall different packages.

**Comment by danielhers** [comment]
It's generally expected that everyone install requirements.txt after every
pull.

**Comment by omerxx** [comment]
@danielhers simply installing requirements.ext on my environment did not change the discussed version.
@SimonMand claims that a run from scratch is calling a different version.. I'm not sure how is that possible but if that's the case we should take care of it

**Comment by danielhers** [comment]
Flask-Security requires `Flask-Login>=0.1.3`, so any version newer than it
will satisfy it. In an environment where an old version is already
installed, it won't upgrade it. But if it isn't, it will install the newest
version.

**Comment by omerxx** [comment]
@SimonMand, @danielhers: Can this be closed then?

**Comment by danielhers** [comment]
No. I thought @SimonMand was going to create a pull request, but this is a very simple change. I can do it myself.

**Comment by SimonMand** [comment]
Yes, it's up to me.
I've changed all the places that treat "is_authenticated" as method to treat it as a property.
But I still haven't added the tests for at least the basic view methods.
I think next week I might have some time. I've just landed in Berlin a few days ago and still haven't established the basic stuff here :)
So if you are a bit patient, I will try to do it soon

**Comment by danielhers** [comment]
Don't worry, I'll do it.
The tests require a different issue though.
Viel Spaß in Berlin!
