### ISSUE TITLE
United marker title is fixed instead of using DB info

### ISSUE THREAD

**Issue by omerxx** [hasadna/anyway#471]
To be fixed in `marker.js`

**Comment by omerxx** [comment]
We're not there yet... the united marker's title is still getting the `single` title load which brings up a parsed string a little off:

![image](https://cloud.githubusercontent.com/assets/12237955/10920617/b860d9d4-8279-11e5-9b32-7d011b899400.png)

**Comment by LironRS** [comment]
@omerxx That's exactly what I said at #473 .. you need to find out why the same marker is rendered twice - once as "united" and another as "single". I removed the case for "united", as you mentioned that you want the full title, and also changed the structure for the infoWindow a bit - there we duplicate values. Please look at the changes and try to figure out why it is called twice and let me know if there's anything I can do.
