### ISSUE TITLE
Small clusters/aggregated icons with inaccurate location appear more opaque than they should

### ISSUE THREAD

**Issue by OmerSchechter** [hasadna/anyway#472]
The problem that @danielhers describes in issue #123 seems to be back.
Quoting Daniel:
> When there are multiple accidents that have inaccurate locations, the opacity of the "multiple accidents" icons accumulate so that the marker looks like an accurate location. The opacity should be just like a single accident with inaccurate location.

**Comment by LironRS** [comment]
@OmerSchechter @danielhers - I'm on it, will keep you posted

**Comment by OmerSchechter** [comment]
The function which calculates the opacity(from `marker.js`):
```javascript
opacitySeverityForGroup : function() {
        var group = this.model.get("groupID") -1;
        this.marker.icon = MULTIPLE_ICONS[app.groupsData[group].severity];
        if (app.groupsData[group].opacity != 'opaque'){
            this.marker.opacity = INACCURATE_MARKER_OPACITY / app.groupsData[group].opacity;
        }
    }
```
