### ISSUE TITLE
Empty app view on load

### ISSUE THREAD

**Issue by danielhers** [hasadna/anyway#485]
When loading http://anyway-unstable.herokuapp.com/, I often get an empty app view:

![uploads/a3ddb391-7180-4aa5-b41d-a212c0cea0e4/Screenshot-3.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fa3ddb391-7180-4aa5-b41d-a212c0cea0e4%2FScreenshot-3.png)

Looking at the JS console, I see the following error:

```
Uncaught ReferenceError: AppView is not defined
```

This is fixed after refreshing enough times (sometimes more than 5).
Perhaps there is some kind of a race condition, such that the AppView is being requested before being created.

**Comment by omerxx** [comment]
This is a backbone issue, from quick googling it seems that we may be using  `AppView` before the page is fully loaded, which may explain the reason for inconsistency.
Maybe moving it under a scope of `document.onload = function ...` ?
@OmerSchechter / @LironRS ?

**Comment by omerxx** [comment]
@danielhers: does running entire `app.js` function after `document load` sound reasonable?

**Comment by danielhers** [comment]
I think so. Need to check the performance hit on the app loading.

**Comment by uda** [comment]
Should this issue be reopened? it is still happening.

**Comment by daonb** [comment]
To recreate:
In firefox, open a new private window, type in the address line: http://www.anyway.co.il

**Comment by simonaho** [comment]
It might be a different issue

**Comment by uda** [comment]
@simonaho @danielhers is this still relevant?

**Comment by ziv17** [comment]
Not relevant any more
