### ISSUE TITLE
Clusters show next to accidents when zooming in

### ISSUE THREAD

**Issue by omerxx** [hasadna/anyway#488]
I think the problem only occurs after using the date filters on cluster mode.
There are several weird behaviors when doing that..
Any ideas?
![image](https://cloud.githubusercontent.com/assets/12237955/11188704/dff72ad2-8c94-11e5-9660-0da20623d250.png)

**Comment by omerxx** [comment]
@danielhers @aviklai @OmerSchechter @HamutalCohen3 @LironRS :
Did any of you encounter this?
If you did not we can close this one

**Comment by danielhers** [comment]
I did, once. Not recently though. Let's give it a few days to see if anyone
encounters it.

**Comment by omerxx** [comment]
@danielhers I think I've noticed it yesterday when @galraij presented the unstable version.
I think it occurs when we change some of the filters while using cluster mode. Not sure though...
We can leave this closed until anyone encounters it again
