### ISSUE TITLE
Discussions are not displayed on the map

### ISSUE THREAD

**Issue by danielhers** [hasadna/anyway#509]
Creating a discussion does not result in a marker showing on the map (as it should), and existing discussions are not displayed either.
This could either be a DB problem or a front-end problem. Further investigation is required.

**Comment by danielhers** [comment]
Looks like a client-side problem. The discussion markers are being created and sent and added to the Backbone model, and their `markerView` are created. But they are just not shown on the map.

**Comment by omerxx** [comment]
Maybe the fact that the icons presentation method was changed left the discussions icon out?
They don't have a CSS solution. I assume if they would, they would be presented

**Comment by danielhers** [comment]
But they do have a part in the CSS: https://github.com/hasadna/anyway/blob/dev/static/css/markers.css#L1

Maybe it's incorrect?

**Comment by omerxx** [comment]
Right.. Don't know.
@LironRS / @HamutalCohen3 ?

**Comment by danielhers** [comment]
Found the problem. There was a `setMap` missing.
