### ISSUE TITLE
Adding fabric as a an assisting dev tool

### ISSUE THREAD

**Issue by omerxx** [hasadna/anyway#525]
Fabric is a python library that allows managing shell tasks in a pythonic simple way.
We can use it for all our dev tasks in one tool.
Examples for usability:
Running the application: `fab anyway`
Rebuilding accidents DB would require: `fab rebuildDB`
Updating requirements: `fab update`
And so forth..
This could save debugging time for envs failing to run the app simply for foregetting to `export` the DB link, or building the data without having the model. Generally I'd like to remove the headache of installation and dependencies so that developers can use their time to develop...

Tasks can be updated all the time.
Once we move our cloud migration [#463] is complete this could be used to manage our nodes and the app on them...

What do you say?
@danielhers @aviklai

**Comment by simonaho** [comment]
Looks cool! Are there any penalties? performance maybe?

**Comment by omerxx** [comment]
Nope. It's a simple tool for managing ssh and shell tasks.
It's not a must, and people don't have to use it.

**Comment by simonaho** [comment]
Looks great.

**Comment by r-darwish** [comment]
Fabric doesn't (and doesn't plan to) support Python 3. I think this issue should be closed.
