### ISSUE TITLE
No markers on map in Android app

### ISSUE THREAD

**Issue by danielhers** [hasadna/anyway#526]
I know it's a problem in the Android app and not in the web app, but it's serious enough.
Since the change in the API, probably, the API calls from the Android app are missing required parameters. This causes no markers to be returned to the Android app. The solution is either to fix the app or to allow omitting parameters in the API (`/markers` route), giving them default values.

**Comment by danielhers** [comment]
Example for bad request:

    http://www.anyway.co.il/markers?ne_lat=31.781489419260584&ne_lng=35.201902873814106&sw_lat=31.771292204835383&sw_lng=35.19366279244423&zoom=16&thin_markers=false&start_date=1388527200&end_date=1420063200&show_fatal=1&show_severe=1&show_light=1&show_inaccurate=1&format=json&show_markers=1&show_discussions=1

**Comment by omerxx** [comment]
If I understand correctly it the change in `ARG_TYPES` which we have to deal with.
I can set non-mandatory values..
@avielg had the same issue and managed to overcome it. how?

**Comment by danielhers** [comment]
Right, [here](https://github.com/hasadna/anyway/blob/dev/main.py#L131) the arguments are taken from `request.values` with bracket notation, which raises an exception if the argument is not present. Using `get` instead will result in `None` being returned in that case instead, or possibly a default values (the second argument to `get`). The `ARG_TYPES` dictionary could be mapping argument names to `(type, default)` pairs, and then the iteration would be

    {arg: arg_type(request.values.get(arg, default_value)) for (arg, (arg_type, default_value)) in ARG_TYPES.iteritems()}

What do you think?

**Comment by omerxx** [comment]
I guess that would be the best option if the app is not updated.
Is there anyone currently working on it?

**Comment by danielhers** [comment]
Currently no one is working on the Android app. We might get some
volunteers to work on it soon though. Still, it would be a good idea to add
default values.

**Comment by avielg** [comment]
@omerxx In iOS I added the missing parameters, for now hardcoded, and there an open issue in the iOS repo to add UI in the filter for these new parameters...

**Comment by omerxx** [comment]
I'll fix it tomorrow, no problem

**Comment by omerxx** [comment]
@danielhers looking at the code now, I see that changing `kwargs` comes with a big overhead forcing us to fix all `kwargs` calls in `models.py`
Trying to think of a better fix. 
If this is temporary I can `try` and `catch` when the api call fails and send another `kwargs` with the defaults built in.. Is that okay?

I think it's the right way to go because the reason we're doing this change is a temporary phase where our app isn't maintained. This fix would not contribute in any other way. moreover - our `bounding_box_query` test would return false results (always true)

**Comment by danielhers** [comment]
I think it's actually good to have default values. When we add more
parameters, we shouldn't have to wait for all the clients to update too; we
should be backward compatible. Querying the server for markers should be
possible even with a short URL, without all the parameters specified, and
not just as a temporary workaround.
To me it seems there are only two places in `main.py` that use `ARG_TYPES`.
If the code is the same, then this is exactly the situation where it should
be factored out to a function, so that changes will not need to be made in
more than a single location.
There's also the code in the `index()` that reads parameters from
`request.values`, but it doesn't use `ARG_TYPES` since it's slightly
different. I think it can stay as it is right now, as it's not really part
of the API - the mobile apps never need to call it.

**Comment by omerxx** [comment]
Agreed. I'll get the defaults in as part of ARG_TYPES

**Comment by omerxx** [comment]
@danielhers Thanks for the fix.
Can this be closed?

**Comment by danielhers** [comment]
Yes
