### ISSUE TITLE
Server error when querying clusters

### ISSUE THREAD

**Issue by simonaho** [hasadna/anyway#532]
Summary icons dissapeared fron the accumulative view.
![image](https://cloud.githubusercontent.com/assets/16196934/12074749/56f38020-b16d-11e5-8ab0-c3d2256a1fa7.png)

**Comment by danielhers** [comment]
Caused by #531 (fixing #526) @omerxx. `ARG_TYPES` was changed to a dictionary of tuples (pairs), but the clusters function still treats it as if it was in the old format:

    File "/app/main.py", line 218, in clusters 
        kwargs = {arg: arg_type(request.values[arg]) for (arg, arg_type) in ARG_TYPES.iteritems()}
