### ISSUE TITLE
Facebook login fails on production

### ISSUE THREAD

**Issue by danielhers** [hasadna/anyway#550]

**Comment by danielhers** [comment]
On oway.org.il, trying to log in with Facebook results in `Invalid redirect_uri: Given URL is not allowed by the Application configuration`

**Comment by simonaho** [comment]
@aviklai did you see this?

**Comment by aviklai** [comment]
@danielhers @simonaho Can you try now? I added http://www.oway.org.il to the Valid OAuth redirect URIs in Facebook Developer console and it seems to work fine now.

**Comment by danielhers** [comment]
Working, thanks.
