### ISSUE TITLE
Google Play icon is missing

### ISSUE THREAD

**Issue by danielhers** [hasadna/anyway#553]
The link to the Android app should have an icon, but it fails to load:

![uploads/eaeda4e1-6269-42c1-ab9b-95a971207334/Selection_004.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Feaeda4e1-6269-42c1-ab9b-95a971207334%2FSelection_004.png)

**Comment by danielhers** [comment]
Same is true for the About modal.

**Comment by siv123456** [comment]
Hi Daniel,

I'm just learning so let me just make sure i did the right thing:
1. added a png file to static/img directory.
changed the src in html to this file ( "static/img/android-google-play.png" )
when loading the local site ,things look ok.
should i check anything else ? 
if its ok, i just commit the new png file + the index.html with my fixes ? ( of course making sure that mine are the only changes when comparing to the dev branch)

**Comment by siv123456** [comment]
this is how it looks like : 
![issue 553](https://cloud.githubusercontent.com/assets/10827288/13230019/66a2fda4-d9ac-11e5-80e5-b34c50e9fd5c.jpg)

**Comment by danielhers** [comment]
This would work great, but perhaps a better idea is to still use Google's icon hosted on their servers, just fixing the URL to the correct one. The icon `en_generic_rgb_wo_60.png` is no longer available, but this one is: https://play.google.com/intl/en_us/badges/images/apps/en-play-badge.png (an up-to-date badge can be generated [here](https://play.google.com/intl/en_us/badges/))
