### ISSUE TITLE
Add user preferences to include notification on accidents near a location

### ISSUE THREAD

**Issue by simonaho** [hasadna/anyway#558]
Add user preferences to include notification on accidents near a location.
This will include preferred location, required distance from location, accident severity, and optional history report.
Tables general preferences:
foreign key, primary key  - userid, minimumDisplayedSeverity, resourcetype(string)
Report preferences
foreign key, primary key  - userid, line #, recieve historical reprot (y/n),howManymonthsback (int), latitude, longtidute, radius (int), minimum severity (enum),

**Comment by aviklai** [comment]
![report_history2-anyway](https://cloud.githubusercontent.com/assets/8260668/14388706/fac7cce2-fdb7-11e5-9fc2-05a31b6ee9c9.png)

**Comment by aviklai** [comment]
I uploaded Lihi's UI proposition.
