### ISSUE TITLE
כאשר אני מחפש את המיקום "נתיבי איילון" בשדה החיפוש 

### ISSUE THREAD

**Issue by LIRONBEN3** [hasadna/anyway#565]
כאשר אני מחפש את המיקום "נתיבי איילון" בשדה החיפוש  
אני מקבל בהשלמות האוטומטיות "נתיבי איילון ראשלון לציון" ולא תל אביב
על סמך מה עובד המנוע חיפוש?

**Comment by simonaho** [comment]
Again google map issue
