### ISSUE TITLE
כפילות בקווי האוטובוס בתחנה

### ISSUE THREAD

**Issue by LIRONBEN3** [hasadna/anyway#569]
כאשר לוחצים במפה על אייקון של תחנת אוטובוס
מוצגת רשימת קווי האוטובוס עם אותו קו מספר פעמים. 
קרה לי על תחנת 
דרך השלום/תוצרת הארץ

**Comment by simonaho** [comment]
Seems to me like a google map bug, not a ANYWAY bug
