### ISSUE TITLE
Add a number to indicate number of accidents on the map

### ISSUE THREAD

**Issue by simonaho** [hasadna/anyway#581]
Add a number to indicate number of accidents on the map

**Comment by MoodyUser** [comment]
![selection_002](https://cloud.githubusercontent.com/assets/15890521/14615572/fe02d8c6-05ae-11e6-8ee0-46d3d2218d1f.png)

**Comment by totalamd** [comment]
Duplicate of putting the number of marker group members on aggregated icons #515
