### ISSUE TITLE
Move to DigitalOcean

### ISSUE THREAD

**Issue by danielhers** [hasadna/anyway#598]
Stop using Heroku and move our server to DigitalOcean.

**Comment by omerxx** [comment]
Hey @danielhers whats the reason for DO instead of the big ones like AWS / GCP?
And is this in progress?

**Comment by danielhers** [comment]
@uda please assist.

**Comment by uda** [comment]
@omerxx Mainly price tag, since we don't utilize the abilities of either AWS or GCP, paying that price is a waste.
I have an issue on hand with another project, after that I will return to this and update this issue accordingly.
