### ISSUE TITLE
Calendar filter - choosing day/time/holiday resets chosen dates

### ISSUE THREAD

**Issue by voronovmax** [hasadna/anyway#635]
After choosing start/end date, selecting one of the other parameters resets the chosen dates to 1/1/{selected year}.  (selected year is the year that the user picked initially)

I think it happens because selecting each of these parameters fires app.changeDate() function that part of its code resets the date.

Removing part of the code in app.js files (the function in lines -1092 -1122) seems to solve this issue.

Can I work on it?

**Comment by danielhers** [comment]
Sure, please do.
