### ISSUE TITLE
Remove the need for Java

### ISSUE THREAD

**Issue by szabgab** [hasadna/anyway#640]
Reducing the dependencies on the server would make it easier to get started with the project. Would it be possible to remove the dependency on Java? If for some reason it cannot be removed then it would be better to add it to the installations instructions.

**Comment by danielhers** [comment]
We used to depend on Java for uglifyjs, but I think we don't use it anymore. Why do you think there is a dependency on Java now?

**Comment by szabgab** [comment]
Very strange. When I set up Anyway the first time in January I bumped into this requirement, but I cannot reproduce it now.
