### ISSUE TITLE
Move to Python 3

### ISSUE THREAD

**Issue by szabgab** [hasadna/anyway#643]

**Comment by szabgab** [comment]
I've started to work on this. So far I found that `wsgiref` cannot be installed on Python 3.

**Comment by szabgab** [comment]
```
$ python3 models.py
Traceback (most recent call last):
  File "models.py", line 12, in <module>
    import localization
  File "/home/p3/work/anyway/localization.py", line 238, in <module>
    _cities = list(csv.DictReader(open(os.path.join("static/data/cities.csv"))))
  File "/usr/lib/python3.5/csv.py", line 109, in __next__
    self.fieldnames
  File "/usr/lib/python3.5/csv.py", line 96, in fieldnames
    self._fieldnames = next(self.reader)
  File "/home/p3/.virtualenvs/anyway/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe0 in position 176: invalid continuation byte
```
but event if I just run `python3` and `import localization` I get the same error

**Comment by szabgab** [comment]
`wsgiref` cannot be installed on Python 3.
Apparently Python 3 already comes with `wsgiref` so no need to install it there.

**Comment by szabgab** [comment]
```
$ python3 models.py
Traceback (most recent call last):
  File "models.py", line 12, in <module>
    import localization
  File "/home/p3/work/anyway/localization.py", line 238, in <module>
    _cities = list(csv.DictReader(open(os.path.join("static/data/cities.csv"))))
  File "/usr/lib/python3.5/csv.py", line 109, in __next__
    self.fieldnames
  File "/usr/lib/python3.5/csv.py", line 96, in fieldnames
    self._fieldnames = next(self.reader)
  File "/home/p3/.virtualenvs/anyway/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe0 in position 176: invalid continuation byte
```
but event if I just run `python3` and `import localization` I get the same error

**Comment by danielhers** [comment]
`open` in Python 3 opens the file as text with `'utf-8'` encoding. Try adding the argument `'rb'` to open as binary (the way `DictReader` expects it).
Also, I never noticed it but `os.path.join("static/data/cities.csv")` doesn't make sense... it should probably be `os.path.join("static", "data", "cities.csv")`.

**Comment by szabgab** [comment]
I might be mistaken but think the proper way is to tell `open` to use the necessary encoding via `encoding='cp1255'`. This works in Python 3 but have not checked in Python 2 yet.

**Comment by danielhers** [comment]
Apparently in Python 2 it's not necessary (assuming it has been working so far), but if it works then lets add it.

**Comment by simonaho** [comment]
Thanks for this contribution. Please note that moving to Python 3 will require the code volunteers to update their machine to support it.
I think that before we push this task we need to have a verified procedure for upgrading Python on the different platforms, especially because some of our volunteers are quite novice. Thanks!

**Comment by danielhers** [comment]
I think the intention is to have both 2 and 3 supported.

**Comment by szabgab** [comment]
For now I'd like to make sure that the code can work on Python 3 while still working on Python 2 and then as the project moves forward to keep it that way. Then the switch can happen later. 

BTW Python 3 was released 8 years ago and it is supported on all the platforms. OTOH Python 2 will reach end of life in 3 years.

**Comment by simonaho** [comment]
Improving infrastructure, is more than welcome. Its just should be done carefully since it always has project overheads.

**Comment by r-darwish** [comment]
@danielhers from personal experience, I advise against dual version support. Dual version support makes it hard to enjoy new features of Python 3 and makes the code heavily depended on the six library.

**Comment by r-darwish** [comment]
I'm restarting this effort in a side-branch called `python3`. It should be easier now that we're done with #722.

**Comment by r-darwish** [comment]
I've changed my mind about how we're going to do this. Trying to do it in one hit is too risky, so we'll do that in steps:

1. First I'm going to start submitting pull requests to the `dev` branch that use [six](https://pypi.python.org/pypi/six) whenever there's an incompatibility issue with Python 3.
1. When everything seems to be working, I'll start developing in Python 3 on my own machine.
1. We'll set the CI (both AppVeyor and Travis) to run the tests in Python versions 2.7, 3.5 and 3.6.
1. After we feel confident we should move the Heroku instances for Python 3.
1. When we're finally ready, move the production to Python 3
1. After a few weeks, we can drop support in Python 2

**Comment by r-darwish** [comment]
Done
