### ISSUE TITLE
Google authentication fails

### ISSUE THREAD

**Issue by ephraimberkovitch** [hasadna/anyway#674]
401. That’s an error.

Error: invalid_client

The OAuth client was not found.

Request Details
scope=email
redirect_uri=http://localhost:5000/callback/google
response_type=code
client_id=None

**Comment by uda** [comment]
That is beause the key is for `https://www.anyway.co.il`, you need to create your own key and allow access from any location, or `localhost:5000`

**Comment by r-darwish** [comment]
I think that this issue can be closed. The real issue is #691
