### ISSUE TITLE
Clusters view still very heavy

### ISSUE THREAD

**Issue by uda** [hasadna/anyway#685]
I uploaded the code to a new server, following #463.
The basic markers view is better and faster, but the clusters is still heavy and might cause server failure (I think the query is hogging the DB).

**Comment by uda** [comment]
I suggest to split the query into separate queries, each querying a specific timeframe for the same area.
This should be done both on the front-end and back-end (the back-end should do it in order to protect the stability of the service).

**Comment by simonaho** [comment]
@r-darwish this is the clusters issue. when you have time to look into it.
I understand that data is accumulated in the server and sent to FE when ready, but I'm not sure.
If this is the situation, then you are welcome to suggest data optimization on the server or Db side.

**Comment by r-darwish** [comment]
Yes, we'll probably need a different method, such as the one that @uda suggested, than what we did in the markers view. I'll look into that in the upcoming days.
