### ISSUE TITLE
 Improve system performance by using pagination between frontend and backend

### ISSUE THREAD

**Issue by simonaho** [hasadna/anyway#695]
Improve system performance by using pagination between Frontend and Backend. Perform the pagination so that accidents from the last years will appear first on the frontend. This way the responsiveness of UI will increase.

**Comment by simonaho** [comment]
@r-darwish Thanks for your contribution. Please see if this issue can be interesting for you.

**Comment by r-darwish** [comment]
I'll take a look

**Comment by r-darwish** [comment]
Should the pagination apply to both cluster view and markers view, or just the markers view?

**Comment by simonaho** [comment]
Lets start with markers view only.
But this raises the question about the markers that contain more than one accident, on markers view.
Can this be done without having ugly refresh on the UI?
If so, do continue, otherwise lets discuss how can we create a nice User experience.
Thanks!

**Comment by r-darwish** [comment]
[Here](http://imgur.com/a/JM9J7) is a screenshot of what I have so far. I picked a small number for entries per page so that we can see that it's working. What should be the number in producion?
My work is available [here](https://github.com/r-darwish/anyway/tree/pagination).

**Comment by simonaho** [comment]
Thank you for this fast and valuable contribution.
I cannot install the system locally so I will try to explain here.
In production when you change the number of years filter (on the bar in the right hand side) you get this star icon markers that when pressed display more than one marker, see images below.
So I was not sure how will these star icons be displayed with pagination.
Is it possible not to refresh them, while receiving more accidents to the same star marker?
Regarding size of page we can try 50-100 items, and see what works fine, but have it configurable so we can play with it if required.
You can check a location like Seadia Gaon St. in Tel Aviv where there are 388 accidents from 2012, to test how it works.
Also, it will be helpful to bring last year first so we don't get flickers on the list of accidents on the right hand side.
One last thing is that I don't know if the bottleneck is on the access to the database, or on communication between Frontend and backend. Optimization should be done accordingly (meaning smaller requests to DB if required, per year for example) so that we get a better performance experience.
You can send me an email to simona.holstein@gmail.com and I will send you the URL of the DB so you can test your work on a populated DB.
Thank you again for this contribution.
![image](https://user-images.githubusercontent.com/16196934/29971323-8389fd6a-8f30-11e7-88f8-c13a1cd80e75.png)
![image](https://user-images.githubusercontent.com/16196934/29971353-9f067db6-8f30-11e7-9bd8-e8a0762186d6.png)
@danielhers what do you think?

**Comment by r-darwish** [comment]
1. The star icon will not necessaraly contain all the accidents that it should, but only the fetched accidents. For example, the star icon in Seadia Gaon St. in Tel Aviv shows 2 accidents at first but when I press the "see more results" button then it starts showing more accidents.

2. The limit is set [in the cilent side](https://github.com/r-darwish/anyway/blob/pagination/static/js/app.js#L29) so I'm not sure how to make it configurable without having to change the code every time we want to change the number. I'm open to suggestions.

3. The results are sorted by time, descending. This means that pressing the "more results button" always appends results to the button of the list.

4. I'm not sure regarding what is the bottleneck, but if the database is the bottleneck the I'm not sure that my change will make things better, as I apply the limit once the records have been ordered. We will probably need to use some SQL query analyzer if we want to understand where is the bottleneck.

5. Could you perhaps provide a AWS/Azure/Google instance that I could deploy my work on so you can access it? It might make discussion easier than posting screenshots.

**Comment by danielhers** [comment]
I think this is a great idea, as it can make the application faster and more usable.
There should probably be an indication for how many accidents there should be in total in the current view, and how many of them are currently shown.
Also, it would be nice if the pagination would happen automatically without the user having to click, so the app would be usable right away but more results will be loaded after the initial load.
As for configuration of the page size, it can be sent from the server (from the context to Jinja2) and read in index.html into a variable that the JS can use. The server can read it from a configuration file.
To check what is the bottleneck, we can already see if this change improves performance with the production DB. If so, then the bottleneck is in communication or in the client, otherwise it's in the DB/server.
About a staging environment, we should ask @uda for automatic deployment of pull requests. For now we can use this feature in Heroku. If you make a PR, I'll be able to deploy it to Heroku and it will be updated automatically with the branch in your GitHub from which you made the PR.

**Comment by r-darwish** [comment]
Opened #698

**Comment by simonaho** [comment]
I will try to relate to your comments.
Let me know when the deployment is ready, so I can relate to that as well.
1. I agree with Daniel the accidents that arrive on the second page can be displayed automatically at the button of the list, no need for a special button. If we have the total number of accidents we can show on the right hand side displaying X out of y accidents.
2. See Daniel's suggestion
3. Ok
4. As Daniel said if this pagination will not solve the problem then we can try to improve the performance in the database query. Then one option can be to do a query per year, but we will open a different task for that if we find it is required. Anyway pagination toward client is always important since one cannot assume bandwidth
5. Solved by Daniel
6. ***Important *** Please make sure the old rest API continues to work since we have two mobile apps, and some client script that we need to continue working before they move to the new API
