### ISSUE TITLE
Ihud Hazala data from 2017 missing from DB

### ISSUE THREAD

**Issue by simonaho** [hasadna/anyway#700]
Ihud Hazala data from 2017 missing from DB
![image](https://user-images.githubusercontent.com/16196934/29995423-b7628c62-8ff1-11e7-98b1-d0062145d0f2.png)
![image](https://user-images.githubusercontent.com/16196934/29995425-c324ce52-8ff1-11e7-87ce-d33639dccee2.png)

**Comment by r-darwish** [comment]
![image](https://user-images.githubusercontent.com/1383193/30081113-a2e394ee-928e-11e7-8e1e-f25be38df21a.png)

They seem to be imported successfully on my machine, and I didn't change anything. Pehaps something went wrong with importing in the production?

**Comment by simonaho** [comment]
Now available also on production. Starts to feel like DB restart today did miracles. that is bad news since it might happen again :-(. closing/
