### ISSUE TITLE
Allow interruption of pagination, so we don't have to wait for all markers to arrive if we change screen  position

### ISSUE THREAD

**Issue by simonaho** [hasadna/anyway#706]
Allow interruption of pagination, so we don't have to wait for all markers to arrive if we change screen  position.
You can see the area above the HAARBAA st. is empty in the picture, markers will be added above the Haarbaa 
 st. only after the previous position markers are completely displayed. 
@r-darwish
![image](https://user-images.githubusercontent.com/16196934/30017642-ae3ea5d6-9162-11e7-99a8-22e8a78b1397.png)

**Comment by r-darwish** [comment]
Will do. Please assign me.

**Comment by simonaho** [comment]
Asked Yehuda to add you to the project, then I can assign.

**Comment by danielhers** [comment]
It's OK, I added @r-darwish .
