### ISSUE TITLE
Write some sample postgresql DB queries for redash

### ISSUE THREAD

**Issue by simonaho** [hasadna/anyway#709]
Write some sample postgresql  DB queries for redash ,such as locate all markers 300 meters from log, lat.
So that new contributors have a good starting point
Redash link: http://data.obudget.org/

**Comment by r-darwish** [comment]
Do we share the redash instance with Open Budget? Because I don't see Anyway tables there

**Comment by simonaho** [comment]
![image](https://user-images.githubusercontent.com/16196934/30215210-e508e4d4-94b7-11e7-9b89-272cdfbf1631.png)

**Comment by r-darwish** [comment]
Can you write me a description for which queries would you like to see examples for?

**Comment by simonaho** [comment]
1. All accidents 500 m around a given location with victims of age 0-7
2. All accidents on road 1 sorted by severity, and display road segment if available
3. All accidents in Tel Aviv
4. Count accidents per town
*If something is too complicated you can skip it

**Comment by simonaho** [comment]
SQL queries are now available
