### ISSUE TITLE
Download CSV shows only last two years

### ISSUE THREAD

**Issue by simonaho** [hasadna/anyway#710]
Download CSV shoes only last two years.
Change it so that it shows the list that is diaplayed in the UI

**Comment by r-darwish** [comment]
Can you provide a URL for reproduction?

I tried [this url](https://www.anyway.co.il/markers?ne_lat=32.08734963606968&ne_lng=34.80869035720821&sw_lat=32.08113193926602&sw_lng=34.7913096427917&zoom=17&thin_markers=false&start_date=1409961600&end_date=1504569600&show_fatal=1&show_severe=1&show_light=1&approx=1&accurate=1&show_markers=1&show_discussions=1&show_urban=3&show_intersection=3&show_lane=3&show_day=7&show_holiday=0&show_time=24&start_time=25&end_time=25&weather=0&road=0&separation=0&surface=0&acctype=0&controlmeasure=0&district=0&case_type=0) and and got the same number of results (249) in both CSV and JSON. I also saw results from 2014 in the CSV.

**Comment by simonaho** [comment]
Yes, now it works for me too, although it did not work through the weekned.
Yehuda, our devops has done some changes to the DB importing 2015 accidents from LAMAS, probably restarted the DB, which seemed to solve the issue.
@uda what do you think? how shell we describe this problem that disappeared now?
