### ISSUE TITLE
Add Age of accidents victims to filter

### ISSUE THREAD

**Issue by simonaho** [hasadna/anyway#717]
Add Age of accidents victims to filter and UI

**Comment by simonaho** [comment]
Requested by Ministry of education

**Comment by r-darwish** [comment]
I started working on it. There are some points to discuss.

1. Just to clarify, when you filter by a certain age group you will get all accidents in which **at least** one of the involved matches one of the desired age groups. Other involved people might be of different ages.

2. Our current age groups are in 4 years resolution. I think these are too many buttons to display in the UI, so my thinking was that we have fewer buttons which cover multiple groups, for example: ילדים, נוער, מבוגרים, קשישים. Now sure how many buttons we should have, though.

**Comment by danielhers** [comment]
How about a slider for minimum age and maximum age of all involved?

**Comment by danielhers** [comment]
No, that's silly, because you won't be able to search for accidents
involving children. So maybe a slider for minimum/maximum age of at least
one involved.

**Comment by simonaho** [comment]
1. Understood and agreed at least one in the selected age is good
2. A slider might be confusing since if I choose 0-8, I cannot have the exact filter since we get 0-7, 8-14 from Lamas. Unless we find a slider with specific stops. so I suggest a widget with multiple selection of. Checkboxes  correlated  with available groups from Lamas. That will pop up in a similar way to the calendar. Whatever is easier.

**Comment by r-darwish** [comment]
We have 18 age groups. Are we sure we don't want to unify some of them?

**Comment by simonaho** [comment]
The ministry of education were interested in the detailed resolution of age groups for children, they even wanted to add one 14-18 that does not exist today. So we can do something like 0-7, 7-14, 14-24, adults, and then 60-70, 70-80, 80+ if we want less groups, or if you find a slider that you can stop in the specific age group values that will also be nice, then you can have 18 stops 0,7,14,24 etc.
What do you think?

**Comment by r-darwish** [comment]
I'm not sure I'm a fan of a slider, but I'm good with your division. This is our current age groups:

- 00-04
- 05-09
- 10-14
- 15-19
- 20-24
- 25-29
- 30-34
- 35-39
- 40-44
- 45-49
- 50-54
- 55-59
- 60-64
- 65-69
- 70-74
- 75-79
- 80-84
- 85+

So it'll have to be 0-9, 10-14, 15-24, 25-59, 60-69, 70-79, 80+

**Comment by galraij** [comment]
Can we try to see what others/similar projects do? My instincts tells me slider would be more intuitive (like tinder ;) ). But I might be wrong 

‫ב-8 בספט׳ 2017, בשעה 18:31, ‏‏Roey Darwish Dror ‏<notifications@github.com> כתב/ה:‬

**Comment by simonaho** [comment]
Slider is very common, but I agree with Roey that tuning them is less convenient, it's hard to select your accurate range, you can try here (http://www.travelist.co.il)  for example after you choose a destination to set you prefered hour range, so you can feel what I mean.
Ebay for example don't use slides, they give you a few options, and then they have a see all button, where you can choose from the full list (see image below).
@galraij What do you think?
One more issue @r-darwish is to check if this ranges were not changed over the years, if there were changes in the ranges then we might be required to display a dynamic set to ranges, by the most coarse range. 
If we go for checkboxes, then I would suggest this set:
- 00-04
- 05-09
- 10-14
- 15-19
- 20-24
- adults
- 70-74
- 75-79
- 80-84
- 85+
![image](https://user-images.githubusercontent.com/16196934/30221650-c7dbdd02-94cc-11e7-86a3-f58757aa69f9.png)

**Comment by simonaho** [comment]
Looks like @galraij is busy?
So, since it will be very nice to get back with age filter, when we go to meet them again.
So you can choose between the ebay (old style), and Alice (new style, see below) with a large popup slider that you can tune easily, assuming the slider can display discrete values (0,4,7... ).
Then when we will have a UX contributor we can create a new issue for UX fine tuning.

![image](https://user-images.githubusercontent.com/16196934/30262449-a1c92412-96d9-11e7-8883-9d90c6182e26.png)

**Comment by r-darwish** [comment]
I think I prefer ebay

**Comment by simonaho** [comment]
Lets go fo it :-)

**Comment by r-darwish** [comment]
Sorry that I didn't get to that. Hopefully I will get to that during this weekend.
