### ISSUE TITLE
Python SDK

### ISSUE THREAD

**Issue by r-darwish** [hasadna/anyway#721]
I spoke with @atalyaalon and we agreed that having an official Python library for interacting with the site would be useful. I don't have permissions to create a new project in @hasadna, so can someone please create a new project called `anyway-sdk` and give me owner permissions?

**Comment by simonaho** [comment]
Can you please explain the advantages you see in such a package.
Will it be in parallel to the REST API? So I have to add each feature to both?
@danielhers

**Comment by r-darwish** [comment]
It will provide a nicer interface than crafting REST requests manually in Python. 

For example, instead of doing `marker['severity']` which will get a number between 1-3 that you have to remember its meaning, you will be able to do `marker.severity` and get a `Severity.CRITICAL` object, which would be an [enum](https://docs.python.org/3/library/enum.html#creating-an-enum).

Another option is that instead of having to specify coordinates manually, you could call `get_accidents(location="ז'בוטינקסי רמת גן")` and the API library would search the coordinates for you.

Another advantage is that when the library is mature, we can use it for the unittesting of Anyway by using [Flask-Loopback](https://github.com/vmalloc/flask-loopback), but that will be in a later stage.

**Comment by simonaho** [comment]
Sounds good.
Is there any common practice to remind developers to update both APIs with new features?

**Comment by danielhers** [comment]
Sound like a good idea. We can even put it on PyPI and anyone can use it in
their apps.

**Comment by r-darwish** [comment]
@simonaho I don't think that Github has any "cross-repository" issues, so the only way I see is to open seperate issues in both the SDK and the mobile apps for each new server feature that needs to be supported.

**Comment by danielhers** [comment]
And the server and client should clearly state which version they are or
depend on (API versioning, Python package versions).

**Comment by simonaho** [comment]
OK, version number can help. We can even add version number to the first API call for compatibility compliance verification.

**Comment by r-darwish** [comment]
I'll begin my work in https://github.com/hasadna/anyway-sdk-python
