### ISSUE TITLE
Use a single entry point and move source code into a package

### ISSUE THREAD

**Issue by r-darwish** [hasadna/anyway#722]
Currently, the source code of the backend is in the root directory of the project, and there are multiple scripts that needs to be run. This makes project less tidy, but more importantly, will not work under Python 3's more strict init system. 

Most of the code should be moved to subdirectory called `anyway` and all the internal imports should become relative (For example `import models` should become `from . import models`).

`main.py` should start in the root directory and should have as little code as possible. By using a framework such as [click](http://click.pocoo.org/5/) we can implement subcommands in `main.py` and keep the actual logic inside the `anyway` subdirectory.

**Comment by simonaho** [comment]
When we do this we need to prepare some migration tool to developers who have the system installed localy?

**Comment by r-darwish** [comment]
I don't think so. Just updating the README should be enough. We will probably need to change the execution path in the server and the cron job, but we shouldn't need any kind of migration steps other than that.

**Comment by simonaho** [comment]
Just trying to save the frustration of developers that their system will stop working after code update.
README is usually read only by new developers.
Any ideas?

**Comment by r-darwish** [comment]
Since there's no developers mailing list and other developers don't use Slack, the only solution I can think of is to put a big **ATTENTION** section at the beginning of the README

**Comment by simonaho** [comment]
I maintain the secret developers list :-), You have seen it when I sent the news about the ministry of Education. I will add the developers mailing list to the github, although it's quite dynamic.
Anyway that's how infrastructure modifications are, so let's do it.

**Comment by r-darwish** [comment]
Done. @simonaho can you please inform other developers that due to framework changes they are advised to read the README file again?
