### ISSUE TITLE
Move load_discussions into main

### ISSUE THREAD

**Issue by r-darwish** [hasadna/anyway#730]
I can't figure out what's the purpose of this file

**Comment by simonaho** [comment]
It might relate to this feature?
![image](https://user-images.githubusercontent.com/16196934/30341455-bb25c11a-97fe-11e7-9e00-754e47cdd223.png)

**Comment by danielhers** [comment]
Yes! I implemented the discussion feature a while ago. Discussions are kept
as markers with Disqus id. The script gets a list of ids and adds the
discussion markers.
