### ISSUE TITLE
Check installation on Windows

### ISSUE THREAD

**Issue by simonaho** [hasadna/anyway#734]
After performance improvement Celery utility was added, now we need to check that dev env can still be installed on Windows

**Comment by r-darwish** [comment]
https://ci.appveyor.com/project/r-darwish/anyway#

This is very weird. I managed to get AppVeyor working, but of all the possible errors I didn't expect to see a different number of records in the database. The same commit passed in Travis.

@aviklai - can you check if the tests pass on your machine?

**Comment by r-darwish** [comment]
Never mind that. I forgot to import united data. Seems to be working in Windows.
