### ISSUE TITLE
United parser is broken to due weather format change

### ISSUE THREAD

**Issue by r-darwish** [hasadna/anyway#767]
See [here](https://travis-ci.org/hasadna/anyway/jobs/285476700). It started happening all of a sudden and builds that used to work are now broken. I suppose that it has something to do with [this xml](https://github.com/hasadna/anyway/blob/dev/anyway/parsers/united.py#L47) that we're fetching.

**Comment by r-darwish** [comment]
We seem to miss the number 2 from [here](https://github.com/hasadna/anyway/blob/dev/anyway/parsers/united.py#L31-L40) but I have no idea what do these numbers mean. @simonaho, do you know anyone who can help?

**Comment by simonaho** [comment]
I am no familiar with the data structure. Maybe @aviklai can understand the problem.
I will also email to Gittel our contact at Ihud Hazalah, maybe she can help (I'll CC you).
Plus meanwhile, can we skip this data not to loose the accidents?
Thanks!

**Comment by r-darwish** [comment]
It works again 🤷 
Maybe it was a temporary issue with the IMS site.
