### ISSUE TITLE
Filters to work in iframe

### ISSUE THREAD

**Issue by simonaho** [hasadna/anyway#779]
Filters to work in iframe (such as severe accidents)

**Comment by r-darwish** [comment]
Actually it turns out that this is already working. It's probably implemented [here](https://github.com/hasadna/anyway/blob/dev/static/js/app.js#L1086-L1092). I still need to figure out why didn't it work for rsa, but that's another issue.

**Comment by simonaho** [comment]
Thanks! I updated Gal we can work with Or Yarok.
