### ISSUE TITLE
Selecting the accident type filter bike with victims results exception (feature was hidden from UI)

### ISSUE THREAD

**Issue by simonaho** [hasadna/anyway#802]
Selecting the accident type filter bike with victims results an empty markers list
selecting the accident type filter bike no victims returns an empty markers list

**Comment by aviklai** [comment]
It looks like there is some problems with the query to the database.
I get an error for all types of filters - not just the bikes.

**Comment by aviklai** [comment]
The markers api returns 500 in production. I checked locally against the sqlite db and it works.

**Comment by simonaho** [comment]
Currently not all markers are displayed regardless of byke query, so we will wait for this fix, then we will check this issue once again.

**Comment by aviklai** [comment]
I checked with a local postgres 10.1 version db and the query works.
Maybe if we upgrade our db version to 10.1 it will fix the issue.

**Comment by atalyaalon** [comment]
#835
