### ISSUE TITLE
Create ANYWAY widget/plug in to integrate the map in other websites

### ISSUE THREAD

**Issue by galraij** [hasadna/anyway#84]
More explanation: https://docs.google.com/document/d/1iq7_iOL0MM3y_0Mjkuh13tiGl9XZtpampymn6u6zLys/edit

![lavie_junction_ynet cropped](https://cloud.githubusercontent.com/assets/3368312/2650238/b81a7676-bf6e-11e3-915c-e5826b4e7984.jpg)

**Comment by danielhers** [comment]
Meaning: add button to show HTML for copying with <i frame=...>

**Comment by danielhers** [comment]
The URL generated is the URL that was present when loading the site, but when we update the URL by panning, zooming, changing filters, etc., it doesn't affect the URL that is shown in the dialog.
@yony need to replace `document.URL` by something that is updated with the `window.history`, or get it from Backbone, or use `app.getCurrentUrlParams` (but then we need to combine it with `app.js`).
