### ISSUE TITLE
Fix Google and Facebook login

### ISSUE THREAD

**Issue by atalyaalon** [hasadna/anyway#841]
@aviklai , can you try to fix it?

**Comment by aviklai** [comment]
@atalyaalon I checked it and it looks like the facebook login is working but google isn't.
Are the GOOGLE_LOGIN_CLIENT_ID and GOOGLE_LOGIN_CLIENT_SECRET configured in the production server?

If not, we need to add them.
If they are - please send them to me so I can test it locally + please send me the email and password for the google account of the web app so I can check all the configurations.

**Comment by atalyaalon** [comment]
@uda Can you help us with google/facebook auth?

**Comment by danielhers** [comment]
Fixed Facebook login. The problem was permission on some of the Python files on the server. They belonged to `root` and now they belong to `www-data` and it works.

**Comment by danielhers** [comment]
Well, sometimes it works, at least. Still not clear what makes it fail.

**Comment by atalyaalon** [comment]
@sa-lo-mon can you take this one?

**Comment by sa-lo-mon** [comment]
Hi, no problem I'll take this one.

**Comment by atalyaalon** [comment]
facebook logging is fixed, now we have google login to fix next.

**Comment by BarVolunteering** [comment]
Google login is working, facebook login is removed.
Closing this issue.
