### ISSUE TITLE
Cbs process fails while trying to load full lms data

### ISSUE THREAD

**Issue by ShacharOch** [hasadna/anyway#854]
When trying to import the lms data (using the command line: **python main.py process cbs**) 

I get the following assert:
File "/home/android/anyway/anyway/parsers/cbs.py", line 373, in <genexpr>
    accidents = (accident for accident
File "/home/android/anyway/anyway/parsers/cbs.py", line 215, in import_accidents
    assert(int(provider_code) == int(accident[field_names.file_type]))

The assert is caused by incorrect lms.zip folders location.

Solution for the issue:
Change the lms.zip as follows:
- The folder H20141041 should be removed from /lms/.
- The folder H20141041 should be removed from /lms/Accidents Type 3/
- The folder H20151041 should be moved from /lms/Accidents Type 3/ to /lms/Accidents Type 1/

(sug_tik column inside the .csv file is compared to the directory name: Accidents Type [number], assert caused if sug_tik value != [number])

**Comment by atalyaalon** [comment]
Thanks!
Fixed. Please download the most updated cbs data (link in the README.md file - you need to request access).
