### ISSUE TITLE
Add option to register for updates

### ISSUE THREAD

**Issue by atalyaalon** [hasadna/anyway#855]
![whatsapp image 2018-02-26 at 00 41 50](https://user-images.githubusercontent.com/20992625/36663110-33e06f66-1ae9-11e8-89c1-6ca869f0c27e.jpeg)
![whatsapp image 2018-02-26 at 00 41 50 1](https://user-images.githubusercontent.com/20992625/36663112-352d523a-1ae9-11e8-8076-b698710ace97.jpeg)

1. Add a new table of registered emails
2. There are two use cases:
- The user is logged in (via google/facebook)
- The user is not logged in, hence email is needed.

@simonaho @galraij , Do you want to add anything?

**Comment by agamaloni** [comment]
Hi @atalyaalon 
I would like to take this task .
but before assign me on, i need more info

case 1:
it look like right now both login via facebook / gmail not working
a. if the user logged in what the privilege hi get .. 

case 2:
Not sure i got it ,
what are the usages for user to enter an email ?
lats say i am creating this tab user not logged in , and now hi enter his email what should happen ? 
a. record only email address to DB 
b. ?
c. ?

please see if you can add more info

**Comment by atalyaalon** [comment]
Hi @agamaloni 
Case 1:
a. Working on it. I will update you when it'll we'll fix it.
b. Right now no privileges. However, we want to save the locations the user searches, but that will be the next feature once we'll finish this one.

case 2:
Right now only a: record the email to the DB.
As I mentioned, we want to save the location that the user searched.

Thank you so much! 
Note that @aviklai can help you with the DB tables.

**Comment by agamaloni** [comment]
Hi @aviklai

we want to add new db table that will include the location of user search + email
in code i saw that location defined by 2 objects latitude, longitude
i thought to add radius & created for the next step sending emails updates on location

Please correct me if needed , and add your thoughts

adding to model.py 

the suggest table:

class Registered_emails(Base):
    __tablename__ = "registered_emails"
    id = Column(Integer, primary_key=True, unique=True)
    email = Column(String(120))
    latitude = Column(Float())
    longitude = Column(Float())
    radius = Column(Float())
    created = Column(DateTime, default=datetime.datetime.now, index=True)
    def serialize(self):
        return {
            "id": self.id,
            "latitude": self.latitude,
            "longitude": self.longitude,
            "radius": self.radius,
            "created": self.created.isoformat()
        }

**Comment by aviklai** [comment]
@agamaloni I think that it is better to add a table like UserLocations which will be able to store multiple preferred locations for each user/
