### ISSUE TITLE
Discussions Markers - Add a figure

### ISSUE THREAD

**Issue by atalyaalon** [hasadna/anyway#885]
1. Discussions Markers contain only a color - Add discussion figure. [Example](https://www.anyway.co.il/?zoom=17&start_date=2017-07-01&end_date=2018-07-01&lat=31.90179320000001&lon=35.011900200000014&show_fatal=1&show_severe=1&show_light=1&approx=1&accurate=1&show_markers=1&show_accidents=1&show_discussions=1&show_rsa=1&show_urban=3&show_intersection=3&show_lane=3&show_day=7&show_holiday=0&show_time=24&start_time=25&end_time=25&weather=0&road=0&separation=0&surface=0&acctype=0&controlmeasure=0&district=0&case_type=0&age_groups=)
<img width="573" alt="screen shot 2018-07-01 at 11 34 10" src="https://user-images.githubusercontent.com/20992625/42132543-b534b54a-7d22-11e8-85ea-00666b2fe863.png">

**Comment by atalyaalon** [comment]
@aviklai can you take this issue?

**Comment by aviklai** [comment]
@atalyaalon are you referring to the number of discussions in that point?

**Comment by atalyaalon** [comment]
@aviklai no, I'm referring to the marker itself. In the photo above you can see a blue shade - I think there should be a figure there of discussions (I think it should be a kind of a chat box).

**Comment by aviklai** [comment]
@atalyaalon were can I find a discussion? I can't find one.

**Comment by atalyaalon** [comment]
@aviklai Thanks, I fixed it. You can see them now using the link in the description above.

**Comment by atalyaalon** [comment]
#910
