### ISSUE TITLE
Remove login button

### ISSUE THREAD

**Issue by atalyaalon** [hasadna/anyway#886]
Right now login doesn't work. 
Remove the button for now (when login will be fixed we will bring it back).
For debugging purposes - maybe we can leave it just for admins?
@danielhers @aviklai what do you think? any suggestions?

**Comment by danielhers** [comment]
Maybe remove the button but add a url route to open the modal for debugging
purposes.

**Comment by aviklai** [comment]
I agree with @danielhers - we can hide the button and open a url for the login.

**Comment by atalyaalon** [comment]
perfect. @aviklai can you handle it?

**Comment by aviklai** [comment]
I just commented out the login part and for debugging we can just uncomment it.
