### ISSUE TITLE
[dev-ops]Create backups for our production DB

### ISSUE THREAD

**Issue by atalyaalon** [hasadna/anyway#951]
create 2 types of backups:
1. Full db backup every day, that will enable us to restore the db if something happens. Keep only the past week, upload every night the backup to s3, and delete the one from a week ago.
The command is: `pg_dump anyway > anyway_full.pgdump`
This backup will only be accessed by the production, and the s3 bucket managers - and won't be open to others.
2. Backup for volunteers that doesn't contain information with sensitive info:
`pg_dump anyway -T users -T roles -T roles_users -T locationsubscribers -T report_preferences -T general_preferences > anyway_public.pgdump`
This backup will be available as well in s3 - we want to enable access only with a token (or any other way that is a good practice)

**Comment by cubann** [comment]
@OriHoch @atalyaalon I am trying to understand this issue, and good way to solve it, so I have got couple questions:

1. https://github.com/hasadna/hasadna-k8s/blob/b91251ffee390ea4ba996d232b04e8f4d0e728f6/charts-external/anyway/templates/db-deployment.yaml Is it the way how we deploy our DB? 
2. does hasadna have any general way/recommendation for backups?
3. do we have any kind of architecture, diagram of production evnrionment?

**Comment by OriHoch** [comment]
hi @cubann 

1. currently anyway production runs in a different way, but running on Kubernetes is the goal. Most other projects are already running on Kubernetes in a similar way
2. we have file-system backups of all volumes, including all DB volumes. But we don't have any DB-specific backups.
3. no, but it's all running on Kubernetes, as defined here - https://github.com/hasadna/hasadna-k8s

**Comment by atalyaalon** [comment]
perhaps @ItamarLevin is also relevant in this discussion.
1. the image in the link you've sent is not updated - we are now using a postgis image from dockerhub.
2. @OriHoch Can you elaborate a bit more or give us an example? What the difference and the advantage of backing up the db volumes vs created a DB-specific backups (e.g. postgres - pg_dump of the db)?
3. Yes, and in general @ItamarLevin and @cubann we want to make sure we're agnostic to the cloud provider - that's why we want to keep up with "hasadna"'s other projects standard, and use docker and Kubernetes.
4. @OriHoch where should we save these backups? s3? where other projects save them?

**Comment by OriHoch** [comment]
main disadvantages of filesystem backups:
* harder to restore / use the data - you have to create a new DB in the exact same version and settings as the original DB and mount a filesystem from the restore on it, where DB backup produces an SQL file you can use anywhere
* might be inconsistent / corrupted - e.g. if a DB write occurs in the middle of the filesystem backup

we currently keep backups in S3

**Comment by atalyaalon** [comment]
@OriHoch - we want to give volunteers the ability to work locally with all of the data - hence I assume we would like to have a db backup (using pg_dump in our case) rather than a filesystem backup, am I right? How do other projects allow their volunteers to work with an up to date data?

**Comment by atalyaalon** [comment]
@cubann regarding saving the backups in s3 - we have a bucket of our own - I will send you and Itamar the access details.

**Comment by OriHoch** [comment]
yes, you will need to use a DB backup for that
other projects don't have this exact requirement, but open budget uses a microservices approach so that unless you are doing some low-level infrastructure work you don't need the DB, you just access the relevant microservices which provide the data

**Comment by atalyaalon** [comment]
got it, thanks!
So @cubann - we want to create 2 types of backups:
1. Full db backup every day, that will enable us to restore the db if something happens. For this one, I believe we can keep only the past week - what do you think?
we'll upload every night the backup to s3, and delete the one from a week ago.
The command is: `pg_dump anyway > anyway_full.pgdump`
2. Backup for volunteers that doesn't contain information with sensitive info:
`pg_dump anyway -T users -T roles -T roles_users -T locationsubscribers -T report_preferences -T general_preferences > anyway_public.pgdump`

@assafdayan - just want you to be aware of this discussion - we're discussing our current production. Feel free to add your 2 cents.

**Comment by OriHoch** [comment]
You can store the db export for volunteers locally and serve it using nginx with http auth.

for example:

**ingress**

https://github.com/hasadna/hasadna-k8s/blob/master/environments/avidcovider-gcloud/values.yaml#L15
https://github.com/hasadna/hasadna-k8s/blob/master/charts-external/avidcovider/templates/ingresses.yaml

**nginx**

https://github.com/hasadna/hasadna-k8s/blob/master/charts-external/avidcovider/templates/pipelines-nginx-deployment.yaml
https://github.com/hasadna/hasadna-k8s/blob/master/charts-external/avidcovider/templates/pipelines-nginx-configmap.yaml

**Comment by atalyaalon** [comment]
@OriHoch isn't it a problem to perform it on the production?
We don't want to overload the production.

**Comment by OriHoch** [comment]
In the example i sent it's a separate pod so doesn't affect any other workload, also nginx requires very low resources

**Comment by cubann** [comment]
@OriHoch @ItamarLevin So what about using K8s CronJob https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#cronjob
for creating backups?
@atalyaalon Seems to me like it is good practice, maybe even best:)

**Comment by atalyaalon** [comment]
@cubann sounds good to me
