### ISSUE TITLE
Upgrade Pandas

### ISSUE THREAD

**Issue by r-darwish** [hasadna/anyway#970]
@atalyaalon I saw that you constrained the version of pandas in 34227b47b53a3601dc2b487f1442efd5bb3743db.

Pandas 0.22 is broken in Python 3.7. Could you tell which errors did you see?

**Comment by uda** [comment]
Any reason this is still open? I am trying to test on python 3.7

**Comment by atalyaalon** [comment]
Pandas is upgraded. Python 3.7 should work well.
